// Code generated by craftgo. DO NOT EDIT.

package bindings

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/bindings_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/bindings"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Echo wire-renamed params. Path, query, header, and cookie each use an explicit @decorator("wire-name") distinct from the Go field name.
//
// EchoWire returns the GET EchoWire handler.
func EchoWire(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.WireRenameReq
		req.UserID = r.PathValue("user_id")
		_q := r.URL.Query()
		if _v := _q.Get("search_q"); _v != "" {
			req.Q = &_v
		}
		if !server.RequirePresent(w, r, len(r.Header.Values("X-API-Key")) > 0, "X-API-Key", "header") {
			return
		}
		req.APIKey = r.Header.Get("X-API-Key")
		if !server.RequirePresent(w, r, server.CookiePresent(r, "session_id"), "session_id", "cookie") {
			return
		}
		if c, err := r.Cookie("session_id"); err == nil {
			req.Session = c.Value
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewEchoWireService(r.Context(), svcCtx)
		resp, err := l.EchoWire(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusOK, resp)
	}
}
