// Code generated by craftgo. DO NOT EDIT.

package bindings

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/bindings_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/bindings"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Upload a doc with optional-null metadata. The @nullable `meta` body field form-binds as *string (nil when the form value is absent).
//
// NullableForm returns the POST NullableForm handler.
func NullableForm(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		defer func() { _ = r.MultipartForm.RemoveAll() }()
		var req types.NullableFormReq
		if _v := r.FormValue("meta"); _v != "" {
			req.Meta = &_v
		}
		if _v := r.FormValue("tint"); _v != "" {
			_w := types.Color(_v)
			req.Tint = &_w
		}
		if _v := r.FormValue("ref"); _v != "" {
			_w := types.UUID(_v)
			req.Ref = &_w
		}
		if _, header, err := r.FormFile("doc"); err == nil {
			req.Doc = header
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewNullableFormService(r.Context(), svcCtx)
		resp, err := l.NullableForm(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusCreated, resp)
	}
}
