// Code generated by craftgo. DO NOT EDIT.

package bindings

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/bindings_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/bindings"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Upload a user avatar. Demonstrates the path + multipart-form combo - id from /users/{id}/avatar, file via multipart/form-data with @maxSize + @mimeTypes validation.
//
// UploadAvatar returns the POST UploadAvatar handler.
func UploadAvatar(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		defer func() { _ = r.MultipartForm.RemoveAll() }()
		var req types.UploadReq
		req.ID = r.PathValue("id")
		if _v := r.FormValue("note"); _v != "" {
			req.Caption = &_v
		}
		if _, header, err := r.FormFile("avatar_file"); err == nil {
			req.File = header
		}
		if _, header, err := r.FormFile("thumb"); err == nil {
			req.Thumb = header
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewUploadAvatarService(r.Context(), svcCtx)
		resp, err := l.UploadAvatar(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusCreated, resp)
	}
}
