// Code generated by craftgo. DO NOT EDIT.

package orders

import (
	"github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/customers"
)

// ErrCodeActionDenied is the canonical machine-readable code for ActionDeniedErr.
const ErrCodeActionDenied = "ACTION_DENIED"

// ActionDeniedBody is the wire-shape payload declared at design time for ActionDeniedErr.
// User code instantiates this struct and hands it to NewActionDeniedErr; the
// framework wraps it with the type-bound code / message metadata.
type ActionDeniedBody struct {
	Code   *string          `json:"code"`
	Reason SuspensionReason `json:"reason"`
}

// ActionDeniedErr is the typed Forbidden error generated for `ActionDenied`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type ActionDeniedErr struct {
	code    string
	message string
	ActionDeniedBody
}

// NewActionDeniedErr constructs ActionDeniedErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewActionDeniedErr(body ActionDeniedBody) *ActionDeniedErr {
	return &ActionDeniedErr{
		code:             ErrCodeActionDenied,
		message:          "Forbidden",
		ActionDeniedBody: body,
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *ActionDeniedErr) Error() string { return e.message }

// ErrCode returns the machine-readable error code bound to the type.
// The transport layer reads this via an `interface{ ErrCode() string }`
// assertion when assembling the fallback JSON envelope for errors
// whose body would otherwise marshal to `{}`. The accessor is named
// `ErrCode` (not `Code`) so it does not shadow a user-declared
// `code <type>` field promoted from the embedded body struct.
func (e *ActionDeniedErr) ErrCode() string { return e.code }

// HTTPStatus returns the HTTP status code associated with the Forbidden category.
func (e *ActionDeniedErr) HTTPStatus() int { return 403 }

// ErrCodeOrderNotFound is the canonical machine-readable code for OrderNotFoundErr.
const ErrCodeOrderNotFound = "ORDER_NOT_FOUND"

// OrderNotFoundErr is the typed NotFound error generated for `OrderNotFound`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type OrderNotFoundErr struct {
	code    string
	message string
}

// NewOrderNotFoundErr constructs OrderNotFoundErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewOrderNotFoundErr() *OrderNotFoundErr {
	return &OrderNotFoundErr{
		code:    ErrCodeOrderNotFound,
		message: "Not found",
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *OrderNotFoundErr) Error() string { return e.message }

// ErrCode returns the machine-readable error code bound to the type.
// The transport layer reads this via an `interface{ ErrCode() string }`
// assertion when assembling the fallback JSON envelope for errors
// whose body would otherwise marshal to `{}`. The accessor is named
// `ErrCode` (not `Code`) so it does not shadow a user-declared
// `code <type>` field promoted from the embedded body struct.
func (e *OrderNotFoundErr) ErrCode() string { return e.code }

// HTTPStatus returns the HTTP status code associated with the NotFound category.
func (e *OrderNotFoundErr) HTTPStatus() int { return 404 }

// ErrCodePaymentFailed is the canonical machine-readable code for PaymentFailedErr.
const ErrCodePaymentFailed = "PAYMENT_FAILED"

// PaymentFailedBody is the wire-shape payload declared at design time for PaymentFailedErr.
// User code instantiates this struct and hands it to NewPaymentFailedErr; the
// framework wraps it with the type-bound code / message metadata.
type PaymentFailedBody struct {
	Code      *string               `json:"code"`
	Method    PaymentMethod         `json:"method"`
	ChargedBy customers.CustomerRef `json:"chargedBy"`
}

// PaymentFailedErr is the typed Conflict error generated for `PaymentFailed`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type PaymentFailedErr struct {
	code    string
	message string
	PaymentFailedBody
}

// NewPaymentFailedErr constructs PaymentFailedErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewPaymentFailedErr(body PaymentFailedBody) *PaymentFailedErr {
	return &PaymentFailedErr{
		code:              ErrCodePaymentFailed,
		message:           "Conflict",
		PaymentFailedBody: body,
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *PaymentFailedErr) Error() string { return e.message }

// ErrCode returns the machine-readable error code bound to the type.
// The transport layer reads this via an `interface{ ErrCode() string }`
// assertion when assembling the fallback JSON envelope for errors
// whose body would otherwise marshal to `{}`. The accessor is named
// `ErrCode` (not `Code`) so it does not shadow a user-declared
// `code <type>` field promoted from the embedded body struct.
func (e *PaymentFailedErr) ErrCode() string { return e.code }

// HTTPStatus returns the HTTP status code associated with the Conflict category.
func (e *PaymentFailedErr) HTTPStatus() int { return 409 }
