// Code generated by craftgo. DO NOT EDIT.

package orders

import (
	"encoding/json"
	"github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/customers"
)

// ErrCodeActionDenied is the canonical machine-readable code for ActionDeniedErr.
const ErrCodeActionDenied = "ACTION_DENIED"

// ActionDeniedBody is the wire-shape payload declared at design time for ActionDeniedErr.
// User code instantiates this struct and hands it to NewActionDeniedErr.
type ActionDeniedBody struct {
	Code   *string          `json:"code,omitempty"`
	Reason SuspensionReason `json:"reason"`
}

// ActionDeniedErr is the typed Forbidden error generated for `ActionDenied`.
type ActionDeniedErr struct {
	ActionDeniedBody
}

// NewActionDeniedErr constructs ActionDeniedErr.
func NewActionDeniedErr(body ActionDeniedBody) *ActionDeniedErr {
	return &ActionDeniedErr{ActionDeniedBody: body}
}

// Error returns the Forbidden category's default message.
func (e *ActionDeniedErr) Error() string { return "Forbidden" }

// ErrCode returns ErrCodeActionDenied. It is named so that it does not shadow a
// `code` field of the body; rpc.Error puts it on the gRPC status.
func (e *ActionDeniedErr) ErrCode() string { return ErrCodeActionDenied }

// HTTPStatus returns the HTTP status code associated with the Forbidden
// category. server.WriteError answers with it, and rpc.Error maps it onto
// the matching gRPC status code.
func (e *ActionDeniedErr) HTTPStatus() int { return 403 }

// MarshalJSON encodes the body alone.
func (e *ActionDeniedErr) MarshalJSON() ([]byte, error) { return json.Marshal(e.ActionDeniedBody) }

// ErrCodeOrderNotFound is the canonical machine-readable code for OrderNotFoundErr.
const ErrCodeOrderNotFound = "ORDER_NOT_FOUND"

// OrderNotFoundErr is the typed NotFound error generated for `OrderNotFound`.
type OrderNotFoundErr struct{}

// NewOrderNotFoundErr constructs OrderNotFoundErr.
func NewOrderNotFoundErr() *OrderNotFoundErr {
	return &OrderNotFoundErr{}
}

// Error returns the NotFound category's default message.
func (e *OrderNotFoundErr) Error() string { return "Not found" }

// ErrCode returns ErrCodeOrderNotFound. It is named so that it does not shadow a
// `code` field of the body; rpc.Error puts it on the gRPC status.
func (e *OrderNotFoundErr) ErrCode() string { return ErrCodeOrderNotFound }

// HTTPStatus returns the HTTP status code associated with the NotFound
// category. server.WriteError answers with it, and rpc.Error maps it onto
// the matching gRPC status code.
func (e *OrderNotFoundErr) HTTPStatus() int { return 404 }

// MarshalJSON encodes the {"code", "message"} envelope.
func (e *OrderNotFoundErr) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]string{"code": ErrCodeOrderNotFound, "message": e.Error()})
}

// ErrCodePaymentFailed is the canonical machine-readable code for PaymentFailedErr.
const ErrCodePaymentFailed = "PAYMENT_FAILED"

// PaymentFailedBody is the wire-shape payload declared at design time for PaymentFailedErr.
// User code instantiates this struct and hands it to NewPaymentFailedErr.
type PaymentFailedBody struct {
	Code      *string               `json:"code,omitempty"`
	Method    PaymentMethod         `json:"method"`
	ChargedBy customers.CustomerRef `json:"chargedBy"`
}

// PaymentFailedErr is the typed Conflict error generated for `PaymentFailed`.
type PaymentFailedErr struct {
	PaymentFailedBody
}

// NewPaymentFailedErr constructs PaymentFailedErr.
func NewPaymentFailedErr(body PaymentFailedBody) *PaymentFailedErr {
	return &PaymentFailedErr{PaymentFailedBody: body}
}

// Error returns the Conflict category's default message.
func (e *PaymentFailedErr) Error() string { return "Conflict" }

// ErrCode returns ErrCodePaymentFailed. It is named so that it does not shadow a
// `code` field of the body; rpc.Error puts it on the gRPC status.
func (e *PaymentFailedErr) ErrCode() string { return ErrCodePaymentFailed }

// HTTPStatus returns the HTTP status code associated with the Conflict
// category. server.WriteError answers with it, and rpc.Error maps it onto
// the matching gRPC status code.
func (e *PaymentFailedErr) HTTPStatus() int { return 409 }

// MarshalJSON encodes the body alone.
func (e *PaymentFailedErr) MarshalJSON() ([]byte, error) { return json.Marshal(e.PaymentFailedBody) }
