// Code generated by craftgo. DO NOT EDIT.

package orders

// FillEmpty sets each required list, map or bytes value below v that is nil to an empty one,
// so v encodes as [] or {} there; depth counts the values entered to reach v.
func (v *CreateOrderReq) FillEmpty(depth int) {
	if depth > fillDepth {
		return
	}
	emptySlice(&v.Items)
}

// FillEmpty sets each required list, map or bytes value below v that is nil to an empty one,
// so v encodes as [] or {} there; depth counts the values entered to reach v.
func (v *Order) FillEmpty(depth int) {
	if depth > fillDepth {
		return
	}
	emptySlice(&v.Items)
	emptySlice(&v.Tags)
	emptySlice(&v.Grid)
	for i0 := range v.Grid {
		emptySlice(&v.Grid[i0])
	}
}

// fillDepth is how deep FillEmpty enters nested values: a value cycle has no end.
const fillDepth = 1000

// emptySlice sets *s to an empty slice when it is nil.
func emptySlice[S ~[]E, E any](s *S) {
	if *s == nil {
		*s = S{}
	}
}
