// Package svccontext is the shared dependency container for the complex
// fixture. It seeds an in-memory profile store keyed by id.
package svccontext

import "sync"

// ServiceContext holds an in-memory store for the complex e2e scenario.
// The embedded `Middlewares` struct is generated by craftgo from the
// DSL `middleware Name` declarations; main.go assigns each field, and
// the generated routes layer reaches them via the embedding.
type ServiceContext struct {
	Middlewares
	mu       sync.Mutex
	Profiles map[string]any
	NextID   int
}

// NewServiceContext returns a fresh, empty ServiceContext.
func NewServiceContext() *ServiceContext {
	return &ServiceContext{Profiles: map[string]any{}}
}

// Lock / Unlock expose the mutex so logic files can keep request
// mutations atomic.
func (s *ServiceContext) Lock()   { s.mu.Lock() }
func (s *ServiceContext) Unlock() { s.mu.Unlock() }
