// Code generated by craftgo. DO NOT EDIT.

package rawmodes

import (
	"fmt"
	"unicode/utf8"
)

// Validate checks every field-level constraint declared on PtReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *PtReq) Validate() error {
	if l := utf8.RuneCountInString(v.ID); l < 1 || l > 32 {
		return fmt.Errorf("id: length out of range [1, 32]")
	}
	return nil
}

// Validate checks every field-level constraint declared on PtResp.
// Returns the first violation; nil when the value satisfies the contract.
func (v *PtResp) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on RqFileReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *RqFileReq) Validate() error {
	if v.Doc == nil {
		return fmt.Errorf("doc: required")
	}
	return nil
}

// Validate checks every field-level constraint declared on RqItem.
// Returns the first violation; nil when the value satisfies the contract.
func (v *RqItem) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on RqResp.
// Returns the first violation; nil when the value satisfies the contract.
func (v *RqResp) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on RrReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *RrReq) Validate() error {
	if l := utf8.RuneCountInString(v.ID); l < 1 || l > 32 {
		return fmt.Errorf("id: length out of range [1, 32]")
	}
	if utf8.RuneCountInString(v.Name) < 2 {
		return fmt.Errorf("name: length less than 2")
	}
	return nil
}

// Validate checks every field-level constraint declared on RrResp.
// Returns the first violation; nil when the value satisfies the contract.
func (v *RrResp) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on RrUploadReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *RrUploadReq) Validate() error {
	if utf8.RuneCountInString(v.Note) < 1 {
		return fmt.Errorf("note: length less than 1")
	}
	if v.Doc == nil {
		return fmt.Errorf("doc: required")
	}
	return nil
}
