// Code generated by craftgo. DO NOT EDIT.

package shared

// Email is the cross-package email shape - capped at the RFC-5321
// maximum and gated by the @format(email) validator. Referenced as
// `shared.Email` from anywhere a user-facing email address appears.
type Email string

// ID is the cross-package opaque identifier shape. Referenced as
// `shared.ID` from `services/` so every entity-id field inherits
// the same 1..64 char cap without each consumer repeating the
// validator stack.
type ID string

// Audit captures the create/update bookkeeping every persistent
// entity carries. Embedded into top-level types via the implicit
// mixin form so the fields land at the wire root without an extra
// nesting level.
type Audit struct {
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	CreatedBy string `json:"createdBy"`
}

// AuditTrail is the canonical "who-did-what-when" mixin shape.
// Declared as a regular type so other decls can embed it (the
// language has no separate `mixin` keyword - any type member that
// is a bare ident becomes a mixin reference). It is embedded both
// into regular types and into an error body (AccessRevoked below),
// flattening its `actor` / `at` fields into the host schema.
type AuditTrail struct {
	Actor string `json:"actor"`
	At    string `json:"at"`
}

// Money is the canonical currency-aware amount: an integer minor-
// unit value paired with the ISO-4217 currency code. `currency` is
// fixed at exactly three characters; `amount` is non-negative so
// the wire type cannot carry a debit (refunds are represented by a
// separate flow, not by a negative Money).
type Money struct {
	Amount   int    `json:"amount"`
	Currency string `json:"currency"`
}

// Pagination is the canonical cursor/limit envelope every list
// endpoint embeds. `limit` carries the standard 1..100 cap with a
// pre-fill of 20 when the caller omits it; `cursor` is the opaque
// continuation token returned by the previous page; `total` is the
// optional total-count summary (omitted when the upstream store can
// not cheaply compute it).
//
// Consumers embed this DTO via the implicit mixin form
// (`type ListUsersReq { shared.Pagination  query string? }`) so the
// pagination contract stays identical across services without copy-
// paste.
type Pagination struct {
	Limit  *int    `json:"limit,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
	Total  *int    `json:"total,omitempty"`
}
