// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package userservice

import (
	"context"

	shared "github.com/dropship-dev/craftgo/example/internal/types/shared"
	types "github.com/dropship-dev/craftgo/example/internal/types/users"

	"github.com/dropship-dev/craftgo/example/svccontext"
	"github.com/dropship-dev/craftgo/pkg/log"
)

// AddContactLogic carries the per-request state for the
// AddContact endpoint of UserService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type AddContactLogic struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewAddContactLogic constructs a fresh logic instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewAddContactLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *AddContactLogic {
	return &AddContactLogic{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// AddContact is the business-logic entry point. Replace the
// TODO with the real implementation.
func (l *AddContactLogic) AddContact(req *types.AddContactReq) (*shared.OkResp, error) {
	// TODO: implement
	return nil, nil
}
