// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package userservice

import (
	"context"

	shared "github.com/dropship-dev/craftgo/example/internal/types/shared"
	types "github.com/dropship-dev/craftgo/example/internal/types/users"

	"github.com/dropship-dev/craftgo/example/svccontext"
	"github.com/dropship-dev/craftgo/pkg/log"
)

// RestoreUserLogic carries the per-request state for the
// RestoreUser endpoint of UserService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type RestoreUserLogic struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewRestoreUserLogic constructs a fresh logic instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewRestoreUserLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *RestoreUserLogic {
	return &RestoreUserLogic{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// RestoreUser is the inverse of SuspendUser. The same chain +
// scope rules apply. Note the request type is reused from
// service.craftgo's GetUserReq — extend blocks share the
// package's full type table.
// RestoreUser is the business-logic entry point. Replace the
// TODO with the real implementation.
func (l *RestoreUserLogic) RestoreUser(req *types.GetUserReq) (*shared.OkResp, error) {
	// TODO: implement
	return nil, nil
}
