// Code generated by craftgo. DO NOT EDIT.

package xshared

import (
	"encoding/json"
)

// ErrCodeXLost is the canonical machine-readable code for XLostErr.
const ErrCodeXLost = "X_LOST"

// XLostBody is the body of XLostErr.
type XLostBody struct {
	Key string `json:"key"`
}

// XLost shares its name with xrefs.XLost, so the merged OpenAPI document
// names this one XsharedXLostErr.
//
// XLostErr is the NotFound error XLost.
type XLostErr struct {
	XLostBody
}

// NewXLostErr constructs XLostErr.
func NewXLostErr(body XLostBody) *XLostErr {
	return &XLostErr{XLostBody: body}
}

// Error returns the NotFound category's default message.
func (e *XLostErr) Error() string { return "Not found" }

// ErrCode returns ErrCodeXLost.
func (e *XLostErr) ErrCode() string { return ErrCodeXLost }

// HTTPStatus returns the NotFound status.
func (e *XLostErr) HTTPStatus() int { return 404 }

// MarshalJSON encodes the body alone.
func (e *XLostErr) MarshalJSON() ([]byte, error) { return json.Marshal(e.XLostBody) }

// ErrCodeXNotFound is the canonical machine-readable code for XNotFoundErr.
const ErrCodeXNotFound = "X_NOT_FOUND"

// XNotFoundBody is the body of XNotFoundErr.
type XNotFoundBody struct {
	Resource string `json:"resource"`
	ID       string `json:"id"`
}

// XNotFound is a cross-package error. Methods on xrefs' service
// declare `@errors(xshared.XNotFound)` so the OpenAPI responses list
// resolves the error schema through the project ErrorTable.
//
// XNotFoundErr is the NotFound error XNotFound.
type XNotFoundErr struct {
	XNotFoundBody
}

// NewXNotFoundErr constructs XNotFoundErr.
func NewXNotFoundErr(body XNotFoundBody) *XNotFoundErr {
	return &XNotFoundErr{XNotFoundBody: body}
}

// Error returns the NotFound category's default message.
func (e *XNotFoundErr) Error() string { return "Not found" }

// ErrCode returns ErrCodeXNotFound.
func (e *XNotFoundErr) ErrCode() string { return ErrCodeXNotFound }

// HTTPStatus returns the NotFound status.
func (e *XNotFoundErr) HTTPStatus() int { return 404 }

// MarshalJSON encodes the body alone.
func (e *XNotFoundErr) MarshalJSON() ([]byte, error) { return json.Marshal(e.XNotFoundBody) }
