// Code generated by craftgo. DO NOT EDIT.

package rawmodes

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/raw/v1"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Inherits @rawResponse from the extend header; no contract.
//
// ExtRaw returns the GET ExtRaw handler.
func ExtRaw(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewExtRawService(r.Context(), svcCtx)
		if err := l.ExtRaw(w, r); err != nil {
			server.WriteError(w, r, err)
			return
		}
	}
}
