// Code generated by craftgo. DO NOT EDIT.

package userservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/example/internal/service/user-service"
	types "github.com/craftgodotdev/craftgo/example/internal/types/users"
	"github.com/craftgodotdev/craftgo/example/svccontext"
)

// RestoreUser is the inverse of SuspendUser. The same chain +
// scope rules apply. Note the request type is reused from
// service.craftgo's GetUserReq — extend blocks share the
// package's full type table.
// RestoreUser returns the http.HandlerFunc for the
// POST RestoreUser endpoint.
func RestoreUser(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetUserReq
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewRestoreUserService(r.Context(), svcCtx)
		resp, err := l.RestoreUser(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
