// Code generated by craftgo. DO NOT EDIT.

package userservice

import (
	"encoding/json"
	"github.com/dropship-dev/craftgo/pkg/server"
	"net/http"

	service "github.com/dropship-dev/craftgo/example/internal/service/user-service"
	types "github.com/dropship-dev/craftgo/example/internal/types/users"
	"github.com/dropship-dev/craftgo/example/svccontext"
)

// UpdateUser returns the http.HandlerFunc for the
// PATCH UpdateUser endpoint.
func UpdateUser(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.UpdateUserReq
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewUpdateUserService(r.Context(), svcCtx)
		resp, err := l.UpdateUser(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
