// Code generated by craftgo. DO NOT EDIT.

package collections

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/collections"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/collections"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// MultiDim drives a 2D array of scalars through the request
// body so the doubly-nested loop emits on the wire boundary.
// MultiDim returns the http.HandlerFunc for the
// POST MultiDim endpoint.
func MultiDim(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.Arr_Tag2D
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewMultiDimService(r.Context(), svcCtx)
		resp, err := l.MultiDim(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
