// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package numbers

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/numbers"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// AddUnsignedService runs NumbersService.AddUnsigned for one request.
type AddUnsignedService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewAddUnsignedService binds AddUnsignedService to ctx; its Logger carries ctx's trace ids.
func NewAddUnsignedService(ctx context.Context, svcCtx *svccontext.ServiceContext) *AddUnsignedService {
	return &AddUnsignedService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// AddUnsigned implements NumbersService.AddUnsigned.
func (l *AddUnsignedService) AddUnsigned(req *types.UnsignedReq) (*types.UnsignedReq, error) {
	// TODO: implement
	return nil, nil
}
