// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package numbers

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/numbers"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// EchoMultipleOfService runs NumbersService.EchoMultipleOf for one request.
type EchoMultipleOfService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewEchoMultipleOfService binds EchoMultipleOfService to ctx; its Logger carries ctx's trace ids.
func NewEchoMultipleOfService(ctx context.Context, svcCtx *svccontext.ServiceContext) *EchoMultipleOfService {
	return &EchoMultipleOfService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// EchoMultipleOf implements NumbersService.EchoMultipleOf.
func (l *EchoMultipleOfService) EchoMultipleOf(req *types.NumberMultipleOf) (*types.NumberMultipleOf, error) {
	// TODO: implement
	return nil, nil
}
