// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package ordersservice

import (
	"context"

	types "github.com/dropship-dev/craftgo/example/internal/types/design"

	"github.com/dropship-dev/craftgo/example/svccontext"
)

// GetOrderLogic carries the per-request state for the
// GetOrder endpoint of OrdersService.
type GetOrderLogic struct {
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewGetOrderLogic constructs a fresh logic instance bound to ctx.
func NewGetOrderLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *GetOrderLogic {
	return &GetOrderLogic{ctx: ctx, svcCtx: svcCtx}
}

// GetOrder is path-bound. @errors documents what the OpenAPI doc
// should advertise; the handler's writeError helper does the
// actual mapping.
// GetOrder is the business-logic entry point. Replace the
// TODO with the real implementation.
func (l *GetOrderLogic) GetOrder(req *types.GetOrderReq) (*types.Order, error) {
	l.svcCtx.Lock()
	defer l.svcCtx.Unlock()
	o, ok := l.svcCtx.Orders[req.ID]
	if !ok {
		return nil, types.NewOrderNotFoundErr()
	}
	out := toWireOrder(o)
	return &out, nil
}
