// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package ordersservice

import (
	"context"

	types "github.com/dropship-dev/craftgo/example/internal/types/design"

	"github.com/dropship-dev/craftgo/example/svccontext"
	"github.com/dropship-dev/craftgo/pkg/log"
)

// ListOrdersLogic carries the per-request state for the
// ListOrders endpoint of OrdersService.
type ListOrdersLogic struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewListOrdersLogic constructs a fresh logic instance bound to ctx.
func NewListOrdersLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *ListOrdersLogic {
	return &ListOrdersLogic{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// ListOrders returns every order. Public for demo simplicity; a
// real shop would gate this with @middlewares(AuthRequired).
// ListOrders is the business-logic entry point. Replace the
// TODO with the real implementation.
func (l *ListOrdersLogic) ListOrders() (*types.OrderList, error) {
	l.svcCtx.Lock()
	defer l.svcCtx.Unlock()
	items := make([]types.Order, 0, len(l.svcCtx.Orders))
	for _, o := range l.svcCtx.Orders {
		items = append(items, toWireOrder(o))
	}
	return &types.OrderList{P: types.Page[types.Order]{Items: items, Total: len(items)}}, nil
}

// toWireOrder maps the in-memory Order to the wire-level type. Defined
// once and reused across get/list/cancel logic.
func toWireOrder(o svccontext.Order) types.Order {
	items := make([]types.OrderItem, 0, len(o.Lines))
	for _, ln := range o.Lines {
		items = append(items, types.OrderItem{BookID: ln.BookID, Quantity: ln.Quantity, UnitPrice: ln.UnitPrice})
	}
	return types.Order{
		ID:            o.ID,
		CustomerEmail: o.CustomerEmail,
		Items:         items,
		TotalCents:    o.TotalCents,
		Status:        o.Status,
	}
}
