// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package scalars

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/scalars"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ListOrdersService runs ScalarsService.ListOrders for one request.
type ListOrdersService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewListOrdersService binds ListOrdersService to ctx; its Logger carries ctx's trace ids.
func NewListOrdersService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ListOrdersService {
	return &ListOrdersService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// List orders with cursor pagination. Demonstrates a generic-instance response (Page<Order>) - codegen emits the parametric struct and substitutes T=Order at the concrete site.
//
// ListOrders implements ScalarsService.ListOrders.
func (l *ListOrdersService) ListOrders(req *types.ListOrdersReq) (*types.OrderPage, error) {
	// TODO: implement
	return nil, nil
}
