// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package scalars

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/scalars"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ListKeyedService runs ScalarsService.ListKeyed for one request.
type ListKeyedService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewListKeyedService binds ListKeyedService to ctx; its Logger carries ctx's trace ids.
func NewListKeyedService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ListKeyedService {
	return &ListKeyedService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// List by key. A generic mixin over a nested mixin binds each query field with the type its own level declares.
//
// ListKeyed implements ScalarsService.ListKeyed.
func (l *ListKeyedService) ListKeyed(req *types.ListKeyedReq) (*types.OrderPage, error) {
	// TODO: implement
	return nil, nil
}
