// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package scalars

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/scalars"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// LookupOrderService runs ScalarsService.LookupOrder for one request.
type LookupOrderService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewLookupOrderService binds LookupOrderService to ctx; its Logger carries ctx's trace ids.
func NewLookupOrderService(ctx context.Context, svcCtx *svccontext.ServiceContext) *LookupOrderService {
	return &LookupOrderService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Look an order up by id. The request is a generic instance, Lookup<Priority>, bound from the path and the query string.
//
// LookupOrder implements ScalarsService.LookupOrder.
func (l *LookupOrderService) LookupOrder(req *types.Lookup[types.Priority]) (*types.Order, error) {
	// TODO: implement
	return nil, nil
}
