// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package scalars

import (
	"context"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/scalars"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// PageKeyedService carries the per-request state for the
// PageKeyed endpoint of ScalarsService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type PageKeyedService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewPageKeyedService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewPageKeyedService(ctx context.Context, svcCtx *svccontext.ServiceContext) *PageKeyedService {
	return &PageKeyedService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// PageKeyed is the service entry point. Replace the
// TODO with the real implementation.
func (l *PageKeyedService) PageKeyed() (*types.KeyedPage[types.Priority], error) {
	// TODO: implement
	return nil, nil
}
