// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package scalars

import (
	"context"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/scalars"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// PutKeyedService carries the per-request state for the
// PutKeyed endpoint of ScalarsService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type PutKeyedService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewPutKeyedService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewPutKeyedService(ctx context.Context, svcCtx *svccontext.ServiceContext) *PutKeyedService {
	return &PutKeyedService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// PutKeyed is the service entry point. Replace the
// TODO with the real implementation.
func (l *PutKeyedService) PutKeyed(req *types.KeyedPut[types.Priority]) (*types.Order, error) {
	// TODO: implement
	return nil, nil
}
