// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package middleware

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"
)

// NewRequestIDMiddleware returns the RequestID middleware, which ServiceContext's RequestID field holds.
func NewRequestIDMiddleware() server.Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// TODO: implement
			next.ServeHTTP(w, r)
		})
	}
}
