// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package middleware

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"
)

// NewRequestIDMiddleware constructs the RequestID middleware.
//
// craftgo never overwrites this file after the first generation, so
// add wiring (token store, logger, rate-limit budget, ...) or change
// the param types freely.
//
// Wire it from main.go:
//
//	svc := svccontext.NewServiceContext()
//	svc.RequestID = middleware.NewRequestIDMiddleware(/* args */)
//	routes.RegisterRoutes(srv, svc)
func NewRequestIDMiddleware() server.Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// TODO: implement
			next.ServeHTTP(w, r)
		})
	}
}
