// Scaffold generated by craftgo. Safe to edit; will not be overwritten.
//
// Boots the runtime server: wires every middleware field, attaches the
// runtime globals (RequestID + AccessLog), and calls the umbrella
// routes.RegisterAll. Replace the placeholder middleware constructor
// arguments with real values before running in production.

package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/dropship-dev/craftgo/pkg/server"

	"github.com/dropship-dev/craftgo/example/internal/routes"
	"github.com/dropship-dev/craftgo/example/svccontext"
)

func main() {
	svc := svccontext.NewServiceContext()

	// Build the Server and attach runtime globals via Use. Add
	// otel/metrics/CORS here too — every Use middleware wraps every
	// request and is safe to leave permanently because the package's
	// own gate keeps it cheap when disabled.
	srv := server.New(svc)
	srv.Use(server.RequestID())
	srv.Use(server.AccessLog(srv.Logger()))

	// One call wires every service. The umbrella RegisterAll is
	// generated from the DSL service set on every `craftgo gen`.
	routes.RegisterAll(srv, svc)

	go func() {
		log.Println("listening on :8080")
		if err := srv.Start(":8080"); err != nil && err != http.ErrServerClosed {
			log.Fatal(err)
		}
	}()

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGINT, syscall.SIGTERM)
	<-stop

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_ = srv.Stop(ctx)
}
