// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package hidden

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/hidden"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ReadService runs HiddenNotes.Read for one request.
type ReadService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewReadService binds ReadService to ctx; its Logger carries ctx's trace ids.
func NewReadService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ReadService {
	return &ReadService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Answers a Note; documented.
//
// Read implements HiddenNotes.Read.
func (l *ReadService) Read() (*types.Note, error) {
	return &types.Note{Text: "read"}, nil
}
