// Code generated by craftgo. DO NOT EDIT.

package stream

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/raw/internal/service/stream_service"
	types "github.com/craftgodotdev/craftgo/example/raw/internal/types/stream"
	"github.com/craftgodotdev/craftgo/example/raw/svccontext"
)

// Stream a file download: the request is bound and validated, logic serves the body with http.ServeContent.
//
// Download returns the GET Download handler.
func Download(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.DownloadReq
		req.File = r.PathValue("file")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewDownloadService(r.Context(), svcCtx)
		if err := l.Download(w, r, &req); err != nil {
			server.WriteError(w, r, err)
			return
		}
	}
}
