// Code generated by craftgo. DO NOT EDIT.

package stream

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/raw/internal/service/stream_service"
	types "github.com/craftgodotdev/craftgo/example/raw/internal/types/stream"
	"github.com/craftgodotdev/craftgo/example/raw/svccontext"
)

// Snapshot returns the http.HandlerFunc for the
// GET Snapshot raw-response endpoint. The handler binds and
// validates the request, then hands the http.ResponseWriter and
// *http.Request to logic, which writes the response directly.
func Snapshot(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.SnapshotReq
		_q := r.URL.Query()
		if _v := _q.Get("region"); _v != "" {
			req.Region = &_v
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewSnapshotService(r.Context(), svcCtx)
		if err := l.Snapshot(w, r, &req); err != nil {
			server.WriteError(w, r, err)
			return
		}
	}
}
