// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package taskservice

import (
	"context"

	types "github.com/dropship-dev/craftgo/example/internal/types/tasks"

	"github.com/dropship-dev/craftgo/example/svccontext"
	"github.com/dropship-dev/craftgo/pkg/log"
)

// ListTasksLogic carries the per-request state for the
// ListTasks endpoint of TaskService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type ListTasksLogic struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewListTasksLogic constructs a fresh logic instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewListTasksLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *ListTasksLogic {
	return &ListTasksLogic{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// ListTasks is the business-logic entry point. Replace the
// TODO with the real implementation.
func (l *ListTasksLogic) ListTasks(req *types.ListTasksReq) (*types.TaskList, error) {
	// TODO: implement
	return nil, nil
}
