version: "2"
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - gocyclo
    - dupl
    - unparam
    - copyloopvar
  settings:
    gocyclo:
      min-complexity: 30
    dupl:
      threshold: 100
  exclusions:
    paths:
      - testdata
formatters:
  enable:
    - gofmt
