// Scaffold generated by craftgo. Safe to edit; will not be overwritten.
//
// Package config is the project's runtime configuration loader. main.go
// reads `config/config.yaml` at boot, fills in framework defaults, and
// hands the resulting *Config to svccontext so every
// service/middleware/logic function reads the same source of truth.
//
// Layout convention:
//
//	config/
//	├── config.go             - this file (Go struct + loader)
//	├── config.yaml           - local dev values (gitignore in real
//	│                           projects; commit only the example)
//	└── example.config.yaml   - committed reference with every key
//	                            documented; copy → config.yaml on a
//	                            new checkout, then edit
//
// Add new fields by extending the struct, optional yaml tag + default
// in [applyDefaults]. Per-environment overrides belong in
// `config.yaml` itself (one file per env, mounted by the deployer).
package config

import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/craftgodotdev/craftgo/pkg/telemetry"
)

// Config is the in-memory shape of `config/config.yaml`. Each section
// maps to one runtime concern - a listener, distributed tracing,
// metrics - so feature owners can extend their own block without
// stepping on each other.
//
// The telemetry block is inlined so `serviceName`, `otel:` and `metrics:`
// sit at the top level of config.yaml. Reusing the library type lets
// main.go pass `cfg.Config` straight to telemetry.Init.
type Config struct {
	GRPC             GRPCConfig `yaml:"grpc"`
	Logging          LogConfig  `yaml:"logging"`
	telemetry.Config `yaml:",inline"`
}

// LogConfig controls the process-wide logger. Only the minimum level is
// modelled here; format (JSON vs console) and output destination are
// wired in main.go, where you can swap log.New / log.NewConsole or
// install your own logger via srv.SetLogger.
type LogConfig struct {
	// Level is the minimum level emitted: "debug", "info" (default),
	// "warn", or "error". main.go feeds it to log.SetLevel, which retunes
	// the server and the generated logic layer together. An unrecognised
	// value leaves the info default in place.
	Level string `yaml:"level"`
}

// GRPCConfig configures the gRPC listener. The generated server layer
// and the interceptors main.go installs read nothing else.
type GRPCConfig struct {
	// Addr is the bind address for the gRPC server, e.g. ":9000".
	Addr string `yaml:"addr"`

	// HandlerTimeout is the default deadline for unary RPCs, carried on
	// the handler context; a shorter client deadline still wins. Streams
	// are not bounded. Zero = no default.
	HandlerTimeout time.Duration `yaml:"handlerTimeout"`

	// Reflection serves the gRPC reflection service so grpcurl and grpcui
	// can call the server without the .proto files. Leave it off on a
	// listener exposed to the public internet.
	Reflection bool `yaml:"reflection"`
}

// The OTel + Metrics block shapes live in `pkg/telemetry` (look there
// for field-by-field docs). The aliases below let `config.yaml` and
// call sites read like local types without the project re-defining
// the schema.
//
// Aliases are kept exported so an IDE goto-definition lands on the
// library doc strings instead of an opaque indirection.
type (
	// TelemetryConfig is the shared `serviceName` plus the two per-signal
	// sections. See [telemetry.Config] for field detail.
	TelemetryConfig = telemetry.Config

	// OTelConfig drives the tracer. The HTTP wrapper emits BOTH signals,
	// so this block gates only where spans go - metrics keep flowing
	// while `metrics.enabled` is true.
	OTelConfig = telemetry.OTelConfig

	// MetricsConfig drives the meter + admin scrape listener. It chooses
	// only where the metrics flow OUT.
	MetricsConfig = telemetry.MetricsConfig
)

// Path returns the conventional config-file location. Override by
// passing a different path to [Load] directly.
func Path() string {
	return "config/config.yaml"
}

// Load reads cfgPath (when non-empty) and fills in framework defaults
// for any blank fields. The YAML file is the single source of truth;
// pass an empty cfgPath to boot purely on defaults.
func Load(cfgPath string) (*Config, error) {
	cfg := &Config{}
	if cfgPath != "" {
		data, err := os.ReadFile(cfgPath)
		if err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("read %s: %w", cfgPath, err)
		}
		if err == nil {
			if err := yaml.Unmarshal(data, cfg); err != nil {
				return nil, fmt.Errorf("parse %s: %w", cfgPath, err)
			}
		}
	}
	cfg.applyDefaults()
	return cfg, nil
}

// applyDefaults fills any blank field with the framework's recommended
// value. Mirrors the example.config.yaml that ships with `craftgo init`
// so a project that deletes config.yaml and runs purely on defaults
// behaves identically to one that copied the example.
func (c *Config) applyDefaults() {
	if c.GRPC.Addr == "" {
		c.GRPC.Addr = ":9000"
	}

	if c.Logging.Level == "" {
		c.Logging.Level = "info"
	}

	if c.ServiceName == "" {
		c.ServiceName = "grpc"
	}
	if c.OTel.Exporter == "" {
		c.OTel.Exporter = "none"
	}

	if c.Metrics.Exporter == "" {
		c.Metrics.Exporter = "prometheus"
	}
	if c.Metrics.AdminAddr == "" {
		c.Metrics.AdminAddr = ":9090"
	}
	if c.Metrics.Path == "" {
		c.Metrics.Path = "/metrics"
	}
}
