// Code generated by craftgo. DO NOT EDIT.

package wiring

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/rpc"

	greetergrpc "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/grpc/greeter"
	grpcpb "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/pb/grpc"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RegisterGRPC attaches the design to srv: every gRPC service the protos
// declare. The body varies with the design; this signature does not, so
// main.go - written once - never needs editing.
//
// The returned shutdown runs beside srv.Stop.
func RegisterGRPC(ctx context.Context, srv *rpc.Server, svcCtx *svccontext.ServiceContext) (func(context.Context) error, error) {
	grpcpb.RegisterGreeterServer(srv, greetergrpc.NewServer(svcCtx))
	return func(context.Context) error { return nil }, nil
}
