// Code generated by craftgo. DO NOT EDIT.

package wiring

import (
	"context"
	"errors"

	"github.com/craftgodotdev/craftgo/pkg/server"

	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/routes"

	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Register attaches the design to srv: every HTTP route it declares. The
// body varies with the design; this signature does not, so main.go -
// written once - never needs editing.
//
// The returned shutdown runs beside srv.Stop.
func Register(ctx context.Context, srv *server.Server, svcCtx *svccontext.ServiceContext) (func(context.Context) error, error) {
	routes.RegisterAll(srv, svcCtx)
	// An HTTP middleware the design applies but nothing wired is skipped
	// by the chain rather than called, so the guarantee would be missing
	// with nothing to notice. Fail here instead, naming the line to add.
	if svcCtx.Audit == nil {
		return nil, errors.New("wiring: the design declares `middleware Audit` and AccountService.Logout runs it, but svcCtx.Audit is nil - assign `svc.Audit = middleware.NewAuditMiddleware(/* args */)` where you build the ServiceContext")
	}
	if svcCtx.AuthRequired == nil {
		return nil, errors.New("wiring: the design declares `middleware AuthRequired` and AccountService.Me runs it, but svcCtx.AuthRequired is nil - assign `svc.AuthRequired = middleware.NewAuthRequiredMiddleware(/* args */)` where you build the ServiceContext")
	}
	if svcCtx.BasicAuth == nil {
		return nil, errors.New("wiring: the design declares `middleware BasicAuth` and AccountService.DeleteAccount runs it, but svcCtx.BasicAuth is nil - assign `svc.BasicAuth = middleware.NewBasicAuthMiddleware(/* args */)` where you build the ServiceContext")
	}
	if svcCtx.ProfileAuth == nil {
		return nil, errors.New("wiring: the design declares `middleware ProfileAuth` and AdminService.DashboardStats runs it, but svcCtx.ProfileAuth is nil - assign `svc.ProfileAuth = middleware.NewProfileAuthMiddleware(/* args */)` where you build the ServiceContext")
	}
	if svcCtx.RateLimit == nil {
		return nil, errors.New("wiring: the design declares `middleware RateLimit` and AccountService.Signup runs it, but svcCtx.RateLimit is nil - assign `svc.RateLimit = middleware.NewRateLimitMiddleware(/* args */)` where you build the ServiceContext")
	}
	if svcCtx.RequestStamp == nil {
		return nil, errors.New("wiring: the design declares `middleware RequestStamp` and AdminService.Snapshot runs it, but svcCtx.RequestStamp is nil - assign `svc.RequestStamp = middleware.NewRequestStampMiddleware(/* args */)` where you build the ServiceContext")
	}
	if svcCtx.Timing == nil {
		return nil, errors.New("wiring: the design declares `middleware Timing` and RawModesService.PtPlain runs it, but svcCtx.Timing is nil - assign `svc.Timing = middleware.NewTimingMiddleware(/* args */)` where you build the ServiceContext")
	}
	return func(context.Context) error { return nil }, nil
}
