// Code generated by craftgo. DO NOT EDIT.

package xrefsservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/complex/internal/service/x-refs-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/complex/internal/types/xrefs"
	xshared "github.com/craftgodotdev/craftgo/tests/e2e/complex/internal/types/xshared"
	"github.com/craftgodotdev/craftgo/tests/e2e/complex/svccontext"
)

// PostDefault returns the http.HandlerFunc for the
// POST PostDefault endpoint.
func PostDefault(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.XEnumDefault
		{
			__d := xshared.XColorRed
			req.Color = &__d
		}
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewPostDefaultService(r.Context(), svcCtx)
		resp, err := l.PostDefault(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
