// Code generated by craftgo. DO NOT EDIT.

package catalogservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/example/ecommerce/internal/service/catalog-service"
	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/catalog"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// GetProduct returns the http.HandlerFunc for the
// GET GetProduct endpoint.
func GetProduct(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetProductReq
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewGetProductService(r.Context(), svcCtx)
		resp, err := l.GetProduct(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
