// Code generated by craftgo. DO NOT EDIT.

package catalogservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/example/ecommerce/internal/service/catalog-service"
	shared "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/shared"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// ListCategories returns the http.HandlerFunc for the
// GET ListCategories endpoint.
func ListCategories(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req shared.Pagination
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewListCategoriesService(r.Context(), svcCtx)
		resp, err := l.ListCategories(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
