// Code generated by craftgo. DO NOT EDIT.

package nested

import (
	"fmt"
	"unicode/utf8"
)

// Validate returns the first constraint v violates, or nil.
func (v *A) Validate() error {
	if v.B != nil {
		if err := v.B.Validate(); err != nil {
			return fmt.Errorf("b: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Address) Validate() error {
	if utf8.RuneCountInString(v.Street) < 1 {
		return fmt.Errorf("street: length less than 1")
	}
	if utf8.RuneCountInString(v.City) < 1 {
		return fmt.Errorf("city: length less than 1")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *AuditedHost) Validate() error {
	if err := v.CreatedAudit.Validate(); err != nil {
		return err
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *B) Validate() error {
	if v.A != nil {
		if err := v.A.Validate(); err != nil {
			return fmt.Errorf("a: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Catalog) Validate() error {
	for _, val0 := range v.Users {
		if err := val0.Validate(); err != nil {
			return fmt.Errorf("users: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *CreatedAudit) Validate() error {
	if utf8.RuneCountInString(v.CreatedAt) < 1 {
		return fmt.Errorf("createdAt: length less than 1")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Cube) Validate() error {
	for i0 := range v.Space {
		for i1 := range v.Space[i0] {
			for i2 := range v.Space[i0][i1] {
				if err := v.Space[i0][i1][i2].Validate(); err != nil {
					return fmt.Errorf("space: %w", err)
				}
			}
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Furniture) Validate() error {
	if utf8.RuneCountInString(v.Name) < 1 {
		return fmt.Errorf("name: length less than 1")
	}
	if v.Weight < 0 {
		return fmt.Errorf("weight: below minimum 0")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *HeaderedResp) Validate() error {
	if err := v.ResponseAudit.Validate(); err != nil {
		return err
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Home) Validate() error {
	for i0 := range v.Rooms {
		if err := v.Rooms[i0].Validate(); err != nil {
			return fmt.Errorf("rooms: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *ListPage) Validate() error {
	for i0 := range v.Items {
		if err := v.Items[i0].Validate(); err != nil {
			return fmt.Errorf("items: %w", err)
		}
	}
	if v.Meta != nil {
		if err := v.Meta.Validate(); err != nil {
			return fmt.Errorf("meta: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Matrix) Validate() error {
	for i0 := range v.Grid {
		for i1 := range v.Grid[i0] {
			if err := v.Grid[i0][i1].Validate(); err != nil {
				return fmt.Errorf("grid: %w", err)
			}
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Node) Validate() error {
	if utf8.RuneCountInString(v.ID) < 1 {
		return fmt.Errorf("id: length less than 1")
	}
	for i0 := range v.Children {
		if err := v.Children[i0].Validate(); err != nil {
			return fmt.Errorf("children: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Order) Validate() error {
	if utf8.RuneCountInString(v.ID) < 1 {
		return fmt.Errorf("id: length less than 1")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Org) Validate() error {
	for i0 := range v.Teams {
		if err := v.Teams[i0].Validate(); err != nil {
			return fmt.Errorf("teams: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Person) Validate() error {
	if err := v.Home.Validate(); err != nil {
		return fmt.Errorf("home: %w", err)
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *RateMeta) Validate() error {
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *RateResp) Validate() error {
	if err := v.RateMeta.Validate(); err != nil {
		return err
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *ResponseAudit) Validate() error {
	if utf8.RuneCountInString(v.CreatedAt) < 1 {
		return fmt.Errorf("createdAt: length less than 1")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Room) Validate() error {
	for i0 := range v.Furniture {
		if err := v.Furniture[i0].Validate(); err != nil {
			return fmt.Errorf("furniture: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Team) Validate() error {
	if len(v.Members) < 1 {
		return fmt.Errorf("members: minItems 1")
	}
	if len(v.Members) > 50 {
		return fmt.Errorf("members: maxItems 50")
	}
	for i0 := range v.Members {
		if err := v.Members[i0].Validate(); err != nil {
			return fmt.Errorf("members: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *User) Validate() error {
	if err := v.Addr.Validate(); err != nil {
		return fmt.Errorf("addr: %w", err)
	}
	if v.Boss != nil {
		if err := v.Boss.Validate(); err != nil {
			return fmt.Errorf("boss: %w", err)
		}
	}
	if v.Name == nil && v.Alias == nil {
		return fmt.Errorf("requiresOneOf [name alias] - at least one must be set")
	}
	return nil
}
