// Code generated by craftgo. DO NOT EDIT.

package regressionbatch3

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/regression-batch3"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/regression"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// EchoResp returns the http.HandlerFunc for the
// POST EchoResp endpoint.
func EchoResp(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.Rg3Audit
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewEchoRespService(r.Context(), svcCtx)
		resp, err := l.EchoResp(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("ETag", resp.Etag)
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
