// Code generated by craftgo. DO NOT EDIT.

package tasks

import (
	"github.com/dropship-dev/craftgo/example/internal/types/users"
)

// ErrCodeTaskAssignmentConflict is the canonical machine-readable code for TaskAssignmentConflictErr.
const ErrCodeTaskAssignmentConflict = "TASK_ASSIGNMENT_CONFLICT"

// TaskAssignmentConflictBody is the wire-shape payload declared at design time for TaskAssignmentConflictErr.
// User code instantiates this struct and hands it to NewTaskAssignmentConflictErr; the
// framework wraps it with the type-bound code / message metadata.
type TaskAssignmentConflictBody struct {
	Code            string        `json:"code"`
	CurrentAssignee users.UserRef `json:"currentAssignee"`
	PendingStatus   TaskStatus    `json:"pendingStatus"`
}

// TaskAssignmentConflictErr is the typed Conflict error generated for `TaskAssignmentConflict`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type TaskAssignmentConflictErr struct {
	code    string
	message string
	TaskAssignmentConflictBody
}

// NewTaskAssignmentConflictErr constructs TaskAssignmentConflictErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewTaskAssignmentConflictErr(body TaskAssignmentConflictBody) *TaskAssignmentConflictErr {
	return &TaskAssignmentConflictErr{
		code:                       ErrCodeTaskAssignmentConflict,
		message:                    "Conflict",
		TaskAssignmentConflictBody: body,
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *TaskAssignmentConflictErr) Error() string { return e.message }

// HTTPStatus returns the HTTP status code associated with the Conflict category.
func (e *TaskAssignmentConflictErr) HTTPStatus() int { return 409 }

// ErrCodeTaskNotFound is the canonical machine-readable code for TaskNotFoundErr.
const ErrCodeTaskNotFound = "TASK_NOT_FOUND"

// TaskNotFoundErr is the typed NotFound error generated for `TaskNotFound`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type TaskNotFoundErr struct {
	code    string
	message string
}

// NewTaskNotFoundErr constructs TaskNotFoundErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewTaskNotFoundErr() *TaskNotFoundErr {
	return &TaskNotFoundErr{
		code:    ErrCodeTaskNotFound,
		message: "Not found",
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *TaskNotFoundErr) Error() string { return e.message }

// HTTPStatus returns the HTTP status code associated with the NotFound category.
func (e *TaskNotFoundErr) HTTPStatus() int { return 404 }
