// Code generated by craftgo. DO NOT EDIT.

package adminapi

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/admin/v1"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// PingV1 returns the http.HandlerFunc for the
// GET PingV1 endpoint.
func PingV1(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewPingV1Service(r.Context(), svcCtx)
		resp, err := l.PingV1()
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
