// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package scalarsservice

import (
	"context"

	types "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/scalars"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// CreateOrderService carries the per-request state for the
// CreateOrder endpoint of ScalarsService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type CreateOrderService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewCreateOrderService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewCreateOrderService(ctx context.Context, svcCtx *svccontext.ServiceContext) *CreateOrderService {
	return &CreateOrderService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// CreateOrder is the service entry point. Replace the
// TODO with the real implementation.
func (l *CreateOrderService) CreateOrder(req *types.CreateOrderReq) (*types.Envelope[types.Order], error) {
	// TODO: implement
	return nil, nil
}
