// Code generated by craftgo. DO NOT EDIT.

package todos

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/todo/internal/service/todo_service"
	types "github.com/craftgodotdev/craftgo/example/todo/internal/types/todos"
	"github.com/craftgodotdev/craftgo/example/todo/svccontext"
)

// Delete a todo. Idempotent.
//
// DeleteTodo returns the DELETE DeleteTodo handler.
func DeleteTodo(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetTodoReq
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewDeleteTodoService(r.Context(), svcCtx)
		resp, err := l.DeleteTodo(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusOK, resp)
	}
}
