// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package orders

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/orders"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// CreateOrderService runs OrderService.CreateOrder for one request.
type CreateOrderService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewCreateOrderService binds CreateOrderService to ctx; its Logger carries ctx's trace ids.
func NewCreateOrderService(ctx context.Context, svcCtx *svccontext.ServiceContext) *CreateOrderService {
	return &CreateOrderService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Create a new order.
//
// CreateOrder implements OrderService.CreateOrder.
func (l *CreateOrderService) CreateOrder(req *types.CreateOrderReq) (*types.Order, error) {
	// TODO: implement
	return nil, nil
}
