// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package orders

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/orders"
	"github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/shared"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// TrackPublicService runs OrderService.TrackPublic for one request.
type TrackPublicService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewTrackPublicService binds TrackPublicService to ctx; its Logger carries ctx's trace ids.
func NewTrackPublicService(ctx context.Context, svcCtx *svccontext.ServiceContext) *TrackPublicService {
	return &TrackPublicService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Public order tracking by id - CORS only, no auth.
//
// TrackPublic implements OrderService.TrackPublic.
func (l *TrackPublicService) TrackPublic(req *types.GetOrderReq) (*shared.OkResp, error) {
	// TODO: implement
	return nil, nil
}
