// Code generated by craftgo. DO NOT EDIT.

package projectservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/project-service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ListProjects returns the http.HandlerFunc for the
// GET ListProjects endpoint.
func ListProjects(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewListProjectsService(r.Context(), svcCtx)
		resp, err := l.ListProjects()
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
