// Code generated by craftgo. DO NOT EDIT.

package services

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/ledger_entry"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Lists every ledger entry; its body component is LedgerEntryListRespBody.
//
// List returns the GET List handler.
func List(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewListService(r.Context(), svcCtx)
		resp, err := l.List()
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusOK, resp)
	}
}
