// Code generated by craftgo. DO NOT EDIT.

package profileservice

import (
	"encoding/json"
	"github.com/dropship-dev/craftgo/pkg/server"
	"net/http"

	logic "github.com/dropship-dev/craftgo/tests/e2e/complex/internal/logic/profile-service"
	types "github.com/dropship-dev/craftgo/tests/e2e/complex/internal/types/design"
	"github.com/dropship-dev/craftgo/tests/e2e/complex/svccontext"
)

// GetProfile returns the profile with the given id.
// GetProfileHandler returns the http.HandlerFunc for the
// GET GetProfile endpoint.
func GetProfileHandler(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetProfileReq
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := logic.NewGetProfileLogic(r.Context(), svcCtx)
		resp, err := l.GetProfile(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
