// Code generated by craftgo. DO NOT EDIT.

package shared

// Reason a validation failed, surfaced in the ValidationErr body so clients
// can branch without string-matching messages.
type FieldProblem string

const (
	FieldProblemMissing  FieldProblem = "Missing"
	FieldProblemTooLong  FieldProblem = "TooLong"
	FieldProblemTooShort FieldProblem = "TooShort"
	FieldProblemFormat   FieldProblem = "Format"
)
