// Code generated by craftgo. DO NOT EDIT.

package payments

import (
	craftevents "github.com/craftgodotdev/craftgo/pkg/events"

	types "github.com/craftgodotdev/craftgo/example/brokers/internal/types/payments"
)

// SettledContract is the wire identity of Settled.
const SettledContract = "payments.settled.v1"

// A payment cleared upstream.
//
// Settled is the payments.settled.v1 event contract.
var Settled = craftevents.NewEvent[types.Settlement](SettledContract, (*types.Settlement).Validate)
