// Code generated by craftgo. DO NOT EDIT.

package routes

import (
	"github.com/dropship-dev/craftgo/pkg/server"
	userserviceroutes "github.com/dropship-dev/craftgo/tests/e2e/users/internal/routes/user-service"

	"github.com/dropship-dev/craftgo/tests/e2e/users/svccontext"
)

// RegisterAll wires every service's routes onto srv with one call.
// Generated from the DSL service set; always overwritten.
func RegisterAll(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	userserviceroutes.RegisterRoutes(srv, svcCtx)
}
