// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package services

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/services"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// CardListService runs Report.CardList for one request.
type CardListService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewCardListService binds CardListService to ctx; its Logger carries ctx's trace ids.
func NewCardListService(ctx context.Context, svcCtx *svccontext.ServiceContext) *CardListService {
	return &CardListService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Lists the report's cards; its body component is ReportCardList2RespBody.
//
// CardList implements Report.CardList.
func (l *CardListService) CardList() (*types.ReportCards, error) {
	// TODO: implement
	return nil, nil
}
