package codegen

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/craftgodotdev/craftgo/internal/config"
	"github.com/craftgodotdev/craftgo/internal/protodesign"
	"github.com/craftgodotdev/craftgo/internal/semantic"
)

// planSrc is two packages covering the shapes the plan must name: enums,
// errors, events, a middleware, a `@group` block, and a package without events.
var planSrc = []string{`package shop
enum Tier { Gold = 1  Silver = 2 }
error NotFound OrderMissing { id string }
type Order {
	id    string @minLength(1)
	tier  Tier
}
middleware AuthRequired
event Placed { payload Order }
@prefix("/shop")
service Orders {
	get GetOrder /orders/{id} { request Order  response Order }
	post PlaceOrder /orders { request Order  response Order }
}
@group("admin/v2")
extend service Orders {
	get Audit /audit { response Order }
}`, `package warehouse
type Shelf { code string @minLength(1) }
service Stock {
	get Shelves /shelves { response Shelf }
}`}

// planConfig enables every target, so the plan meets the widest output.
func planConfig() *config.Config { return eventsConfig() }

// emitOnly runs a pass without its sweep, so the test sees every file the
// emitters wrote.
func emitOnly(t *testing.T, proj *semantic.Project, cfg *config.Config, dir string) {
	t.Helper()
	sel, _ := selection(nil)
	if err := emit(Inputs{Design: proj}, cfg, dir, sel); err != nil {
		t.Fatalf("emit: %v", err)
	}
}

// The plan names exactly the regenerated files a pass writes.
func TestPlanMatchesWhatTheRunWrites(t *testing.T) {
	dir := t.TempDir()
	cfg := planConfig()
	proj := analyzeProject(t, planSrc...)
	emitOnly(t, proj, cfg, dir)

	planned := regeneratedFiles(Inputs{Design: proj}, cfg, dir)
	written := regeneratedUnder(t, dir)
	// An empty tree would compare nothing and pass.
	if len(written) < 15 {
		t.Fatalf("the fixture regenerated %d files, too few to pin the plan", len(written))
	}

	for _, f := range sortedPaths(written) {
		if !planned[f] {
			t.Errorf("%s is regenerated but unplanned - the sweep would delete it; add it to the plan", rel(dir, f))
		}
	}
	for _, f := range sortedPaths(planned) {
		if !written[f] {
			t.Errorf("%s is planned but nothing wrote it - drop it from the plan", rel(dir, f))
		}
	}
}

// No gen-once scaffold is planned, and each survives the sweep, svccontext.go
// in a swept directory included.
func TestScaffoldsSurviveTheSweep(t *testing.T) {
	dir := t.TempDir()
	cfg := planConfig()
	cfg.Output.Main = "./main.go"
	proj := analyzeProject(t, planSrc...)
	if err := Generate(Inputs{Design: proj}, cfg, dir); err != nil {
		t.Fatalf("generate: %v", err)
	}
	planned := regeneratedFiles(Inputs{Design: proj}, cfg, dir)
	scaffolds := 0
	_ = filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !hasPrefix(path, "// Scaffold generated by craftgo") {
			return nil
		}
		scaffolds++
		if planned[path] {
			t.Errorf("%s is a scaffold and must not be part of the plan", rel(dir, path))
		}
		return nil
	})
	if scaffolds == 0 {
		t.Fatal("the fixture wrote no scaffold, so the rule is untested")
	}
	if _, err := os.Stat(filepath.Join(dir, "svccontext", "svccontext.go")); err != nil {
		t.Errorf("the container scaffold shares a directory with a regenerated file and must survive: %v", err)
	}
}

// The sweep never walks the project root, even when an output key resolves
// to it.
func TestTheProjectRootIsNeverSwept(t *testing.T) {
	dir := t.TempDir()
	cfg := planConfig()
	cfg.Output.Types = "."
	cfg.Output.Svccontext = "./svccontext.go"
	cfg.Output.OpenAPI = "./openapi.yaml"
	cfg.Events.Targets = []config.EventTarget{{Lang: config.LangGo, Out: "."}}
	sel, _ := selection(nil)
	for _, got := range outputDirs(cfg, dir, sel) {
		if got.path == filepath.Clean(dir) {
			t.Errorf("the sweep must not walk the project root, got %v", outputDirs(cfg, dir, sel))
		}
	}
}

// regeneratedUnder returns every file under dir that opens with craftgo's
// or a plugin's generated header.
func regeneratedUnder(t *testing.T, dir string) map[string]bool {
	t.Helper()
	out := map[string]bool{}
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		if hasPrefix(path, "// Code generated by craftgo") || hasPrefix(path, "# Generated by craftgo") || hasPrefix(path, protodesign.PluginHeaders[0]) || hasPrefix(path, protodesign.PluginHeaders[1]) {
			out[path] = true
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func hasPrefix(path, prefix string) bool {
	body, err := os.ReadFile(path)
	return err == nil && strings.HasPrefix(string(body), prefix)
}

func sortedPaths(set map[string]bool) []string {
	out := make([]string, 0, len(set))
	for p := range set {
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}

func rel(root, path string) string {
	r, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return filepath.ToSlash(r)
}
