package codegen

import (
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/craftgodotdev/craftgo/internal/codegen/docs"
	"github.com/craftgodotdev/craftgo/internal/codegen/golang"
	"github.com/craftgodotdev/craftgo/internal/config"
	"github.com/craftgodotdev/craftgo/internal/protodesign"
)

// An output directory belongs to one design. What craftgo regenerates
// there is therefore its own, so a run ends by deleting every file in
// those directories that carries a generated header and that the run did
// not write. Nothing else can identify them: a service the design has
// dropped takes its name with it, and nothing left in the design says
// which file on disk used to be its.
//
// The sweep runs over the whole pass rather than inside one emitter, so
// every regenerated output goes on the same terms - the handler set of a
// service that is gone, its routes, the types folder of a package that
// was deleted, the descriptor of an event nobody declares any more.
//
// Gen-once territory is outside it. output.service, output.middleware,
// output.config and main.go are written only when missing, so their
// directories are never walked and the user's own code in them is never
// a question the sweep has to answer.

// generatedHeaders open the files craftgo rewrites on every run: the Go
// header, and the one the YAML documents carry. A gen-once scaffold opens
// with a different line, so the sweep never considers one.
var generatedHeaders = []string{
	"// Code generated by craftgo. DO NOT EDIT.",
	"# Generated by craftgo. DO NOT EDIT.",
}

// sweepDir is one directory the sweep walks and the headers that mark a
// file there as regenerated. The pb directory is swept for the plugins'
// headers, every other for craftgo's own, so plugin output anywhere else
// is never touched.
type sweepDir struct {
	path    string
	headers []string
}

// isGenerated reports whether the file at path opens with one of headers.
// A missing or unreadable file does not, so the sweep can ask this
// instead of stat-ing first.
func isGenerated(path string, headers []string) bool {
	body, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	for _, header := range headers {
		if strings.HasPrefix(string(body), header) {
			return true
		}
	}
	return false
}

// outputDirs are the directories the selected targets regenerate into. A
// target that does not run does not sweep, so a narrowed pass never walks
// another target's output.
func outputDirs(cfg *config.Config, projectRoot string, sel map[string]bool) []sweepDir {
	var dirs []sweepDir
	if sel[config.LangGo] {
		for _, dir := range golang.OutputDirs(cfg, projectRoot) {
			dirs = append(dirs, sweepDir{path: dir, headers: generatedHeaders})
		}
		if !cfg.Output.PBDisabled() {
			dirs = append(dirs, sweepDir{path: filepath.Join(projectRoot, cfg.Output.PB), headers: protodesign.PluginHeaders})
		}
	}
	dirs = append(dirs, eventOutputDirs(cfg, projectRoot, sel)...)
	if sel[TargetDocs] {
		if doc := docs.OutputDir(cfg, projectRoot); doc != "" {
			dirs = append(dirs, sweepDir{path: filepath.Dir(doc), headers: generatedHeaders})
		}
	}
	return owned(dirs, projectRoot)
}

// eventOutputDirs is [outputDirs] for the language targets alone, which
// is what a run of [GenerateEventTargets] sweeps.
func eventOutputDirs(cfg *config.Config, projectRoot string, sel map[string]bool) []sweepDir {
	var dirs []sweepDir
	for _, target := range LangTargets {
		if !sel[target.Lang] {
			continue
		}
		cfgTarget, ok := cfg.Events.TargetFor(target.Lang)
		if !ok || !cfgTarget.Enabled() {
			continue
		}
		dirs = append(dirs, sweepDir{path: filepath.Join(projectRoot, cfgTarget.Out), headers: generatedHeaders})
	}
	return owned(dirs, projectRoot)
}

// owned drops the directories a design does not own outright and orders
// what is left. A key left blank resolves to the project root, and the
// root holds whatever else the repository puts there - a sibling design's
// output included - so it is never swept.
func owned(dirs []sweepDir, projectRoot string) []sweepDir {
	root := filepath.Clean(projectRoot)
	seen := map[string]bool{}
	out := make([]sweepDir, 0, len(dirs))
	for _, dir := range dirs {
		dir.path = filepath.Clean(dir.path)
		if dir.path == root || strings.HasPrefix(root, dir.path+string(filepath.Separator)) || seen[dir.path] {
			continue
		}
		seen[dir.path] = true
		out = append(out, dir)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].path < out[j].path })
	return out
}

// regeneratedFiles is every file this project's targets produce, whatever
// `--target` narrowed the run to: a target that did not run still owns
// its output, and a directory holding two targets' files must not lose
// one of them to the other's sweep.
func regeneratedFiles(in Inputs, cfg *config.Config, projectRoot string) map[string]bool {
	proj := in.Design
	files := golang.RegeneratedFiles(proj, in.Protos, cfg, projectRoot)
	for _, target := range LangTargets {
		cfgTarget, ok := cfg.Events.TargetFor(target.Lang)
		if !ok || !cfgTarget.Enabled() {
			continue
		}
		if target.Lang == config.LangGo {
			files = append(files, golang.RegeneratedEventFiles(proj, projectRoot, cfgTarget.Out)...)
		}
	}
	if doc := docs.RegeneratedFile(proj, cfg, projectRoot); doc != "" {
		files = append(files, doc)
	}
	set := make(map[string]bool, len(files))
	for _, file := range files {
		set[file] = true
	}
	return set
}

// prune deletes, under every directory dirs names, the generated files
// written does not name, then removes the directories that leaves empty.
func prune(dirs []sweepDir, written map[string]bool) error {
	for _, dir := range dirs {
		root := dir.path
		var emptied []string
		err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() || written[path] || !isGenerated(path, dir.headers) {
				return nil
			}
			if rmErr := os.Remove(path); rmErr != nil && !os.IsNotExist(rmErr) {
				return rmErr
			}
			emptied = append(emptied, filepath.Dir(path))
			return nil
		})
		if err != nil {
			return err
		}
		pruneEmptyDirs(root, emptied)
	}
	return nil
}

// pruneEmptyDirs removes the directories a sweep emptied, deepest first,
// and the parents that empties in turn. It stops at the output root: the
// directory is the design's, and a run that leaves it bare still owns it.
func pruneEmptyDirs(root string, dirs []string) {
	sort.Sort(sort.Reverse(sort.StringSlice(dirs)))
	for _, dir := range dirs {
		for strings.HasPrefix(dir, root+string(filepath.Separator)) {
			entries, err := os.ReadDir(dir)
			if err != nil || len(entries) > 0 {
				break
			}
			if os.Remove(dir) != nil {
				break
			}
			dir = filepath.Dir(dir)
		}
	}
}
