// Package codegen turns a validated [semantic.Package] into Go source files.
//
// Each generator function in this package is responsible for one artefact
// (currently only types.go; handler/routes/logic scaffolds and OpenAPI/client
// generators land in subsequent slices). Output files are formatted with
// `go/format` before being written so that diffs in version control are
// minimal and the generated code passes `gofmt`.
package codegen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/dropship-dev/craftgo/internal/ast"
	"github.com/dropship-dev/craftgo/internal/semantic"
)

// GenerateTypes emits a `types.go` file under outDir/<pkg.Name>/ containing
// Go struct definitions for every concrete (non-generic) [ast.TypeDecl] in
// pkg. Generic declarations (those with [ast.TypeDecl.TypeParams]) are
// skipped — their concrete instances are emitted at the call site once
// generic instantiation lands.
//
// outDir is the configured `output.types` directory; the package name
// segment is appended so that types live alongside the rest of the
// service-scoped artefacts.
func GenerateTypes(pkg *semantic.Package, outDir string) error {
	if pkg.Name == "" {
		return fmt.Errorf("package has no name")
	}
	pkgDir := filepath.Join(outDir, pkg.Name)
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		return err
	}
	src := buildTypesGo(pkg)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return fmt.Errorf("format types.go: %w\n--- source ---\n%s", err, src)
	}
	return os.WriteFile(filepath.Join(pkgDir, "types.go"), formatted, 0o644)
}

// buildTypesGo assembles the textual contents of types.go, including the
// generated-file header, package clause, imports, and one struct per
// concrete TypeDecl in deterministic name order. The result is returned
// pre-formatting; the caller runs `go/format` to normalise whitespace.
func buildTypesGo(pkg *semantic.Package) string {
	parts := []string{
		"// Code generated by craftgo. DO NOT EDIT.\n",
		"package " + pkg.Name + "\n",
	}
	if imps := collectImports(pkg); len(imps) > 0 {
		parts = append(parts, renderImports(imps))
	}
	names := make([]string, 0, len(pkg.Types))
	for n := range pkg.Types {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, name := range names {
		parts = append(parts, renderType(pkg.Types[name]))
	}
	return strings.Join(parts, "\n")
}

// renderImports returns the `import (...)` block. Each path is quoted
// via strconv.Quote so non-ASCII characters in stdlib paths (extremely
// unlikely but harmless) survive correctly.
func renderImports(imps []string) string {
	lines := make([]string, len(imps))
	for i, imp := range imps {
		lines[i] = "\t" + strconv.Quote(imp)
	}
	return fmt.Sprintf("import (\n%s\n)\n", strings.Join(lines, "\n"))
}

// collectImports walks every field type in pkg and returns the sorted set
// of standard-library imports that the generated structs require (`io`,
// `mime/multipart`, `encoding/json`).
func collectImports(pkg *semantic.Package) []string {
	imports := map[string]bool{}
	for _, td := range pkg.Types {
		for _, m := range td.Body {
			f, ok := m.(*ast.Field)
			if !ok {
				continue
			}
			collectFieldImports(f.Type, imports)
		}
	}
	var out []string
	for imp := range imports {
		out = append(out, imp)
	}
	sort.Strings(out)
	return out
}

// collectFieldImports recurses into a TypeRef collecting any built-in
// names that resolve to imported Go types (`any` → encoding/json, `reader`
// / `writer` → io, `file` → mime/multipart). Generic and map types are
// recursed into so nested usages are caught too.
func collectFieldImports(t *ast.TypeRef, set map[string]bool) {
	if t == nil {
		return
	}
	if t.Map != nil {
		collectFieldImports(t.Map.Key, set)
		collectFieldImports(t.Map.Value, set)
		return
	}
	if t.Named != nil {
		switch t.Named.Name.String() {
		case "any":
			set["encoding/json"] = true
		case "reader", "writer":
			set["io"] = true
		case "file":
			set["mime/multipart"] = true
		}
		for _, a := range t.Named.Args {
			collectFieldImports(a, set)
		}
	}
}

// renderType returns the Go source for one TypeDecl: doc, header
// (with optional `[T any, ...]` generic params), and body.
func renderType(td *ast.TypeDecl) string {
	doc := renderDoc(td.Doc, "")
	body := renderTypeBody(td.Body)
	header := "type " + td.Name + renderTypeParams(td.TypeParams) + " struct {\n" + body + "}\n"
	return doc + header
}

// renderTypeParams returns "[T any, U any]" for a generic decl, or ""
// when the decl has no type parameters.
func renderTypeParams(params []string) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = p + " any"
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// renderTypeBody returns the contents of a struct body — fields and
// mixin embeds — already indented with one leading tab per line. The
// caller wraps with the `struct { ... }` braces.
func renderTypeBody(members []ast.TypeMember) string {
	var sb strings.Builder
	for _, m := range members {
		switch v := m.(type) {
		case *ast.Field:
			sb.WriteString(renderField(v))
		case *ast.Mixin:
			sb.WriteString(renderMixin(v))
		}
	}
	return sb.String()
}

// renderField returns one struct field line (with leading tab). The
// JSON tag is computed by [jsonTag]; doc comments are emitted by
// [renderDoc] and prepended.
func renderField(f *ast.Field) string {
	return renderDoc(f.Doc, "\t") +
		fmt.Sprintf("\t%s %s `json:%s`\n", GoFieldName(f.Name), GoTypeRef(f.Type), strconv.Quote(jsonTag(f)))
}

// renderMixin returns one Go-level embedded-type line. Qualified mixin
// references (`pkg.Name`) are rendered using the last segment for now;
// cross-package resolution will revisit the qualified form.
func renderMixin(m *ast.Mixin) string {
	parts := strings.Split(m.Ref.Name.String(), ".")
	return "\t" + parts[len(parts)-1] + "\n"
}

// GoTypeRef converts an [ast.TypeRef] into the corresponding Go type
// expression. The optional suffix (`?`) prepends `*` only when the
// underlying Go type isn't already nilable: slices, maps, channels,
// interfaces, and pointer-shaped builtins (`file` → `*multipart.FileHeader`)
// already use `nil` as their zero value, so wrapping them in another
// pointer would just produce `**T` / `*[]T` for no semantic gain. Value
// types (`string`, `int`, user structs) still receive `*` so the
// generated field can distinguish "absent" from the zero value.
func GoTypeRef(t *ast.TypeRef) string {
	if t == nil {
		return ""
	}
	var s string
	if t.Map != nil {
		s = "map[" + GoTypeRef(t.Map.Key) + "]" + GoTypeRef(t.Map.Value)
	} else if t.Named != nil {
		s = goNamedType(t.Named)
	}
	if t.Array {
		s = "[]" + s
	}
	if t.Optional && !isNilableGoType(s) {
		s = "*" + s
	}
	return s
}

// isNilableGoType reports whether the Go type expression `s` can take
// the value `nil` directly. Used by [GoTypeRef] to skip a redundant
// pointer wrap on optional fields whose base type is already nilable.
//
// The check is purely syntactic — it inspects the leading characters of
// the rendered type, plus a small fixed set of builtin/std-lib names —
// because the codegen never sees a Go reflect.Type. That's enough to
// catch every shape the DSL currently produces: arrays, maps, the
// `file` / `reader` / `writer` / `any` / `bytes` builtins, and any
// user-supplied pointer.
func isNilableGoType(s string) bool {
	if s == "" {
		return false
	}
	switch {
	case strings.HasPrefix(s, "[]"),
		strings.HasPrefix(s, "map["),
		strings.HasPrefix(s, "*"),
		strings.HasPrefix(s, "chan "),
		strings.HasPrefix(s, "func("):
		return true
	}
	switch s {
	case "io.Reader", "io.Writer", "io.ReadWriter",
		"any", "interface{}", "json.RawMessage", "error":
		return true
	}
	return false
}

// goNamedType maps a [ast.NamedTypeRef] to its Go form. Built-in DSL
// names translate to the standard-library equivalents documented in
// the README; generic instances render with Go 1.18+ generic syntax,
// e.g. `Page<Book>` becomes `Page[Book]`.
func goNamedType(n *ast.NamedTypeRef) string {
	name := n.Name.String()
	switch name {
	case "bytes":
		return "[]byte"
	case "any":
		return "json.RawMessage"
	case "reader":
		return "io.Reader"
	case "writer":
		return "io.Writer"
	case "file":
		return "*multipart.FileHeader"
	}
	if len(n.Args) > 0 {
		var parts []string
		for _, a := range n.Args {
			parts = append(parts, GoTypeRef(a))
		}
		return name + "[" + strings.Join(parts, ", ") + "]"
	}
	return name
}

// commonInitialisms enumerates abbreviations that should be rendered fully
// upper-cased when they appear as a word inside a Go identifier (matches
// `golint`/`staticcheck` conventions and mirrors the table documented in
// the project README).
var commonInitialisms = map[string]bool{
	"id": true, "url": true, "uri": true, "api": true, "http": true,
	"https": true, "json": true, "xml": true, "tcp": true, "udp": true,
	"dns": true, "db": true, "sql": true, "csv": true, "tls": true,
	"ssl": true, "sha": true, "md5": true, "cdn": true, "dom": true,
	"pdf": true, "gif": true, "jpeg": true, "png": true, "xss": true,
	"csrf": true, "cpu": true, "gpu": true, "ram": true, "os": true,
	"io": true, "eof": true, "ip": true, "mac": true, "utf8": true,
	"ascii": true,
}

// GoFieldName converts a DSL field name (which is allowed to be lowercase,
// snake_case, kebab-case, or camelCase) into an exported Go identifier
// applying the common-initialism rule. The DSL field name is preserved
// verbatim as the JSON tag — see [jsonTag].
func GoFieldName(name string) string {
	parts := splitFieldName(name)
	var sb strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if commonInitialisms[strings.ToLower(p)] {
			sb.WriteString(strings.ToUpper(p))
			continue
		}
		sb.WriteString(strings.ToUpper(p[:1]))
		sb.WriteString(strings.ToLower(p[1:]))
	}
	return sb.String()
}

// splitFieldName breaks a name into word components on `_`, `-`, and
// camelCase boundaries. Consecutive uppercase letters are kept together as
// a single acronym word (so `DBError` → `["DB", "Error"]` and `HTTPRequest`
// → `["HTTP", "Request"]`); a new word starts whenever an uppercase letter
// follows a lowercase letter, OR when an uppercase letter sits between two
// other uppercase letters and is followed by a lowercase letter (the
// "acronym ends here" boundary).
func splitFieldName(s string) []string {
	if s == "" {
		return nil
	}
	runes := []rune(s)
	var parts []string
	var current strings.Builder
	flush := func() {
		if current.Len() > 0 {
			parts = append(parts, current.String())
			current.Reset()
		}
	}
	isUpper := func(r rune) bool { return r >= 'A' && r <= 'Z' }
	isLower := func(r rune) bool { return r >= 'a' && r <= 'z' }
	for i, r := range runes {
		if r == '_' || r == '-' {
			flush()
			continue
		}
		if i > 0 {
			prev := runes[i-1]
			switch {
			case isUpper(r) && isLower(prev):
				// camelCase boundary: lowercase → uppercase.
				flush()
			case isUpper(r) && isUpper(prev) && i+1 < len(runes) && isLower(runes[i+1]):
				// Acronym boundary: ABc → split before A.
				flush()
			}
		}
		current.WriteRune(r)
	}
	flush()
	return parts
}

// jsonTag renders the JSON tag for a field. Per the project convention
// "DSL field name = JSON tag (1:1, no conversion)" the original name is
// used verbatim. Optional fields receive `,omitempty`; required fields
// (carrying `@required`) do not, even when also marked optional.
//
// Fields bound to a non-body location (`@path`, `@query`, `@header`,
// `@cookie`) are excluded from the JSON shape entirely (`json:"-"`) so
// neither the request decoder nor the response encoder picks them up.
// `@form` is left in the body tag because the multipart handler binds
// its own table; the JSON tag is harmless for those types.
func jsonTag(f *ast.Field) string {
	if isNonBodyBound(f) {
		return "-"
	}
	for _, d := range f.Decorators {
		if d.Name == "required" {
			return f.Name
		}
	}
	if f.Type != nil && f.Type.Optional {
		return f.Name + ",omitempty"
	}
	return f.Name
}

// isNonBodyBound reports whether f carries an explicit binding decorator
// that places its value outside the JSON body (`@path`, `@query`,
// `@header`, `@cookie`). Those values are populated from the URL / headers
// / cookies — never from the body — so the generated struct should hide
// them from JSON entirely.
func isNonBodyBound(f *ast.Field) bool {
	for _, d := range f.Decorators {
		switch d.Name {
		case "path", "query", "header", "cookie":
			return true
		}
	}
	return false
}
