// Code generated by craftgo. DO NOT EDIT.

package numbers

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/numbers_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/numbers"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// EchoBigMultipleOf returns the POST EchoBigMultipleOf handler.
func EchoBigMultipleOf(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.NumberBigMultipleOf
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewEchoBigMultipleOfService(r.Context(), svcCtx)
		resp, err := l.EchoBigMultipleOf(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusCreated, resp)
	}
}
