// Code generated by craftgo. DO NOT EDIT.

package customers

import (
	"fmt"
	"net/url"
	"regexp"
	"time"
	"unicode/utf8"
)

// The regexes of the @pattern and @format checks, compiled once.
var (
	_pattern0 = regexp.MustCompile("^[A-Z0-9 -]{3,12}$")
	_pattern1 = regexp.MustCompile("^\\+?[0-9 ()-]{6,20}$")
)

// Validate returns the first constraint v violates, or nil.
func (v *Address) Validate() error {
	if l := utf8.RuneCountInString(v.Street); l < 1 || l > 200 {
		return fmt.Errorf("street: length out of range [1, 200]")
	}
	if v.Street2 != nil && utf8.RuneCountInString(*v.Street2) > 200 {
		return fmt.Errorf("street2: length greater than 200")
	}
	if utf8.RuneCountInString(v.City) < 1 {
		return fmt.Errorf("city: length less than 1")
	}
	if utf8.RuneCountInString(v.City) > 100 {
		return fmt.Errorf("city: length greater than 100")
	}
	if v.Region != nil && utf8.RuneCountInString(*v.Region) > 100 {
		return fmt.Errorf("region: length greater than 100")
	}
	if !_pattern0.MatchString(v.PostalCode) {
		return fmt.Errorf("postalCode: does not match pattern")
	}
	if err := v.Country.Validate(); err != nil {
		return fmt.Errorf("country: %w", err)
	}
	if v.Geo != nil {
		if err := v.Geo.Validate(); err != nil {
			return fmt.Errorf("geo: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Contact) Validate() error {
	if v.Email != nil {
		if err := v.Email.Validate(); err != nil {
			return fmt.Errorf("email: %w", err)
		}
	}
	if v.Phone != nil && !_pattern1.MatchString(*v.Phone) {
		return fmt.Errorf("phone: does not match pattern")
	}
	if v.Email == nil && v.Phone == nil {
		return fmt.Errorf("requiresOneOf [email phone] - at least one must be set")
	}
	{
		n := 0
		if v.Work != nil {
			n++
		}
		if v.Personal != nil {
			n++
		}
		if n > 1 {
			return fmt.Errorf("mutuallyExclusive [work personal] - at most one may be set")
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *CreateCustomerReq) Validate() error {
	if err := v.Email.Validate(); err != nil {
		return fmt.Errorf("email: %w", err)
	}
	if l := utf8.RuneCountInString(v.Name); l < 1 || l > 120 {
		return fmt.Errorf("name: length out of range [1, 120]")
	}
	if err := v.PrimaryAddress.Validate(); err != nil {
		return fmt.Errorf("primaryAddress: %w", err)
	}
	if err := v.Contact.Validate(); err != nil {
		return fmt.Errorf("contact: %w", err)
	}
	if v.Bio != nil && utf8.RuneCountInString(*v.Bio) > 500 {
		return fmt.Errorf("bio: length greater than 500")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Customer) Validate() error {
	if err := v.ID.Validate(); err != nil {
		return fmt.Errorf("id: %w", err)
	}
	if err := v.Email.Validate(); err != nil {
		return fmt.Errorf("email: %w", err)
	}
	if l := utf8.RuneCountInString(v.Name); l < 1 || l > 120 {
		return fmt.Errorf("name: length out of range [1, 120]")
	}
	if err := v.PrimaryAddress.Validate(); err != nil {
		return fmt.Errorf("primaryAddress: %w", err)
	}
	if v.BillingAddress != nil {
		if err := v.BillingAddress.Validate(); err != nil {
			return fmt.Errorf("billingAddress: %w", err)
		}
	}
	if err := v.Contact.Validate(); err != nil {
		return fmt.Errorf("contact: %w", err)
	}
	if v.AvatarURL != nil {
		if _u, _err := url.Parse(*v.AvatarURL); _err != nil || (_u.Scheme != "http" && _u.Scheme != "https") {
			return fmt.Errorf("avatarUrl: not a valid URL")
		}
	}
	if v.LoyaltyPoints != nil && *v.LoyaltyPoints < 0 {
		return fmt.Errorf("loyaltyPoints: below minimum 0")
	}
	if v.LoyaltyPoints != nil && *v.LoyaltyPoints > 1000000 {
		return fmt.Errorf("loyaltyPoints: above maximum 1000000")
	}
	if v.Bio != nil && utf8.RuneCountInString(*v.Bio) > 500 {
		return fmt.Errorf("bio: length greater than 500")
	}
	if _, _err := time.Parse(time.RFC3339, v.CreatedAt); _err != nil {
		return fmt.Errorf("createdAt: not a valid RFC 3339 datetime")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *CustomerRef) Validate() error {
	if err := v.ID.Validate(); err != nil {
		return fmt.Errorf("id: %w", err)
	}
	if l := utf8.RuneCountInString(v.Name); l < 1 || l > 120 {
		return fmt.Errorf("name: length out of range [1, 120]")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Geocode) Validate() error {
	if err := v.Lat.Validate(); err != nil {
		return fmt.Errorf("lat: %w", err)
	}
	if err := v.Lng.Validate(); err != nil {
		return fmt.Errorf("lng: %w", err)
	}
	if v.Altitude != nil && *v.Altitude < -500 {
		return fmt.Errorf("altitude: below minimum -500")
	}
	if v.Altitude != nil && *v.Altitude > 9000 {
		return fmt.Errorf("altitude: above maximum 9000")
	}
	if _, _err := time.Parse(time.RFC3339, v.CapturedAt); _err != nil {
		return fmt.Errorf("capturedAt: not a valid RFC 3339 datetime")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *GetCustomerReq) Validate() error {
	if l := utf8.RuneCountInString(v.ID); l < 1 || l > 64 {
		return fmt.Errorf("id: length out of range [1, 64]")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *UploadAvatarReq) Validate() error {
	if l := utf8.RuneCountInString(v.ID); l < 1 || l > 64 {
		return fmt.Errorf("id: length out of range [1, 64]")
	}
	if v.Image == nil {
		return fmt.Errorf("image: required")
	}
	if v.Image != nil && v.Image.Size > 5242880 {
		return fmt.Errorf("image: file size exceeds 5242880 bytes")
	}
	if v.Image != nil {
		switch v.Image.Header.Get("Content-Type") {
		case "image/png", "image/jpeg", "image/webp":
		default:
			return fmt.Errorf("image: disallowed content type")
		}
	}
	return nil
}
