// Code generated by craftgo. DO NOT EDIT.

package combine

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/combine_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/combine"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Echo the narrow-width default matrix. The pre-fill casts each literal to the field primitive so the *T pointer assignment compiles (int32 / int64 / uint16 / float32).
//
// EchoWidth returns the POST EchoWidth handler.
func EchoWidth(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.DefaultsWidth
		{
			__d := int32(7)
			req.W32 = &__d
		}
		{
			__d := int64(9)
			req.W64 = &__d
		}
		{
			__d := uint16(3)
			req.Wu16 = &__d
		}
		{
			__d := float32(1.5)
			req.Wf32 = &__d
		}
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewEchoWidthService(r.Context(), svcCtx)
		resp, err := l.EchoWidth(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
