// Code generated by craftgo. DO NOT EDIT.

package combine

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/combine_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/combine"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Tag a pair. The response sends ETag as a header; its body carries the response type's @mutuallyExclusive and its mixin's @requiresOneOf.
//
// TagPairs returns the POST TagPairs handler.
func TagPairs(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.PairsDoc
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewTagPairsService(r.Context(), svcCtx)
		resp, err := l.TagPairs(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("ETag", resp.Etag)
		server.WriteResponse(w, r, http.StatusCreated, resp)
	}
}
