// Code generated by craftgo. DO NOT EDIT.

package combine

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/combine_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/combine"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Upload a file or a link, exactly one. The multipart body carries the request type's own groups; an empty url part counts as absent.
//
// UploadSource returns the POST UploadSource handler.
func UploadSource(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		defer func() { _ = r.MultipartForm.RemoveAll() }()
		var req types.PairsSource
		if _v := r.FormValue("url"); _v != "" {
			req.URL = &_v
		}
		req.Title = r.FormValue("title")
		if _, header, err := r.FormFile("doc"); err == nil {
			req.Doc = header
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewUploadSourceService(r.Context(), svcCtx)
		resp, err := l.UploadSource(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusCreated, resp)
	}
}
