// Code generated by craftgo. DO NOT EDIT.

package combine

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/combine_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/combine"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Upload a file beside the parts of a mixin with a @requiresOneOf. The multipart body carries the group: sending neither a nor b fails.
//
// UploadPairs returns the http.HandlerFunc for the
// POST UploadPairs multipart endpoint. The handler parses
// `multipart/form-data` bodies, binds every form field declared on
// the request type, and populates `*multipart.FileHeader` fields
// for any DSL-typed `file` declarations.
func UploadPairs(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		// Remove the temp files the parser spilled to disk as soon as the
		// handler returns. net/http sweeps them again at end-of-response, but
		// the explicit cleanup releases disk before the response flush and
		// still runs on panic paths that bypass that sweep.
		defer func() { _ = r.MultipartForm.RemoveAll() }()
		var req types.PairsUpload
		if _v := r.FormValue("a"); _v != "" {
			req.A = &_v
		}
		if _v := r.FormValue("b"); _v != "" {
			req.B = &_v
		}
		if _, header, err := r.FormFile("doc"); err == nil {
			req.Doc = header
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewUploadPairsService(r.Context(), svcCtx)
		resp, err := l.UploadPairs(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
