// Code generated by craftgo. DO NOT EDIT.

package services

import (
	"net/http"
	"strconv"
)

// ErrCodeRateLimited is the canonical machine-readable code for RateLimitedErr.
const ErrCodeRateLimited = "RATE_LIMITED"

// RateLimitedBody is the wire-shape payload declared at design time for RateLimitedErr.
// User code instantiates this struct and hands it to NewRateLimitedErr; the
// framework wraps it with the type-bound code / message metadata.
type RateLimitedBody struct {
	RetryAfter int `json:"-"`
}

// RateLimitedErr is the typed TooManyRequests error generated for `RateLimited`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type RateLimitedErr struct {
	code    string
	message string
	RateLimitedBody
}

// NewRateLimitedErr constructs RateLimitedErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewRateLimitedErr(body RateLimitedBody) *RateLimitedErr {
	return &RateLimitedErr{
		code:            ErrCodeRateLimited,
		message:         "Too many requests",
		RateLimitedBody: body,
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *RateLimitedErr) Error() string { return e.message }

// ErrCode returns the machine-readable error code bound to the type.
// The transport layer reads this via an `interface{ ErrCode() string }`
// assertion when assembling the fallback JSON envelope for errors
// whose body would otherwise marshal to `{}`. The accessor is named
// `ErrCode` (not `Code`) so it does not shadow a user-declared
// `code <type>` field promoted from the embedded body struct.
func (e *RateLimitedErr) ErrCode() string { return e.code }

// HTTPStatus returns the HTTP status code associated with the TooManyRequests category.
func (e *RateLimitedErr) HTTPStatus() int { return 429 }

// WriteResponseHeaders writes the `@header` / `@cookie` fields onto w.
// Called by the generated `writeError` helper before the JSON body is
// encoded so values reach the wire in a single response.
func (e *RateLimitedErr) WriteResponseHeaders(w http.ResponseWriter) {
	w.Header().Set("Retry-After", strconv.Itoa(e.RetryAfter))
}
