// Code generated by craftgo. DO NOT EDIT.

package services

import (
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/shared"
)

// GetUserReq is the workaround for the cross-package-scalar bug.
//
// Originally `id shared.ID @path`, but `isStringBindingType` /
// `stringBindable` look up scalar declarations in the CURRENT
// package only (`pkg.Scalars[name]`). The qualified name
// `"shared.ID"` misses the map and the check falls through with
// `@path requires a string-backed field ... - got shared.ID`,
// even though `shared.ID` IS a `scalar ID string`. So @path /
// @header / @cookie / @query all refuse cross-package scalars
// across the entire binding surface.
//
// The local-string-with-length workaround replays shared.ID's
// validator stack manually — the bug is recorded in the report.
type GetUserReq struct {
	ID string `json:"-"`
}

// ListUsersReq embeds `shared.Pagination` cross-package. The
// implicit mixin form makes the limit / cursor / total fields land
// at the request root, and the optional `query` slot adds the free-
// text filter on top.
type ListUsersReq struct {
	shared.Pagination
	Query *string `json:"query,omitempty"`
}

// ListUsersResp wraps a page of Users with the canonical pagination
// envelope. `meta` is a NESTED reference (not a mixin) so the
// pagination summary lands in its own JSON sub-object — the
// distinction between "embed at root" (mixin) and "embed as nested
// object" (field) is captured cleanly across these two consumers.
type ListUsersResp struct {
	Items []User            `json:"items"`
	Meta  shared.Pagination `json:"meta"`
}

// Project carries the cross-package `shared.ID` scalar (Go field
// type: `string`, validators inherited from the scalar decl) and
// the SAME-PACKAGE `UserRef` nested type — exercise of both the
// qualified and the bare type-reference paths in one DTO.
type Project struct {
	ID    shared.ID `json:"id"`
	Name  string    `json:"name"`
	Owner UserRef   `json:"owner"`
}

// ProjectsResp wraps a slice in an envelope so the response shape
// stays inside what `parseNamedTypeRef` accepts. The brick wall
// the original spec hit: `response Project[]` won't parse — the
// method body's `response` slot is a NamedTypeRef and never sees
// the array-suffix branch.
type ProjectsResp struct {
	Items []Project `json:"items"`
}

// User is the full entity. Embeds `shared.Audit` via the implicit
// CROSS-PACKAGE MIXIN form (`shared.Audit` alone on a body line is
// a mixin reference, not a field) so the createdAt / updatedAt /
// createdBy bookkeeping lands at the wire root without a nested
// envelope.
type User struct {
	shared.Audit
	ID    shared.ID    `json:"id"`
	Email shared.Email `json:"email"`
	Name  string       `json:"name"`
}

// UserRef is the lightweight handle: id + email. Used as a BODY
// request (POST CreateUser, POST BanUser) and as the owner field
// of services.Project.
//
// NOTE: UserRef cannot ride a GET request unchanged. `email
// shared.Email` is a cross-package scalar; the query-bind path in
// `collectBindings` looks up scalar declarations in the current
// package only (`pkg.Scalars[declName]`) and falls through with
// `type shared.Email cannot bind to query`. The transport
// generator never resolves the scalar across the import edge —
// recorded as a bug in the report. The path-only GetUser uses the
// local-scalar `GetUserReq` below as a workaround.
type UserRef struct {
	ID    shared.ID    `json:"id"`
	Email shared.Email `json:"email"`
}
