// Code generated by craftgo. DO NOT EDIT.

package runtime

type RtItem struct {
	Sku   string `json:"sku"`
	Price int    `json:"price"`
}

type RtOrder struct {
	ID    string `json:"id"`
	Total int    `json:"total"`
}

type RtPong struct {
	Name string `json:"name"`
}
