// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package eventsubs

import (
	"context"

	events "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/events"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// CountDispatchedConsumer carries the per-message state for the CountDispatched
// consumer of AnalyticsService. The embedded log.Logger is bound to the
// delivery context; whether that context carries a trace depends on the
// transport - the in-process one starts a fresh context per message.
type CountDispatchedConsumer struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewCountDispatchedConsumer constructs a fresh consumer instance bound to ctx.
func NewCountDispatchedConsumer(ctx context.Context, svcCtx *svccontext.ServiceContext) *CountDispatchedConsumer {
	return &CountDispatchedConsumer{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// CountDispatched handles events.ShipmentDispatched, recording the payload so the
// fixture's round-trip test can assert on what reached logic.
func (l *CountDispatchedConsumer) CountDispatched(payload *events.ShipmentDispatched) error {
	l.svcCtx.Record("CountDispatched", payload)
	return nil
}
