// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package eventsubs

import (
	"context"

	events "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/events"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// TrackTierConsumer carries the per-message state for the TrackTier
// consumer of AnalyticsService. The embedded log.Logger is bound to the
// delivery context; whether that context carries a trace depends on the
// transport - the in-process one starts a fresh context per message.
type TrackTierConsumer struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewTrackTierConsumer constructs a fresh consumer instance bound to ctx.
func NewTrackTierConsumer(ctx context.Context, svcCtx *svccontext.ServiceContext) *TrackTierConsumer {
	return &TrackTierConsumer{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// panicMemberID makes this consumer panic on demand, so the fixture can
// drive a panicking handler on the transport's own delivery goroutine -
// the only place recovery can be observed for what it is.
const panicMemberID = "panic-please"

// TrackTier handles events.TierPromoted, recording the payload so the
// fixture's round-trip test can assert on what reached logic.
func (l *TrackTierConsumer) TrackTier(payload *events.TierPromoted) error {
	if payload.MemberID == panicMemberID {
		panic("TrackTier exploded")
	}
	l.svcCtx.Record("TrackTier", payload)
	return nil
}
