// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package activity

import (
	"context"

	"github.com/craftgodotdev/craftgo/example/taskflow/internal/activity"
	tasks "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/tasks"

	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// RecordTaskCreatedConsumer carries the per-message state for the RecordTaskCreated
// consumer of ActivityService. The embedded log.Logger is pre-bound to the
// message context (trace_id / span_id).
type RecordTaskCreatedConsumer struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewRecordTaskCreatedConsumer constructs a fresh consumer instance bound to ctx.
func NewRecordTaskCreatedConsumer(ctx context.Context, svcCtx *svccontext.ServiceContext) *RecordTaskCreatedConsumer {
	return &RecordTaskCreatedConsumer{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// RecordTaskCreated appends a line to the project feed. The payload
// arrives decoded and validated; returning an error tells the transport
// the message was not processed.
func (l *RecordTaskCreatedConsumer) RecordTaskCreated(payload *tasks.TaskCreated) error {
	l.svcCtx.Activity.Append(activity.Entry{
		ProjectID: string(payload.ProjectID),
		TaskID:    string(payload.TaskID),
		Summary:   "created " + payload.Title,
		At:        payload.CreatedAt,
	})
	return nil
}
