// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package activity

import (
	"context"

	"github.com/craftgodotdev/craftgo/example/taskflow/internal/activity"
	tasks "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/tasks"

	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// RecordStatusChangeConsumer carries the per-message state for the RecordStatusChange
// consumer of ActivityService. The embedded log.Logger is pre-bound to the
// message context (trace_id / span_id).
type RecordStatusChangeConsumer struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewRecordStatusChangeConsumer constructs a fresh consumer instance bound to ctx.
func NewRecordStatusChangeConsumer(ctx context.Context, svcCtx *svccontext.ServiceContext) *RecordStatusChangeConsumer {
	return &RecordStatusChangeConsumer{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// RecordStatusChange appends a line to the project feed. The payload
// arrives decoded and validated; returning an error tells the transport
// the message was not processed.
func (l *RecordStatusChangeConsumer) RecordStatusChange(payload *tasks.TaskStatusChanged) error {
	l.svcCtx.Activity.Append(activity.Entry{
		ProjectID: string(payload.ProjectID),
		TaskID:    string(payload.TaskID),
		Summary:   "status " + string(payload.From) + " -> " + string(payload.To),
		At:        payload.ChangedAt,
	})
	return nil
}
