// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package prefixvar

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/prefixvar"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ListTenantItemsService runs TenantService.ListTenantItems for one request.
type ListTenantItemsService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewListTenantItemsService binds ListTenantItemsService to ctx; its Logger carries ctx's trace ids.
func NewListTenantItemsService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ListTenantItemsService {
	return &ListTenantItemsService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// List a tenant's items. tenantID auto-binds to the @prefix path segment; without the prefix-aware rule it would read from the query string instead.
//
// ListTenantItems implements TenantService.ListTenantItems.
func (l *ListTenantItemsService) ListTenantItems(req *types.TenantListReq) (*types.TenantItemList, error) {
	// TODO: implement
	return nil, nil
}
