// Code generated by craftgo. DO NOT EDIT.

package attachments

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/taskflow/internal/service/attachment_service"
	types "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/attachments"
	"github.com/craftgodotdev/craftgo/example/taskflow/internal/types/shared"
	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// Upload a file attachment to a task (image, PDF or text; ≤10MB).
//
// UploadAttachment returns the POST UploadAttachment handler.
func UploadAttachment(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		defer func() { _ = r.MultipartForm.RemoveAll() }()
		var req types.UploadAttachmentReq
		req.ProjectID = shared.ID(r.PathValue("projectId"))
		req.TaskID = shared.ID(r.PathValue("taskId"))
		if _v := r.FormValue("caption"); _v != "" {
			req.Caption = &_v
		}
		if _, header, err := r.FormFile("file"); err == nil {
			req.File = header
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewUploadAttachmentService(r.Context(), svcCtx)
		resp, err := l.UploadAttachment(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusCreated, resp)
	}
}
