// Code generated by craftgo. DO NOT EDIT.

package services

import (
	"github.com/craftgodotdev/craftgo/pkg/server"

	transport "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/transport/project_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RegisterRoutes registers the ProjectService routes on srv.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api", transport.ListProjects(svcCtx))
}
