// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package rawmodes

import (
	"context"
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// PtPlainService carries the per-request state for the PtPlain endpoint of
// RawModesService. Hand-implemented so the raw-modes runtime tests can
// observe which side of the transport the framework owns.
type PtPlainService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewPtPlainService constructs a fresh service instance bound to ctx.
func NewPtPlainService(ctx context.Context, svcCtx *svccontext.ServiceContext) *PtPlainService {
	return &PtPlainService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// PtPlain is a bare passthrough: logic owns the whole wire.
func (l *PtPlainService) PtPlain(w http.ResponseWriter, r *http.Request) error {
	return server.WriteBytes(w, http.StatusOK, "text/plain; charset=utf-8", []byte("plain"))
}
