// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package rawmodes

import (
	"context"
	"net/http"

	"errors"
	"io"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/rawmodes"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RqDocsReqService carries the per-request state for the RqDocsReq endpoint of
// RawModesService. Hand-implemented so the raw-modes runtime tests can
// observe which side of the transport the framework owns.
type RqDocsReqService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewRqDocsReqService constructs a fresh service instance bound to ctx.
func NewRqDocsReqService(ctx context.Context, svcCtx *svccontext.ServiceContext) *RqDocsReqService {
	return &RqDocsReqService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// RqDocsReq proves the multipart contract is documentation only.
func (l *RqDocsReqService) RqDocsReq(r *http.Request) (*types.RqResp, error) {
	if r.MultipartForm != nil {
		return nil, errors.New("transport must not parse the docs-only multipart contract")
	}
	n, err := io.Copy(io.Discard, r.Body)
	if err != nil {
		return nil, err
	}
	return &types.RqResp{Accepted: int(n)}, nil
}
