// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package rawmodes

import (
	"context"
	"net/http"

	"io"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/rawmodes"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RqRespService carries the per-request state for the RqResp endpoint of
// RawModesService. Hand-implemented so the raw-modes runtime tests can
// observe which side of the transport the framework owns.
type RqRespService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewRqRespService constructs a fresh service instance bound to ctx.
func NewRqRespService(ctx context.Context, svcCtx *svccontext.ServiceContext) *RqRespService {
	return &RqRespService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// RqResp consumes the unread body and lets the framework encode the response.
func (l *RqRespService) RqResp(r *http.Request) (*types.RqResp, error) {
	// Nothing decoded the body: count the raw bytes to prove it.
	n, err := io.Copy(io.Discard, r.Body)
	if err != nil {
		return nil, err
	}
	return &types.RqResp{Accepted: int(n)}, nil
}
