// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package rawmodes

import (
	"context"
	"net/http"

	"bytes"
	"compress/gzip"
	"io"

	"github.com/craftgodotdev/craftgo/pkg/server"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RrNoReqService carries the per-request state for the RrNoReq endpoint of
// RawModesService. Hand-implemented so the raw-modes runtime tests can
// observe which side of the transport the framework owns.
type RrNoReqService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewRrNoReqService constructs a fresh service instance bound to ctx.
func NewRrNoReqService(ctx context.Context, svcCtx *svccontext.ServiceContext) *RrNoReqService {
	return &RrNoReqService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// RrNoReq serves a body that is stored already gzip-compressed, the way a cache entry would be, negotiating per request.
func (l *RrNoReqService) RrNoReq(w http.ResponseWriter, r *http.Request) error {
	return server.WritePrecompressed(w, r, http.StatusOK, "application/json; charset=utf-8", "gzip", cachedGzipJSON, gunzip)
}

// CachedPlainJSON is the identity form of the stored body, exported for
// the runtime test to compare against.
const CachedPlainJSON = `{"ok":true,"items":["a","b","c"]}`

// cachedGzipJSON stands in for a Redis entry that was compressed when it
// was written, so the handler never has to encode JSON on the read path.
var cachedGzipJSON = func() []byte {
	var buf bytes.Buffer
	zw := gzip.NewWriter(&buf)
	_, _ = zw.Write([]byte(CachedPlainJSON))
	_ = zw.Close()
	return buf.Bytes()
}()

func gunzip(b []byte) ([]byte, error) {
	zr, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
		return nil, err
	}
	return io.ReadAll(zr)
}
