// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package projectservice

import (
	"context"

	types "github.com/dropship-dev/craftgo/example/internal/types/projects"

	"github.com/dropship-dev/craftgo/example/svccontext"
	"github.com/dropship-dev/craftgo/pkg/log"
)

// CreateProjectLogic carries the per-request state for the
// CreateProject endpoint of ProjectService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type CreateProjectLogic struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewCreateProjectLogic constructs a fresh logic instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewCreateProjectLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *CreateProjectLogic {
	return &CreateProjectLogic{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// CreateProject is the business-logic entry point. Replace the
// TODO with the real implementation.
func (l *CreateProjectLogic) CreateProject(req *types.CreateProjectReq) (*types.Project, error) {
	// TODO: implement
	return nil, nil
}
