// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package projectservice

import (
	"context"

	types "github.com/dropship-dev/craftgo/example/internal/types/projects"
	shared "github.com/dropship-dev/craftgo/example/internal/types/shared"

	"github.com/dropship-dev/craftgo/example/svccontext"
	"github.com/dropship-dev/craftgo/pkg/log"
)

// DeleteProjectLogic carries the per-request state for the
// DeleteProject endpoint of ProjectService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type DeleteProjectLogic struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewDeleteProjectLogic constructs a fresh logic instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewDeleteProjectLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *DeleteProjectLogic {
	return &DeleteProjectLogic{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// DeleteProject is the business-logic entry point. Replace the
// TODO with the real implementation.
func (l *DeleteProjectLogic) DeleteProject(req *types.GetProjectReq) (*shared.OkResp, error) {
	// TODO: implement
	return nil, nil
}
