// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package shared

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/tasks"
	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// GetTaskService runs TaskService.GetTask for one request.
type GetTaskService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewGetTaskService binds GetTaskService to ctx; its Logger carries ctx's trace ids.
func NewGetTaskService(ctx context.Context, svcCtx *svccontext.ServiceContext) *GetTaskService {
	return &GetTaskService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Fetch one task.
//
// GetTask implements TaskService.GetTask.
func (l *GetTaskService) GetTask(req *types.GetTaskReq) (*types.Task, error) {
	return l.svcCtx.Store.GetTask(req.ProjectID, req.ID)
}
