// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package grpc

import (
	"context"
	"errors"
	"io"

	pb "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/pb/grpc"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
	"google.golang.org/grpc"
)

// ChatService carries the per-request state for the
// Chat endpoint of Greeter. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type ChatService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewChatService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewChatService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ChatService {
	return &ChatService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Chat echoes every greeting back until the client closes its side.
func (l *ChatService) Chat(stream grpc.BidiStreamingServer[pb.HelloRequest, pb.HelloReply]) error {
	for {
		req, err := stream.Recv()
		if errors.Is(err, io.EOF) {
			return nil
		}
		if err != nil {
			return err
		}
		if err := stream.Send(&pb.HelloReply{Message: "echo " + req.GetName()}); err != nil {
			return err
		}
	}
}
