// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package grpc

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// PingService runs Greeter.Ping for one request.
type PingService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewPingService binds PingService to ctx; its Logger carries ctx's trace ids.
func NewPingService(ctx context.Context, svcCtx *svccontext.ServiceContext) *PingService {
	return &PingService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Ping implements Greeter.Ping.
func (l *PingService) Ping(req *emptypb.Empty) (*emptypb.Empty, error) {
	return &emptypb.Empty{}, nil
}
