// Code generated by craftgo. DO NOT EDIT.

package userservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/service/user-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/services"
	shared "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/shared"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// BanUser returns the http.HandlerFunc for the
// POST BanUser endpoint.
func BanUser(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.UserRef
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		req.ID = shared.ID(r.PathValue("id"))
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewBanUserService(r.Context(), svcCtx)
		resp, err := l.BanUser(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
