// Code generated by craftgo. DO NOT EDIT.

package userservice

import (
	"encoding/json"
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/service/user-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/services"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// DeleteUser returns the http.HandlerFunc for the
// DELETE DeleteUser endpoint.
func DeleteUser(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetUserReq
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewDeleteUserService(r.Context(), svcCtx)
		resp, err := l.DeleteUser(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
