// Code generated by craftgo. DO NOT EDIT.

package services

import (
	"github.com/craftgodotdev/craftgo/pkg/server"

	transport "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/transport/header_echo_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RegisterRoutes registers the HeaderEchoService routes on srv.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api/header-echo", transport.ListItems(svcCtx))
}
