// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package adminapi

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/adminapi"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// PingInheritService runs AdminApi.PingInherit for one request.
type PingInheritService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewPingInheritService binds PingInheritService to ctx; its Logger carries ctx's trace ids.
func NewPingInheritService(ctx context.Context, svcCtx *svccontext.ServiceContext) *PingInheritService {
	return &PingInheritService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// PingInherit implements AdminApi.PingInherit.
func (l *PingInheritService) PingInherit() (*types.VerResp, error) {
	return &types.VerResp{Version: "inherit", Ok: true}, nil
}
