// Code generated by craftgo. DO NOT EDIT.

package shared

// Email is a DSL scalar - alias of string with the validators declared on it inherited by every field of this type.
type Email = string

// ID is a DSL scalar - alias of string with the validators declared on it inherited by every field of this type.
type ID = string

// Audit captures the create/update bookkeeping every persistent
// entity carries. Embedded into top-level types via the implicit
// mixin form so the fields land at the wire root without an extra
// nesting level.
type Audit struct {
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	CreatedBy string `json:"createdBy"`
}

// Money is the canonical currency-aware amount: an integer minor-
// unit value paired with the ISO-4217 currency code. `currency` is
// fixed at exactly three characters; `amount` is non-negative so
// the wire type cannot carry a debit (refunds are represented by a
// separate flow, not by a negative Money).
type Money struct {
	Amount   int    `json:"amount"`
	Currency string `json:"currency"`
}

// Pagination is the canonical cursor/limit envelope every list
// endpoint embeds. `limit` carries the standard 1..100 cap with a
// pre-fill of 20 when the caller omits it; `cursor` is the opaque
// continuation token returned by the previous page; `total` is the
// optional total-count summary (omitted when the upstream store can
// not cheaply compute it).
//
// Consumers embed this DTO via the implicit mixin form
// (`type ListUsersReq { shared.Pagination  query string? }`) so the
// pagination contract stays identical across services without copy-
// paste.
type Pagination struct {
	Limit  *int    `json:"limit,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
	Total  *int    `json:"total,omitempty"`
}
