// Code generated by craftgo. DO NOT EDIT.

package shared

import (
	"fmt"
	"time"
)

// Validate checks every field-level constraint declared on Audit.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Audit) Validate() error {
	if _, _err := time.Parse(time.RFC3339, v.CreatedAt); _err != nil {
		return fmt.Errorf("createdAt: not a valid RFC 3339 datetime")
	}
	if _, _err := time.Parse(time.RFC3339, v.UpdatedAt); _err != nil {
		return fmt.Errorf("updatedAt: not a valid RFC 3339 datetime")
	}
	return nil
}

// Validate checks every field-level constraint declared on AuditTrail.
// Returns the first violation; nil when the value satisfies the contract.
func (v *AuditTrail) Validate() error {
	if _, _err := time.Parse(time.RFC3339, v.At); _err != nil {
		return fmt.Errorf("at: not a valid RFC 3339 datetime")
	}
	return nil
}

// Validate checks every field-level constraint declared on Money.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Money) Validate() error {
	if v.Amount < 0 {
		return fmt.Errorf("amount: below minimum 0")
	}
	if l := len(v.Currency); l < 3 || l > 3 {
		return fmt.Errorf("currency: length out of range [3, 3]")
	}
	return nil
}

// Validate checks every field-level constraint declared on Pagination.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Pagination) Validate() error {
	if v.Limit != nil && *v.Limit < 1 {
		return fmt.Errorf("limit: below minimum 1")
	}
	if v.Limit != nil && *v.Limit > 100 {
		return fmt.Errorf("limit: above maximum 100")
	}
	return nil
}

// Validate checks every field-level constraint declared on AccessDeniedErrBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *AccessDeniedErrBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on ConflictErrBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *ConflictErrBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on NotFoundErrBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *NotFoundErrBody) Validate() error {
	if l := len(v.ID); l < 1 || l > 64 {
		return fmt.Errorf("id: length out of range [1, 64]")
	}
	return nil
}
