// Code generated by craftgo. DO NOT EDIT.

package shared

import (
	"fmt"
	"net/mail"
	"time"
)

// Validate checks every field-level constraint declared on Audit.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Audit) Validate() error {
	if _, _err := time.Parse(time.RFC3339, v.CreatedAt); _err != nil {
		return fmt.Errorf("createdAt: not a valid RFC 3339 datetime")
	}
	if _, _err := time.Parse(time.RFC3339, v.UpdatedAt); _err != nil {
		return fmt.Errorf("updatedAt: not a valid RFC 3339 datetime")
	}
	return nil
}

// Validate checks every field-level constraint declared on AuditTrail.
// Returns the first violation; nil when the value satisfies the contract.
func (v *AuditTrail) Validate() error {
	if _, _err := time.Parse(time.RFC3339, v.At); _err != nil {
		return fmt.Errorf("at: not a valid RFC 3339 datetime")
	}
	return nil
}

// Validate checks every field-level constraint declared on Money.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Money) Validate() error {
	if v.Amount < 0 {
		return fmt.Errorf("amount: below minimum 0")
	}
	if l := len(v.Currency); l < 3 || l > 3 {
		return fmt.Errorf("currency: length out of range [3, 3]")
	}
	return nil
}

// Validate checks every field-level constraint declared on Pagination.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Pagination) Validate() error {
	if v.Limit != nil && *v.Limit < 1 {
		return fmt.Errorf("limit: below minimum 1")
	}
	if v.Limit != nil && *v.Limit > 100 {
		return fmt.Errorf("limit: above maximum 100")
	}
	return nil
}

// Validate checks every field-level constraint declared on Email.
// Returns the first violation; nil when the value satisfies the contract.
func (v Email) Validate() error {
	if _, _err := mail.ParseAddress(string(v)); _err != nil {
		return fmt.Errorf("Email: not a valid email")
	}
	if len(string(v)) > 254 {
		return fmt.Errorf("Email: length greater than 254")
	}
	return nil
}

// Validate checks every field-level constraint declared on ID.
// Returns the first violation; nil when the value satisfies the contract.
func (v ID) Validate() error {
	if l := len(string(v)); l < 1 || l > 64 {
		return fmt.Errorf("ID: length out of range [1, 64]")
	}
	return nil
}

// Validate checks every field-level constraint declared on Severity.
// Returns the first violation; nil when the value satisfies the contract.
func (v Severity) Validate() error {
	switch v {
	case SeverityInfo, SeverityWarning, SeverityError, SeverityCritical:
	default:
		return fmt.Errorf("Severity: invalid Severity value")
	}
	return nil
}

// Validate checks every field-level constraint declared on AccessRevokedBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *AccessRevokedBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on ConflictErrBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *ConflictErrBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on NotFoundErrBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *NotFoundErrBody) Validate() error {
	if err := v.ID.Validate(); err != nil {
		return err
	}
	return nil
}
