// Code generated by craftgo. DO NOT EDIT.

package orderservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"
	"strconv"

	service "github.com/craftgodotdev/craftgo/example/ecommerce/internal/service/order-service"
	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/orders"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// FilterOrders returns the http.HandlerFunc for the
// GET FilterOrders endpoint.
func FilterOrders(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.FilterOrdersReq
		req.Status = types.OrderStatus(r.PathValue("status"))
		req.Method = types.PaymentMethod(r.URL.Query().Get("method"))
		if _v := r.URL.Query().Get("limit"); _v != "" {
			_n, _err := strconv.ParseInt(_v, 10, 64)
			if _err != nil {
				http.Error(w, "limit"+": invalid int value: "+_err.Error(), http.StatusBadRequest)
				return
			}
			req.Limit = int(_n)
		}
		if _v := r.URL.Query().Get("maxPrice"); _v != "" {
			_n, _err := strconv.ParseInt(_v, 10, 64)
			if _err != nil {
				http.Error(w, "maxPrice"+": invalid int value: "+_err.Error(), http.StatusBadRequest)
				return
			}
			req.MaxPrice = int(_n)
		}
		if _v := r.Header.Get("idemKey"); _v != "" {
			req.IdemKey = &_v
		}
		if _v := r.Header.Get("retryAfter"); _v != "" {
			_n, _err := strconv.ParseInt(_v, 10, 64)
			if _err != nil {
				http.Error(w, "retryAfter"+": invalid int value: "+_err.Error(), http.StatusBadRequest)
				return
			}
			req.RetryAfter = int(_n)
		}
		if c, err := r.Cookie("lastSeen"); err == nil {
			if _v := c.Value; _v != "" {
				req.LastSeen = &_v
			}
		}
		if c, err := r.Cookie("tier"); err == nil {
			if _v := c.Value; _v != "" {
				_n, _err := strconv.ParseInt(_v, 10, 64)
				if _err != nil {
					http.Error(w, "tier"+": invalid int value: "+_err.Error(), http.StatusBadRequest)
					return
				}
				req.Tier = int(_n)
			}
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewFilterOrdersService(r.Context(), svcCtx)
		resp, err := l.FilterOrders(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
