// Code generated by craftgo. DO NOT EDIT.

package orderservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/example/ecommerce/internal/service/order-service"
	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/orders"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// ListOrders returns the http.HandlerFunc for the
// GET ListOrders endpoint.
func ListOrders(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.ListOrdersReq
		_q := r.URL.Query()
		if _v := _q.Get("cursor"); _v != "" {
			req.Cursor = &_v
		}
		if !server.BindValue(w, r, "limit", "int", _q.Get("limit"), &req.Limit, server.ParseSigned[int]) {
			return
		}
		if _v := _q.Get("status"); _v != "" {
			_w := types.OrderStatus(_v)
			req.Status = &_w
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewListOrdersService(r.Context(), svcCtx)
		resp, err := l.ListOrders(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
