// Code generated by craftgo. DO NOT EDIT.

package combineservice

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/combine-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/combine"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ValidateNum returns the http.HandlerFunc for the
// POST ValidateNum endpoint.
func ValidateNum(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.PairsNum
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewValidateNumService(r.Context(), svcCtx)
		resp, err := l.ValidateNum(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
