// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package services

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/services"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/shared"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// DeleteAccountService runs AccountService.DeleteAccount for one request.
type DeleteAccountService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewDeleteAccountService binds DeleteAccountService to ctx; its Logger carries ctx's trace ids.
func NewDeleteAccountService(ctx context.Context, svcCtx *svccontext.ServiceContext) *DeleteAccountService {
	return &DeleteAccountService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Delete an account - admin-only. Chain: [RateLimit, BasicAuth, Audit].
//
// DeleteAccount implements AccountService.DeleteAccount.
func (l *DeleteAccountService) DeleteAccount(req *types.DeleteAccountReq) (*shared.ID, error) {
	// TODO: implement
	return nil, nil
}
