// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package services

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/shared"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ResetService runs AccountService.Reset for one request.
type ResetService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewResetService binds ResetService to ctx; its Logger carries ctx's trace ids.
func NewResetService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ResetService {
	return &ResetService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Hard reset - bypasses BasicAuth, uses its own minimal chain.
//
// Reset implements AccountService.Reset.
func (l *ResetService) Reset() (*shared.ID, error) {
	// TODO: implement
	return nil, nil
}
