// Code generated by craftgo. DO NOT EDIT.

package shared

// ErrCodeInternalErr is the canonical machine-readable code for InternalErr.
const ErrCodeInternalErr = "INTERNAL_ERR"

// InternalErr is the typed Internal error generated for `InternalErr`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type InternalErr struct {
	code    string
	message string
}

// NewInternalErr constructs InternalErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewInternalErr() *InternalErr {
	return &InternalErr{
		code:    ErrCodeInternalErr,
		message: "Internal server error",
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *InternalErr) Error() string { return e.message }

// ErrCode returns the machine-readable error code bound to the type.
// The transport layer reads this via an `interface{ ErrCode() string }`
// assertion when assembling the fallback JSON envelope for errors
// whose body would otherwise marshal to `{}`. The accessor is named
// `ErrCode` (not `Code`) so it does not shadow a user-declared
// `code <type>` field promoted from the embedded body struct.
func (e *InternalErr) ErrCode() string { return e.code }

// HTTPStatus returns the HTTP status code associated with the Internal category.
func (e *InternalErr) HTTPStatus() int { return 500 }

// ErrCodeMaintenanceWindow is the canonical machine-readable code for MaintenanceWindowErr.
const ErrCodeMaintenanceWindow = "MAINTENANCE_WINDOW"

// MaintenanceWindowBody is the wire-shape payload declared at design time for MaintenanceWindowErr.
// User code instantiates this struct and hands it to NewMaintenanceWindowErr; the
// framework wraps it with the type-bound code / message metadata.
type MaintenanceWindowBody struct {
	Reason         MaintenanceReason `json:"reason"`
	EstimatedEndAt string            `json:"estimatedEndAt"`
}

// MaintenanceWindowErr is the typed ServiceUnavailable error generated for `MaintenanceWindow`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type MaintenanceWindowErr struct {
	code    string
	message string
	MaintenanceWindowBody
}

// NewMaintenanceWindowErr constructs MaintenanceWindowErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewMaintenanceWindowErr(body MaintenanceWindowBody) *MaintenanceWindowErr {
	return &MaintenanceWindowErr{
		code:                  ErrCodeMaintenanceWindow,
		message:               "Service unavailable",
		MaintenanceWindowBody: body,
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *MaintenanceWindowErr) Error() string { return e.message }

// ErrCode returns the machine-readable error code bound to the type.
// The transport layer reads this via an `interface{ ErrCode() string }`
// assertion when assembling the fallback JSON envelope for errors
// whose body would otherwise marshal to `{}`. The accessor is named
// `ErrCode` (not `Code`) so it does not shadow a user-declared
// `code <type>` field promoted from the embedded body struct.
func (e *MaintenanceWindowErr) ErrCode() string { return e.code }

// HTTPStatus returns the HTTP status code associated with the ServiceUnavailable category.
func (e *MaintenanceWindowErr) HTTPStatus() int { return 503 }

// ErrCodeRateLimitedErr is the canonical machine-readable code for RateLimitedErr.
const ErrCodeRateLimitedErr = "RATE_LIMITED_ERR"

// RateLimitedErrBody is the wire-shape payload declared at design time for RateLimitedErr.
// User code instantiates this struct and hands it to NewRateLimitedErr; the
// framework wraps it with the type-bound code / message metadata.
type RateLimitedErrBody struct {
	RetryAfter int     `json:"retryAfter"`
	Bucket     *string `json:"bucket,omitempty"`
}

// RateLimitedErr is the typed TooManyRequests error generated for `RateLimitedErr`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type RateLimitedErr struct {
	code    string
	message string
	RateLimitedErrBody
}

// NewRateLimitedErr constructs RateLimitedErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewRateLimitedErr(body RateLimitedErrBody) *RateLimitedErr {
	return &RateLimitedErr{
		code:               ErrCodeRateLimitedErr,
		message:            "Too many requests",
		RateLimitedErrBody: body,
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *RateLimitedErr) Error() string { return e.message }

// ErrCode returns the machine-readable error code bound to the type.
// The transport layer reads this via an `interface{ ErrCode() string }`
// assertion when assembling the fallback JSON envelope for errors
// whose body would otherwise marshal to `{}`. The accessor is named
// `ErrCode` (not `Code`) so it does not shadow a user-declared
// `code <type>` field promoted from the embedded body struct.
func (e *RateLimitedErr) ErrCode() string { return e.code }

// HTTPStatus returns the HTTP status code associated with the TooManyRequests category.
func (e *RateLimitedErr) HTTPStatus() int { return 429 }

// ErrCodeUnauthorizedErr is the canonical machine-readable code for UnauthorizedErr.
const ErrCodeUnauthorizedErr = "UNAUTHORIZED_ERR"

// UnauthorizedErrBody is the wire-shape payload declared at design time for UnauthorizedErr.
// User code instantiates this struct and hands it to NewUnauthorizedErr; the
// framework wraps it with the type-bound code / message metadata.
type UnauthorizedErrBody struct {
	Code *string `json:"code,omitempty"`
}

// UnauthorizedErr is the typed Unauthorized error generated for `UnauthorizedErr`.
// The unexported `code` and `message` fields hold the type-bound
// metadata populated by the constructor. Because they are unexported,
// json.Marshal omits them from the wire payload - clients see only
// the embedded body shape (or `{}` when no body was declared).
type UnauthorizedErr struct {
	code    string
	message string
	UnauthorizedErrBody
}

// NewUnauthorizedErr constructs UnauthorizedErr with the framework metadata baked in.
// `code` and `message` are bound to the type and not exposed as
// constructor parameters; only the body struct varies per instance.
func NewUnauthorizedErr(body UnauthorizedErrBody) *UnauthorizedErr {
	return &UnauthorizedErr{
		code:                ErrCodeUnauthorizedErr,
		message:             "Unauthorized",
		UnauthorizedErrBody: body,
	}
}

// Error implements the standard error interface and returns the
// category-default message bound to the type.
func (e *UnauthorizedErr) Error() string { return e.message }

// ErrCode returns the machine-readable error code bound to the type.
// The transport layer reads this via an `interface{ ErrCode() string }`
// assertion when assembling the fallback JSON envelope for errors
// whose body would otherwise marshal to `{}`. The accessor is named
// `ErrCode` (not `Code`) so it does not shadow a user-declared
// `code <type>` field promoted from the embedded body struct.
func (e *UnauthorizedErr) ErrCode() string { return e.code }

// HTTPStatus returns the HTTP status code associated with the Unauthorized category.
func (e *UnauthorizedErr) HTTPStatus() int { return 401 }
