// Code generated by craftgo. DO NOT EDIT.

package shared

// FillEmpty sets each required list, map or bytes value below v left nil to an empty one, so
// v encodes as [] or {} there, and reports whether it set a value v holds itself. It writes to
// no map: a copy holding the changed values takes the map's place. Past fillDepth values deep
// it stops at once, reporting stopped.
func (v *Envelope[T]) FillEmpty(depth int) (changed, stopped bool) {
	if v == nil {
		return false, false
	}
	if depth > fillDepth {
		return false, true
	}
	if f, ok := any(&v.Data).(interface{ FillEmpty(int) (bool, bool) }); ok {
		if c, s := f.FillEmpty(depth + 1); s {
			return changed, true
		} else if c {
			changed = true
		}
	}
	return changed, false
}

// FillEmpty sets each required list, map or bytes value below v left nil to an empty one, so
// v encodes as [] or {} there, and reports whether it set a value v holds itself. It writes to
// no map: a copy holding the changed values takes the map's place. Past fillDepth values deep
// it stops at once, reporting stopped.
func (v *Page[T]) FillEmpty(depth int) (changed, stopped bool) {
	if v == nil {
		return false, false
	}
	if depth > fillDepth {
		return false, true
	}
	if emptySlice(&v.Items) {
		changed = true
	}
	for i0 := range v.Items {
		if f, ok := any(&v.Items[i0]).(interface{ FillEmpty(int) (bool, bool) }); ok {
			if _, s := f.FillEmpty(depth + 1); s {
				return changed, true
			}
		}
	}
	return changed, false
}

// FillEmpty sets each required list, map or bytes value below v left nil to an empty one, so
// v encodes as [] or {} there, and reports whether it set a value v holds itself. It writes to
// no map: a copy holding the changed values takes the map's place. Past fillDepth values deep
// it stops at once, reporting stopped.
func (v *Result[T, E]) FillEmpty(depth int) (changed, stopped bool) {
	if v == nil {
		return false, false
	}
	if depth > fillDepth {
		return false, true
	}
	if v.Ok != nil {
		if f, ok := any(v.Ok).(interface{ FillEmpty(int) (bool, bool) }); ok {
			if _, s := f.FillEmpty(depth + 1); s {
				return changed, true
			}
		}
	}
	if v.Err != nil {
		if f, ok := any(v.Err).(interface{ FillEmpty(int) (bool, bool) }); ok {
			if _, s := f.FillEmpty(depth + 1); s {
				return changed, true
			}
		}
	}
	return changed, false
}

// fillDepth is how deep FillEmpty enters nested values, as deep as encoding/json decodes: only
// a cycle, or data no Go client could decode, goes further.
const fillDepth = 10000

// emptySlice sets *s to an empty slice when it is nil, and reports whether it did.
func emptySlice[S ~[]E, E any](s *S) bool {
	if *s != nil {
		return false
	}
	*s = S{}
	return true
}
