// Code generated by craftgo. DO NOT EDIT.

package transport

import (
	"context"

	craftevents "github.com/craftgodotdev/craftgo/pkg/events"

	activityserviceevents "github.com/craftgodotdev/craftgo/example/taskflow/internal/events/activity_service"

	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// SubscribeAll registers every consumer the design declares, the way
// RegisterAll wires every handler. Each service's subscriptions are built
// by its own event package from the handler set in this package, so the
// decode-validate-dispatch rule is spelled once, in the contract.
// Delivery runs until ctx is cancelled.
//
// It refuses rather than subscribing when a consume middleware the design
// applies has not been wired: a nil one is skipped, so the design's
// guarantee would simply be absent.
func SubscribeAll(ctx context.Context, bus *craftevents.Bus, svcCtx *svccontext.ServiceContext) error {
	var subs []craftevents.Subscription
	subs = append(subs, activityserviceevents.Subscriptions(bus, NewActivityServiceConsumers(svcCtx))...)
	return bus.SubscribeAll(ctx, subs)
}
