// Code generated by craftgo. DO NOT EDIT.

package transport

import (
	"context"

	craftevents "github.com/craftgodotdev/craftgo/pkg/events"

	activityserviceevents "github.com/craftgodotdev/craftgo/example/taskflow/internal/events/activity_service"

	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// SubscribeAll registers every consumer the design declares, the way
// RegisterAll wires every handler. Delivery runs until ctx is cancelled.
// It refuses when a consume middleware the design applies is not wired:
// a nil one would be skipped, and the guarantee silently absent.
func SubscribeAll(ctx context.Context, bus *craftevents.Bus, svcCtx *svccontext.ServiceContext) error {
	var subs []craftevents.Subscription
	subs = append(subs, activityserviceevents.Subscriptions(bus, NewActivityServiceConsumers(svcCtx))...)
	return bus.SubscribeAll(ctx, subs)
}
