// Code generated by craftgo. DO NOT EDIT.

package collections

import (
	"fmt"
	"net/mail"
	"regexp"
	"unicode/utf8"
)

// Pattern regexes compile ONCE at package init so Validate() calls
// reference the precompiled var instead of recompiling per request.
// The pattern is rendered via %q (Go-quoted) rather than a raw-string
// literal so regexes containing a backtick, backslash, or quote still
// produce compilable Go - a raw `...` literal would break on a backtick.
var (
	_pattern0 = regexp.MustCompile("^[a-z-]+$")
)

// Validate checks every field-level constraint declared on Address.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Address) Validate() error {
	if l := utf8.RuneCountInString(v.Street); l < 1 || l > 200 {
		return fmt.Errorf("street: length out of range [1, 200]")
	}
	if l := utf8.RuneCountInString(v.City); l < 1 || l > 100 {
		return fmt.Errorf("city: length out of range [1, 100]")
	}
	return nil
}

// Validate checks every field-level constraint declared on Arr_BoundsBasic.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_BoundsBasic) Validate() error {
	if len(v.Tags) < 1 {
		return fmt.Errorf("tags: minItems 1")
	}
	if len(v.Tags) > 10 {
		return fmt.Errorf("tags: maxItems 10")
	}
	{
		seen := make(map[string]struct{}, len(v.Tags))
		for _, item := range v.Tags {
			if _, dup := seen[item]; dup {
				return fmt.Errorf("tags: items must be unique")
			}
			seen[item] = struct{}{}
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Arr_EmptyExact.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_EmptyExact) Validate() error {
	if len(v.AlwaysEmpty) > 0 {
		return fmt.Errorf("always_empty: maxItems 0")
	}
	return nil
}

// Validate checks every field-level constraint declared on Arr_MinZero.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_MinZero) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on Arr_OptionalBound.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_OptionalBound) Validate() error {
	if v.Tags != nil {
		if len(v.Tags) < 1 {
			return fmt.Errorf("tags: minItems 1")
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Arr_PlainInts.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_PlainInts) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on Arr_PlainStrings.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_PlainStrings) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on Arr_Tag2D.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_Tag2D) Validate() error {
	for i0 := range v.Grid {
		for i1 := range v.Grid[i0] {
			if err := v.Grid[i0][i1].Validate(); err != nil {
				return fmt.Errorf("grid: %w", err)
			}
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Arr_Tag2DOptional.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_Tag2DOptional) Validate() error {
	for i0 := range v.Grid {
		for i1 := range v.Grid[i0] {
			if err := v.Grid[i0][i1].Validate(); err != nil {
				return fmt.Errorf("grid: %w", err)
			}
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Arr_Tag3D.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_Tag3D) Validate() error {
	for i0 := range v.Cube {
		for i1 := range v.Cube[i0] {
			for i2 := range v.Cube[i0][i1] {
				if err := v.Cube[i0][i1][i2].Validate(); err != nil {
					return fmt.Errorf("cube: %w", err)
				}
			}
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Arr_TagSlice.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Arr_TagSlice) Validate() error {
	if len(v.Tags) < 1 {
		return fmt.Errorf("tags: minItems 1")
	}
	if len(v.Tags) > 10 {
		return fmt.Errorf("tags: maxItems 10")
	}
	{
		seen := make(map[Tag]struct{}, len(v.Tags))
		for _, item := range v.Tags {
			if _, dup := seen[item]; dup {
				return fmt.Errorf("tags: items must be unique")
			}
			seen[item] = struct{}{}
		}
	}
	for i0 := range v.Tags {
		if err := v.Tags[i0].Validate(); err != nil {
			return fmt.Errorf("tags: %w", err)
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Map_ArrayValue.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Map_ArrayValue) Validate() error {
	for _, val := range v.Buckets {
		for i0 := range val {
			if err := val[i0].Validate(); err != nil {
				return fmt.Errorf("buckets: %w", err)
			}
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Map_Bounds.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Map_Bounds) Validate() error {
	if len(v.Counts) < 1 {
		return fmt.Errorf("counts: minItems 1")
	}
	if len(v.Counts) > 100 {
		return fmt.Errorf("counts: maxItems 100")
	}
	return nil
}

// Validate checks every field-level constraint declared on Map_KeyAndValue.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Map_KeyAndValue) Validate() error {
	for key, val := range v.Index {
		if err := key.Validate(); err != nil {
			return fmt.Errorf("index: %w", err)
		}
		if err := val.Validate(); err != nil {
			return fmt.Errorf("index: %w", err)
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Map_Optional.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Map_Optional) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on Map_Plain.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Map_Plain) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on Map_ScalarValue.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Map_ScalarValue) Validate() error {
	for _, val := range v.Labels {
		if err := val.Validate(); err != nil {
			return fmt.Errorf("labels: %w", err)
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Map_StructAddress.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Map_StructAddress) Validate() error {
	for _, val := range v.Addresses {
		if err := val.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on Map_StructValue.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Map_StructValue) Validate() error {
	for _, val := range v.Users {
		if err := val.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on User.
// Returns the first violation; nil when the value satisfies the contract.
func (v *User) Validate() error {
	if l := utf8.RuneCountInString(v.Name); l < 1 || l > 80 {
		return fmt.Errorf("name: length out of range [1, 80]")
	}
	if err := v.Email.Validate(); err != nil {
		return fmt.Errorf("email: %w", err)
	}
	return nil
}

// Validate checks every field-level constraint declared on Email.
// Returns the first violation; nil when the value satisfies the contract.
func (v Email) Validate() error {
	if _, _err := mail.ParseAddress(string(v)); _err != nil {
		return fmt.Errorf("not a valid email")
	}
	if utf8.RuneCountInString(string(v)) > 254 {
		return fmt.Errorf("length greater than 254")
	}
	return nil
}

// Validate checks every field-level constraint declared on NonEmptyID.
// Returns the first violation; nil when the value satisfies the contract.
func (v NonEmptyID) Validate() error {
	if utf8.RuneCountInString(string(v)) < 1 {
		return fmt.Errorf("length less than 1")
	}
	if utf8.RuneCountInString(string(v)) > 64 {
		return fmt.Errorf("length greater than 64")
	}
	return nil
}

// Validate checks every field-level constraint declared on Tag.
// Returns the first violation; nil when the value satisfies the contract.
func (v Tag) Validate() error {
	if utf8.RuneCountInString(string(v)) < 1 {
		return fmt.Errorf("length less than 1")
	}
	if utf8.RuneCountInString(string(v)) > 20 {
		return fmt.Errorf("length greater than 20")
	}
	if !_pattern0.MatchString(string(v)) {
		return fmt.Errorf("does not match pattern")
	}
	return nil
}
