// Code generated by craftgo. DO NOT EDIT.

package prefixvar

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/tenant_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Export a tenant's items in a format logic picks. Logic reads the raw request; the document declares tenantID and format as path parameters.
//
// ExportTenantItems returns the http.HandlerFunc for the
// GET ExportTenantItems passthrough endpoint. The framework stays
// out of the way: logic receives the raw http.ResponseWriter and
// *http.Request and writes the response directly.
func ExportTenantItems(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewExportTenantItemsService(r.Context(), svcCtx)
		if err := l.ExportTenantItems(w, r); err != nil {
			server.WriteError(w, r, err)
			return
		}
	}
}
