// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package regressionbatch2

import (
	"context"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/regression"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// EchoFmtService carries the per-request state for the
// EchoFmt endpoint of RegressionBatch2. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type EchoFmtService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewEchoFmtService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewEchoFmtService(ctx context.Context, svcCtx *svccontext.ServiceContext) *EchoFmtService {
	return &EchoFmtService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// EchoFmt is the service entry point. Replace the
// TODO with the real implementation.
func (l *EchoFmtService) EchoFmt(req *types.Rg2Fmt) (*types.Rg2Fmt, error) {
	// TODO: implement
	return nil, nil
}
