// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package emptylists

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/emptylists"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// GetDeepService runs EmptyLists.GetDeep for one request.
type GetDeepService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewGetDeepService binds GetDeepService to ctx; its Logger carries ctx's trace ids.
func NewGetDeepService(ctx context.Context, svcCtx *svccontext.ServiceContext) *GetDeepService {
	return &GetDeepService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Answers a Chain whose first node nests 1500 deep, with no cycle.
//
// GetDeep implements EmptyLists.GetDeep.
func (l *GetDeepService) GetDeep() (*types.Chain, error) {
	c := &types.Chain{}
	cur := &c.First
	for range 1500 {
		cur.Next = &types.Node{}
		cur = cur.Next
	}
	return c, nil
}
