// Code generated by craftgo. DO NOT EDIT.

package todoservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/example/todo/internal/service/todo-service"
	types "github.com/craftgodotdev/craftgo/example/todo/internal/types/todos"
	"github.com/craftgodotdev/craftgo/example/todo/svccontext"
)

// CreateTodo returns the http.HandlerFunc for the
// POST CreateTodo endpoint.
func CreateTodo(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.CreateTodoReq
		{
			__d := types.TodoPriorityMedium
			req.Priority = &__d
		}
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewCreateTodoService(r.Context(), svcCtx)
		resp, err := l.CreateTodo(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
