// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package media

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/example/upload/internal/types/media"
	"github.com/craftgodotdev/craftgo/example/upload/svccontext"
)

// UploadAttachmentService runs MediaService.UploadAttachment for one request.
type UploadAttachmentService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewUploadAttachmentService binds UploadAttachmentService to ctx; its Logger carries ctx's trace ids.
func NewUploadAttachmentService(ctx context.Context, svcCtx *svccontext.ServiceContext) *UploadAttachmentService {
	return &UploadAttachmentService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Attach a small blob to a note (tight 500KB cap).
//
// UploadAttachment implements MediaService.UploadAttachment.
func (l *UploadAttachmentService) UploadAttachment(req *types.UploadAttachmentReq) (*types.UploadResult, error) {
	return storeUpload(l.svcCtx.Store, req.Blob)
}
