// Code generated by craftgo. DO NOT EDIT.

package admininventoryservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	transport "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/transport/admin-inventory-service"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// RegisterRoutes wires every AdminInventoryService endpoint onto srv. Patterns
// use the Go 1.22 method-prefixed form so VERB and path match together;
// service prefix and OpenAPI basePath are baked in. Methods declaring
// `@middlewares(...)` are wrapped via the corresponding fields on
// ServiceContext (embedded Middlewares struct), so no runtime name
// lookup is required - the values come pre-wired.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api/admin/inventory/health", transport.Health(svcCtx))
	srv.Handle("GET /api/admin/inventory", transport.ListItems(svcCtx), svcCtx.AuthRequired)
	srv.Handle("POST /api/admin/inventory/{itemId}/promote", transport.PromoteItem(svcCtx), svcCtx.AuthRequired)
}
