// Code generated by craftgo. DO NOT EDIT.

package design

import (
	"fmt"
	"regexp"
)

// Pattern regexes compile ONCE at package init so Validate() calls
// reference the precompiled var instead of recompiling per request.
// The pattern is rendered via %q (Go-quoted) rather than a raw-string
// literal so regexes containing a backtick, backslash, or quote still
// produce compilable Go - a raw `...` literal would break on a backtick.
var (
	_pattern0 = regexp.MustCompile("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")
)

// Validate checks every field-level constraint declared on Address.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Address) Validate() error {
	if l := len(v.Street); l < 1 || l > 200 {
		return fmt.Errorf("street: length out of range [1, 200]")
	}
	if l := len(v.City); l < 1 || l > 100 {
		return fmt.Errorf("city: length out of range [1, 100]")
	}
	if l := len(v.Country); l < 2 || l > 2 {
		return fmt.Errorf("country: length out of range [2, 2]")
	}
	if v.Coords != nil {
		if err := v.Coords.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on ContactInfo.
// Returns the first violation; nil when the value satisfies the contract.
func (v *ContactInfo) Validate() error {
	if !_pattern0.MatchString(v.Email) {
		return fmt.Errorf("email: does not match pattern")
	}
	if v.Phone != nil && len(*v.Phone) < 7 {
		return fmt.Errorf("phone: length less than 7")
	}
	if v.Phone != nil && len(*v.Phone) > 20 {
		return fmt.Errorf("phone: length greater than 20")
	}
	return nil
}

// Validate checks every field-level constraint declared on Coords.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Coords) Validate() error {
	if v.Lat < -90 || v.Lat > 90 {
		return fmt.Errorf("lat: out of range [-90, 90]")
	}
	if v.Lng < -180 || v.Lng > 180 {
		return fmt.Errorf("lng: out of range [-180, 180]")
	}
	return nil
}

// Validate checks every field-level constraint declared on CreateProfileReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *CreateProfileReq) Validate() error {
	if l := len(v.DisplayName); l < 1 || l > 50 {
		return fmt.Errorf("displayName: length out of range [1, 50]")
	}
	if err := v.Contacts.Validate(); err != nil {
		return err
	}
	if len(v.Addresses) < 1 {
		return fmt.Errorf("addresses: minItems 1")
	}
	if len(v.Addresses) > 5 {
		return fmt.Errorf("addresses: maxItems 5")
	}
	for i0 := range v.Addresses {
		if err := v.Addresses[i0].Validate(); err != nil {
			return err
		}
	}
	if len(v.Tags) > 10 {
		return fmt.Errorf("tags: maxItems 10")
	}
	return nil
}

// Validate checks every field-level constraint declared on GetProfileReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *GetProfileReq) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on ListProfilesResp.
// Returns the first violation; nil when the value satisfies the contract.
func (v *ListProfilesResp) Validate() error {
	for i0 := range v.Items {
		if err := v.Items[i0].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on PatchProfileReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *PatchProfileReq) Validate() error {
	if l := len(v.DisplayName); l < 1 || l > 50 {
		return fmt.Errorf("displayName: length out of range [1, 50]")
	}
	return nil
}

// Validate checks every field-level constraint declared on PatchProfileResp.
// Returns the first violation; nil when the value satisfies the contract.
func (v *PatchProfileResp) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on Profile.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Profile) Validate() error {
	if l := len(v.DisplayName); l < 1 || l > 50 {
		return fmt.Errorf("displayName: length out of range [1, 50]")
	}
	if err := v.Contacts.Validate(); err != nil {
		return err
	}
	if len(v.Addresses) < 1 {
		return fmt.Errorf("addresses: minItems 1")
	}
	if len(v.Addresses) > 5 {
		return fmt.Errorf("addresses: maxItems 5")
	}
	for i0 := range v.Addresses {
		if err := v.Addresses[i0].Validate(); err != nil {
			return err
		}
	}
	if len(v.Tags) > 10 {
		return fmt.Errorf("tags: maxItems 10")
	}
	return nil
}

// Validate checks every field-level constraint declared on DuplicateEmailBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *DuplicateEmailBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on InsufficientPermissionsBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *InsufficientPermissionsBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on ProfileValidationFailedBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *ProfileValidationFailedBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on RateLimitedBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *RateLimitedBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on StaleVersionBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *StaleVersionBody) Validate() error {
	return nil
}
