// Code generated by craftgo. DO NOT EDIT.

package services

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/secured_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Public status page - no auth or rate limit, only the block's Audit.
//
// Status returns the GET Status handler.
func Status(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewStatusService(r.Context(), svcCtx)
		resp, err := l.Status()
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusOK, resp)
	}
}
