// Code generated by craftgo. DO NOT EDIT.

package adminservice

import (
	"encoding/json"
	"net/http"

	service "github.com/dropship-dev/craftgo/tests/e2e/complex/internal/service/admin-service"
	"github.com/dropship-dev/craftgo/tests/e2e/complex/svccontext"
)

// DashboardStats reuses ListProfilesResp as a minimal stat payload.
// DashboardStats returns the http.HandlerFunc for the
// GET DashboardStats endpoint.
func DashboardStats(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewDashboardStatsService(r.Context(), svcCtx)
		resp, err := l.DashboardStats()
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
