// Code generated by craftgo. DO NOT EDIT.

package shared

import (
	"fmt"
	"regexp"
)

// Validate checks every field-level constraint declared on AuditEntry.
// Returns the first violation; nil when the value satisfies the contract.
func (v *AuditEntry) Validate() error {
	if l := len(v.EntityType); l < 1 || l > 32 {
		return fmt.Errorf("entityType: length out of range [1, 32]")
	}
	if l := len(v.EntityID); l < 1 || l > 128 {
		return fmt.Errorf("entityId: length out of range [1, 128]")
	}
	if !regexp.MustCompile(`^[a-z]+$`).MatchString(v.Action) {
		return fmt.Errorf("action: does not match pattern")
	}
	if v.Tags == nil {
		return fmt.Errorf("tags: required")
	}
	if len(v.Tags) > 20 {
		return fmt.Errorf("tags: maxItems 20")
	}
	{
		seen := make(map[any]struct{}, len(v.Tags))
		for _, item := range v.Tags {
			if _, dup := seen[item]; dup {
				return fmt.Errorf("tags: items must be unique")
			}
			seen[item] = struct{}{}
		}
	}
	if !regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`).MatchString(v.Uuid) {
		return fmt.Errorf("uuid: not a valid UUID")
	}
	return nil
}

// Validate checks every field-level constraint declared on OkResp.
// Returns the first violation; nil when the value satisfies the contract.
func (v *OkResp) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on Pagination.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Pagination) Validate() error {
	if v.Limit < 0 {
		return fmt.Errorf("limit: below minimum 0")
	}
	if v.Limit > 100 {
		return fmt.Errorf("limit: above maximum 100")
	}
	return nil
}

// Validate checks every field-level constraint declared on PluginConfig.
// Returns the first violation; nil when the value satisfies the contract.
func (v *PluginConfig) Validate() error {
	if l := len(v.PluginID); l < 1 || l > 64 {
		return fmt.Errorf("pluginId: length out of range [1, 64]")
	}
	if v.Settings == nil {
		return fmt.Errorf("settings: required")
	}
	if v.Version < 1 {
		return fmt.Errorf("version: below minimum 1")
	}
	return nil
}

// Validate checks every field-level constraint declared on WebhookEvent.
// Returns the first violation; nil when the value satisfies the contract.
func (v *WebhookEvent) Validate() error {
	if !regexp.MustCompile(`^[a-z]+(\.[a-z]+)+$`).MatchString(v.EventType) {
		return fmt.Errorf("eventType: does not match pattern")
	}
	if len(v.EventType) > 64 {
		return fmt.Errorf("eventType: length greater than 64")
	}
	if l := len(v.DeliveryID); l < 1 || l > 128 {
		return fmt.Errorf("deliveryId: length out of range [1, 128]")
	}
	if v.Data == nil {
		return fmt.Errorf("data: required")
	}
	return nil
}
