// Code generated by craftgo. DO NOT EDIT.

package projectservice

import (
	"encoding/json"
	"github.com/dropship-dev/craftgo/pkg/server"
	"net/http"
	"strconv"

	logic "github.com/dropship-dev/craftgo/example/internal/logic/project-service"
	types "github.com/dropship-dev/craftgo/example/internal/types/projects"
	"github.com/dropship-dev/craftgo/example/svccontext"
)

// ListProjectsHandler returns the http.HandlerFunc for the
// GET ListProjects endpoint.
func ListProjectsHandler(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.ListProjectsReq
		if _v := r.URL.Query().Get("cursor"); _v != "" {
			req.Cursor = &_v
		}
		if _v := r.URL.Query().Get("limit"); _v != "" {
			_n, _err := strconv.ParseInt(_v, 10, 64)
			if _err != nil {
				http.Error(w, "limit"+": invalid int value: "+_err.Error(), http.StatusBadRequest)
				return
			}
			req.Limit = int(_n)
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := logic.NewListProjectsLogic(r.Context(), svcCtx)
		resp, err := l.ListProjects(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
