// Code generated by craftgo. DO NOT EDIT.

package admin

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/taskflow/internal/service/admin"
	types "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/admin"
	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// CreateToken returns the http.HandlerFunc for the
// POST CreateToken endpoint.
func CreateToken(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.CreateTokenReq
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewCreateTokenService(r.Context(), svcCtx)
		resp, err := l.CreateToken(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
