// Code generated by craftgo. DO NOT EDIT.

package admin

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/taskflow/internal/service/admin"
	shared "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/shared"
	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// ListTokens returns the http.HandlerFunc for the
// GET ListTokens endpoint.
func ListTokens(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req shared.PageParams
		{
			__d := 20
			req.Limit = &__d
		}
		_q := r.URL.Query()
		if _v := _q.Get("cursor"); _v != "" {
			req.Cursor = &_v
		}
		if !server.BindValuePtr(w, r, "limit", "int", _q.Get("limit"), &req.Limit, server.ParseSigned[int]) {
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewListTokensService(r.Context(), svcCtx)
		resp, err := l.ListTokens(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
