// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package bindingsservice

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// HealthService carries the per-request state for the
// Health endpoint of BindingsService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type HealthService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewHealthService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewHealthService(ctx context.Context, svcCtx *svccontext.ServiceContext) *HealthService {
	return &HealthService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Health is the bodyless probe — no request type, no response
// type. Only the @errors declaration rides on the method line so
// the OpenAPI doc still lists the rate-limit envelope.
// Health is the service entry point. Replace the
// TODO with the real implementation.
func (l *HealthService) Health() error {
	// TODO: implement
	return nil
}
