// Code generated by craftgo. DO NOT EDIT.

package events

import (
	craftevents "github.com/craftgodotdev/craftgo/pkg/events"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/events"
)

// EnvelopedContract is the wire identity of Enveloped.
// Publisher and listener both address the contract by this value.
const EnvelopedContract = "events.Enveloped"

// Generic payload: the argument must survive into every target.
//
// Enveloped is the events.Enveloped contract.
// Enveloped.Publish(ctx, bus, payload) sends one; a listener registers
// Enveloped.Subscribe(bus, group, fn) on its own bus.
var Enveloped = craftevents.NewEvent[types.Envelope[types.ItemStocked]](EnvelopedContract, (*types.Envelope[types.ItemStocked]).Validate)

// ForgedContract is the wire identity of Forged.
// Publisher and listener both address the contract by this value.
const ForgedContract = "events.Forged"

// A second contract over the payload ItemStocked already uses, so a batch can mix two contracts of one package.
//
// Forged is the events.Forged contract.
// Forged.Publish(ctx, bus, payload) sends one; a listener registers
// Forged.Subscribe(bus, group, fn) on its own bus.
var Forged = craftevents.NewEvent[types.ItemStocked](ForgedContract, (*types.ItemStocked).Validate)

// ItemStockedContract is the wire identity of ItemStocked.
// Publisher and listener both address the contract by this value.
const ItemStockedContract = "events.ItemStocked"

// Stock arrived at a warehouse. Its sku rides in through the mixin.
//
// ItemStocked is the events.ItemStocked contract.
// ItemStocked.Publish(ctx, bus, payload) sends one; a listener registers
// ItemStocked.Subscribe(bus, group, fn) on its own bus.
var ItemStocked = craftevents.NewEvent[types.ItemStocked](ItemStockedContract, (*types.ItemStocked).Validate)

// ReconciledContract is the wire identity of Reconciled.
// Publisher and listener both address the contract by this value.
const ReconciledContract = "legacy.inventory.reconciled.v2"

// The wire name is fixed by a system outside this design.
//
// Reconciled is the legacy.inventory.reconciled.v2 contract.
// Reconciled.Publish(ctx, bus, payload) sends one; a listener registers
// Reconciled.Subscribe(bus, group, fn) on its own bus.
var Reconciled = craftevents.NewEvent[types.ItemStocked](ReconciledContract, (*types.ItemStocked).Validate)

// ShipmentDispatchedContract is the wire identity of ShipmentDispatched.
// Publisher and listener both address the contract by this value.
const ShipmentDispatchedContract = "events.ShipmentDispatched"

// A shipment left. Its id is a scalar over a string primitive.
//
// ShipmentDispatched is the events.ShipmentDispatched contract.
// ShipmentDispatched.Publish(ctx, bus, payload) sends one; a listener registers
// ShipmentDispatched.Subscribe(bus, group, fn) on its own bus.
var ShipmentDispatched = craftevents.NewEvent[types.ShipmentDispatched](ShipmentDispatchedContract, (*types.ShipmentDispatched).Validate)

// StocktakeStartedContract is the wire identity of StocktakeStarted.
// Publisher and listener both address the contract by this value.
const StocktakeStartedContract = "events.StocktakeStarted"

// Published without a key, so the transport places it where it likes.
//
// StocktakeStarted is the events.StocktakeStarted contract.
// StocktakeStarted.Publish(ctx, bus, payload) sends one; a listener registers
// StocktakeStarted.Subscribe(bus, group, fn) on its own bus.
var StocktakeStarted = craftevents.NewEvent[types.StocktakeStarted](StocktakeStartedContract, (*types.StocktakeStarted).Validate)

// TierPromotedContract is the wire identity of TierPromoted.
// Publisher and listener both address the contract by this value.
const TierPromotedContract = "events.TierPromoted"

// Carries an int-valued enum declared in another package.
//
// TierPromoted is the events.TierPromoted contract.
// TierPromoted.Publish(ctx, bus, payload) sends one; a listener registers
// TierPromoted.Subscribe(bus, group, fn) on its own bus.
var TierPromoted = craftevents.NewEvent[types.TierPromoted](TierPromotedContract, (*types.TierPromoted).Validate)

// WarehouseClosedContract is the wire identity of WarehouseClosed.
// Publisher and listener both address the contract by this value.
const WarehouseClosedContract = "events.WarehouseClosed"

// Carries an int-valued enum declared in this package.
//
// WarehouseClosed is the events.WarehouseClosed contract.
// WarehouseClosed.Publish(ctx, bus, payload) sends one; a listener registers
// WarehouseClosed.Subscribe(bus, group, fn) on its own bus.
var WarehouseClosed = craftevents.NewEvent[types.WarehouseClosed](WarehouseClosedContract, (*types.WarehouseClosed).Validate)
