// Code generated by craftgo. DO NOT EDIT.

package services

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/ledger"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Lists the ledger's entries; its body component is LedgerEntryList3RespBody.
//
// EntryList returns the GET EntryList handler.
func EntryList(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewEntryListService(r.Context(), svcCtx)
		resp, err := l.EntryList()
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
