// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package eventsubs

import (
	"context"

	events "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/events"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// AuditReconciliationConsumer carries the per-message state for the AuditReconciliation
// consumer of NotificationService. The embedded log.Logger is pre-bound to the
// message context (trace_id / span_id).
type AuditReconciliationConsumer struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewAuditReconciliationConsumer constructs a fresh consumer instance bound to ctx.
func NewAuditReconciliationConsumer(ctx context.Context, svcCtx *svccontext.ServiceContext) *AuditReconciliationConsumer {
	return &AuditReconciliationConsumer{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// AuditReconciliation handles legacy.inventory.reconciled.v2, recording the payload so the fixture's
// round-trip test can assert on what reached logic.
func (l *AuditReconciliationConsumer) AuditReconciliation(payload *events.ItemStocked) error {
	l.svcCtx.Record("AuditReconciliation", payload)
	return nil
}
