// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package services

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/services"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// GetUserService runs UserService.GetUser for one request.
type GetUserService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewGetUserService binds GetUserService to ctx; its Logger carries ctx's trace ids.
func NewGetUserService(ctx context.Context, svcCtx *svccontext.ServiceContext) *GetUserService {
	return &GetUserService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// GetUser implements UserService.GetUser.
func (l *GetUserService) GetUser(req *types.GetUserReq) (*types.User, error) {
	// TODO: implement
	return nil, nil
}
