// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package services

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/services"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ListUsersService runs UserService.ListUsers for one request.
type ListUsersService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewListUsersService binds ListUsersService to ctx; its Logger carries ctx's trace ids.
func NewListUsersService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ListUsersService {
	return &ListUsersService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// ListUsers implements UserService.ListUsers.
func (l *ListUsersService) ListUsers(req *types.ListUsersReq) (*types.ListUsersResp, error) {
	// TODO: implement
	return nil, nil
}
