// Code generated by craftgo. DO NOT EDIT.

package admin

import (
	"fmt"
	"regexp"
	"unicode/utf8"
)

// The regexes of the @pattern and @format checks, compiled once.
var (
	_pattern0 = regexp.MustCompile("^(read|write|admin)$")
)

// Validate returns the first constraint v violates, or nil.
func (v *AdminStats) Validate() error {
	if v.Projects < 0 {
		return fmt.Errorf("projects: below minimum 0")
	}
	if v.Tasks < 0 {
		return fmt.Errorf("tasks: below minimum 0")
	}
	if v.Attachments < 0 {
		return fmt.Errorf("attachments: below minimum 0")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *ApiToken) Validate() error {
	if err := v.ID.Validate(); err != nil {
		return fmt.Errorf("id: %w", err)
	}
	if l := utf8.RuneCountInString(v.Name); l < 1 || l > 80 {
		return fmt.Errorf("name: length out of range [1, 80]")
	}
	if utf8.RuneCountInString(v.Last4) != 4 {
		return fmt.Errorf("last4: length must be 4")
	}
	if err := v.Timestamps.Validate(); err != nil {
		return err
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *ApiTokenSecret) Validate() error {
	if err := v.ID.Validate(); err != nil {
		return fmt.Errorf("id: %w", err)
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *CreateTokenReq) Validate() error {
	if l := utf8.RuneCountInString(v.Name); l < 1 || l > 80 {
		return fmt.Errorf("name: length out of range [1, 80]")
	}
	if !_pattern0.MatchString(v.Scope) {
		return fmt.Errorf("scope: does not match pattern")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *RevokeTokenReq) Validate() error {
	if err := v.ID.Validate(); err != nil {
		return fmt.Errorf("id: %w", err)
	}
	return nil
}
