// Code generated by craftgo. DO NOT EDIT.

package numbers

import (
	"github.com/craftgodotdev/craftgo/pkg/server"

	transport "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/transport/numbers_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RegisterRoutes registers the NumbersService routes on srv.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("POST /api/numbers/counter", transport.AddCounter(svcCtx))
	srv.Handle("POST /api/numbers/unsigned", transport.AddUnsigned(svcCtx))
	srv.Handle("POST /api/numbers/price", transport.AddPrice(svcCtx))
	srv.Handle("POST /api/numbers/optional", transport.AddOptional(svcCtx))
	srv.Handle("POST /api/numbers/mixed", transport.AddMixed(svcCtx))
	srv.Handle("POST /api/numbers/exact", transport.AddExact(svcCtx))
	srv.Handle("POST /api/numbers/boundary", transport.AddBoundary(svcCtx))
	srv.Handle("POST /api/numbers/big-bounds", transport.EchoBigBounds(svcCtx))
	srv.Handle("POST /api/numbers/multiple-of", transport.EchoMultipleOf(svcCtx))
	srv.Handle("POST /api/numbers/big-multiple-of", transport.EchoBigMultipleOf(svcCtx))
}
