// Code generated by craftgo. DO NOT EDIT.

package todos

// Millis is a scalar over int used below for a non-string @header
// value (X-Response-Time); scalar-typed header fields format through
// their underlying primitive (strconv.Itoa).
type Millis int

// Tag is a scalar over string used as a request query filter. Its
// @length / @pattern validators are inherited by any field typed Tag,
// so a `@query`-bound Tag field is validated during req.Validate() and
// a malformed ?tag= value is rejected with 400 before the handler runs.
type Tag string

type CreateTodoReq struct {
	Title    string        `json:"title"`
	Notes    *string       `json:"notes,omitempty"`
	Status   TodoStatus    `json:"status"`
	Priority *TodoPriority `json:"priority,omitempty"`
	Tags     []string      `json:"tags,omitempty"`
}

type GetTodoReq struct {
	ID string `json:"-" path:"id"`
}

type ListTodosReq struct {
	Cursor *string     `json:"-" query:"cursor"`
	Limit  int         `json:"-" query:"limit"`
	Status *TodoStatus `json:"-" query:"status"`
	// tag is a scalar (Tag) filter bound from the query string. The
	// scalar's inherited @length / @pattern run during req.Validate(),
	// so `?tag=NOT_A_SLUG` returns 400 and never reaches the handler.
	Tag *Tag `json:"-" query:"tag"`
}

type OkResp struct {
	Ok bool `json:"ok"`
}

type Todo struct {
	ID        string        `json:"id"`
	Title     string        `json:"title"`
	Notes     *string       `json:"notes,omitempty"`
	Status    TodoStatus    `json:"status"`
	Priority  *TodoPriority `json:"priority,omitempty"`
	Tags      []string      `json:"tags"`
	CreatedAt string        `json:"createdAt"`
}

type TodoList struct {
	Items  []Todo  `json:"items"`
	Cursor *string `json:"cursor,omitempty"`
	// total rides the X-Total-Count response header instead of the JSON
	// body - a non-string @header value the generated handler formats
	// with strconv.Itoa.
	Total int `json:"-" header:"X-Total-Count"`
	// tookMs is a scalar-typed (Millis = int) header: it resolves to its
	// underlying primitive and formats the same as a plain int.
	TookMs Millis `json:"-" header:"X-Response-Time"`
}

type UpdateTodoReq struct {
	ID       string        `json:"-" path:"id"`
	Title    *string       `json:"title,omitempty"`
	Notes    *string       `json:"notes,omitempty"`
	Status   *TodoStatus   `json:"status,omitempty"`
	Priority *TodoPriority `json:"priority,omitempty"`
}
