// Code generated by craftgo. DO NOT EDIT.

package todos

import (
	"fmt"
	"regexp"
	"time"
	"unicode/utf8"
)

// The regexes of the @pattern and @format checks, compiled once.
var (
	_pattern0 = regexp.MustCompile("^[a-z0-9-]+$")
)

// Validate returns the first constraint v violates, or nil.
func (v *CreateTodoReq) Validate() error {
	if l := utf8.RuneCountInString(v.Title); l < 1 || l > 200 {
		return fmt.Errorf("title: length out of range [1, 200]")
	}
	if v.Notes != nil && utf8.RuneCountInString(*v.Notes) > 2000 {
		return fmt.Errorf("notes: length greater than 2000")
	}
	if v.Status == "" {
		return fmt.Errorf("status: required")
	}
	if err := v.Status.Validate(); err != nil {
		return fmt.Errorf("status: %w", err)
	}
	if v.Priority != nil {
		if err := v.Priority.Validate(); err != nil {
			return fmt.Errorf("priority: %w", err)
		}
	}
	if v.Tags != nil {
		if len(v.Tags) > 10 {
			return fmt.Errorf("tags: maxItems 10")
		}
	}
	{
		seen := make(map[string]struct{}, len(v.Tags))
		for _, item := range v.Tags {
			if _, dup := seen[item]; dup {
				return fmt.Errorf("tags: items must be unique")
			}
			seen[item] = struct{}{}
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *GetTodoReq) Validate() error {
	if l := utf8.RuneCountInString(v.ID); l < 1 || l > 64 {
		return fmt.Errorf("id: length out of range [1, 64]")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *ListTodosReq) Validate() error {
	if v.Limit < 0 {
		return fmt.Errorf("limit: below minimum 0")
	}
	if v.Limit > 100 {
		return fmt.Errorf("limit: above maximum 100")
	}
	if v.Status != nil {
		if err := v.Status.Validate(); err != nil {
			return fmt.Errorf("status: %w", err)
		}
	}
	if v.Tag != nil {
		if err := v.Tag.Validate(); err != nil {
			return fmt.Errorf("tag: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *OkResp) Validate() error {
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *Todo) Validate() error {
	if l := utf8.RuneCountInString(v.ID); l < 1 || l > 64 {
		return fmt.Errorf("id: length out of range [1, 64]")
	}
	if l := utf8.RuneCountInString(v.Title); l < 1 || l > 200 {
		return fmt.Errorf("title: length out of range [1, 200]")
	}
	if v.Notes != nil && utf8.RuneCountInString(*v.Notes) > 2000 {
		return fmt.Errorf("notes: length greater than 2000")
	}
	if v.Status == "" {
		return fmt.Errorf("status: required")
	}
	if err := v.Status.Validate(); err != nil {
		return fmt.Errorf("status: %w", err)
	}
	if v.Priority != nil {
		if err := v.Priority.Validate(); err != nil {
			return fmt.Errorf("priority: %w", err)
		}
	}
	if len(v.Tags) > 10 {
		return fmt.Errorf("tags: maxItems 10")
	}
	{
		seen := make(map[string]struct{}, len(v.Tags))
		for _, item := range v.Tags {
			if _, dup := seen[item]; dup {
				return fmt.Errorf("tags: items must be unique")
			}
			seen[item] = struct{}{}
		}
	}
	if _, _err := time.Parse(time.RFC3339, v.CreatedAt); _err != nil {
		return fmt.Errorf("createdAt: not a valid RFC 3339 datetime")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *TodoList) Validate() error {
	for i0 := range v.Items {
		if err := v.Items[i0].Validate(); err != nil {
			return fmt.Errorf("items: %w", err)
		}
	}
	if err := v.TookMs.Validate(); err != nil {
		return fmt.Errorf("X-Response-Time: %w", err)
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v *UpdateTodoReq) Validate() error {
	if l := utf8.RuneCountInString(v.ID); l < 1 || l > 64 {
		return fmt.Errorf("id: length out of range [1, 64]")
	}
	if v.Title != nil {
		if l := utf8.RuneCountInString(*v.Title); l < 1 || l > 200 {
			return fmt.Errorf("title: length out of range [1, 200]")
		}
	}
	if v.Notes != nil && utf8.RuneCountInString(*v.Notes) > 2000 {
		return fmt.Errorf("notes: length greater than 2000")
	}
	if v.Status != nil {
		if err := v.Status.Validate(); err != nil {
			return fmt.Errorf("status: %w", err)
		}
	}
	if v.Priority != nil {
		if err := v.Priority.Validate(); err != nil {
			return fmt.Errorf("priority: %w", err)
		}
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v Millis) Validate() error {
	if int(v) < 0 {
		return fmt.Errorf("below minimum 0")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v Tag) Validate() error {
	if l := utf8.RuneCountInString(string(v)); l < 1 || l > 40 {
		return fmt.Errorf("length out of range [1, 40]")
	}
	if !_pattern0.MatchString(string(v)) {
		return fmt.Errorf("does not match pattern")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v TodoPriority) Validate() error {
	switch v {
	case TodoPriorityLow, TodoPriorityMedium, TodoPriorityHigh:
	default:
		return fmt.Errorf("must be one of [low medium high]")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v TodoStatus) Validate() error {
	switch v {
	case TodoStatusOpen, TodoStatusInProgress, TodoStatusDone:
	default:
		return fmt.Errorf("must be one of [open in_progress done]")
	}
	return nil
}
