// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

// Package config loads the runtime settings from config/config.yaml.
package config

import (
	"fmt"
	"os"
	"time"

	"github.com/craftgodotdev/craftgo/pkg/telemetry"
	"gopkg.in/yaml.v3"
)

// Config is the shape of `config/config.yaml`; the inlined telemetry.Config puts
// serviceName, otel and metrics at its top level.
type Config struct {
	GRPC             GRPCConfig `yaml:"grpc"`
	Logging          LogConfig  `yaml:"logging"`
	telemetry.Config `yaml:",inline"`
}

// LogConfig configures the process-wide logger.
type LogConfig struct {
	// Level is "debug", "info" (the default), "warn" or "error"; main.go passes it to
	// log.SetLevel.
	Level string `yaml:"level"`
}

// GRPCConfig configures the gRPC listener.
type GRPCConfig struct {
	// Addr is the gRPC bind address, e.g. ":9000".
	Addr string `yaml:"addr"`

	// HandlerTimeout bounds unary calls, a shorter client deadline winning; streams are not
	// bounded. 0 sets none.
	HandlerTimeout time.Duration `yaml:"handlerTimeout"`

	// Reflection serves gRPC reflection for grpcurl and grpcui; keep it off on a public listener.
	Reflection bool `yaml:"reflection"`
}

// The telemetry sections under local names; [telemetry.Config] documents their fields.
type (
	TelemetryConfig = telemetry.Config
	OTelConfig      = telemetry.OTelConfig
	MetricsConfig   = telemetry.MetricsConfig
)

// Path returns the location of config.yaml, relative to the project root.
func Path() string {
	return "config/config.yaml"
}

// Load reads cfgPath, unless it is empty or missing, then fills the defaults the runtime
// lacks.
func Load(cfgPath string) (*Config, error) {
	cfg := &Config{}
	if cfgPath != "" {
		data, err := os.ReadFile(cfgPath)
		if err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("read %s: %w", cfgPath, err)
		}
		if err == nil {
			if err := yaml.Unmarshal(data, cfg); err != nil {
				return nil, fmt.Errorf("parse %s: %w", cfgPath, err)
			}
		}
	}
	cfg.applyDefaults()
	return cfg, nil
}

// applyDefaults fills the fields the runtime has no default of its own for.
func (c *Config) applyDefaults() {
	if c.GRPC.Addr == "" {
		c.GRPC.Addr = ":9000"
	}
	if c.ServiceName == "" {
		c.ServiceName = "app"
	}
}
