// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

// Package config loads the runtime settings from config/config.yaml.
package config

import (
	"fmt"
	"os"
	"time"

	"github.com/craftgodotdev/craftgo/pkg/telemetry"
	"gopkg.in/yaml.v3"
)

// Config is the shape of `config/config.yaml`; the inlined telemetry.Config puts
// serviceName, otel and metrics at its top level.
type Config struct {
	Server           ServerConfig `yaml:"server"`
	GRPC             GRPCConfig   `yaml:"grpc"`
	Logging          LogConfig    `yaml:"logging"`
	telemetry.Config `yaml:",inline"`
	Docs             DocsConfig `yaml:"docs"`
}

// LogConfig configures the process-wide logger.
type LogConfig struct {
	// Level is "debug", "info" (the default), "warn" or "error"; main.go passes it to
	// log.SetLevel.
	Level string `yaml:"level"`
}

// DocsConfig configures the API-reference page main.go serves beside the OpenAPI document.
type DocsConfig struct {
	// Enabled serves the docs and spec routes; false, the zero value, serves neither.
	Enabled bool `yaml:"enabled"`

	// UI is the renderer: "redoc" (the default), "swagger" or "scalar".
	UI string `yaml:"ui"`

	// Path is the docs page route, "/docs" by default.
	Path string `yaml:"path"`

	// SpecPath is the OpenAPI document route, "/openapi.yaml" by default.
	SpecPath string `yaml:"specPath"`
}

// ServerConfig configures the HTTP listener and the defaults its routes take. Its read and write
// deadlines and header cap are the server's SetDefault* setters, for main.go to call when needed.
type ServerConfig struct {
	// Addr is the HTTP bind address, e.g. ":8080" or "127.0.0.1:8080".
	Addr string `yaml:"addr"`

	// HandlerTimeout is the request-context deadline of a route without @timeout; 0 sets none.
	HandlerTimeout time.Duration `yaml:"handlerTimeout"`

	// MaxBodySize is the body cap in bytes of a route without @maxBodySize; 0 sets none.
	MaxBodySize int64 `yaml:"maxBodySize"`

	// StrictJSON rejects a JSON body with an unknown field or data after the value.
	StrictJSON bool `yaml:"strictJSON"`

	// Compression is off by default, for a deployment behind a compressing proxy.
	Compression CompressionConfig `yaml:"compression"`
}

// CompressionConfig configures gzip and deflate response compression.
type CompressionConfig struct {
	// Enabled wraps every route in server.Compress.
	Enabled bool `yaml:"enabled"`
	// MinSize is the smallest body compressed, in bytes; 0 means 1024.
	MinSize int `yaml:"minSize"`
	// Level is the compression level, 1 to 9; 0 means the default.
	Level int `yaml:"level"`
}

// GRPCConfig configures the gRPC listener.
type GRPCConfig struct {
	// Addr is the gRPC bind address, e.g. ":9000".
	Addr string `yaml:"addr"`

	// HandlerTimeout bounds unary calls, a shorter client deadline winning; streams are not
	// bounded. 0 sets none.
	HandlerTimeout time.Duration `yaml:"handlerTimeout"`

	// Reflection serves gRPC reflection for grpcurl and grpcui; keep it off on a public listener.
	Reflection bool `yaml:"reflection"`
}

// The telemetry sections under local names; [telemetry.Config] documents their fields.
type (
	TelemetryConfig = telemetry.Config
	OTelConfig      = telemetry.OTelConfig
	MetricsConfig   = telemetry.MetricsConfig
)

// Path returns the location of config.yaml, relative to the project root.
func Path() string {
	return "config/config.yaml"
}

// Load reads cfgPath, unless it is empty or missing, then fills the defaults the runtime
// lacks.
func Load(cfgPath string) (*Config, error) {
	cfg := &Config{}
	if cfgPath != "" {
		data, err := os.ReadFile(cfgPath)
		if err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("read %s: %w", cfgPath, err)
		}
		if err == nil {
			if err := yaml.Unmarshal(data, cfg); err != nil {
				return nil, fmt.Errorf("parse %s: %w", cfgPath, err)
			}
		}
	}
	cfg.applyDefaults()
	return cfg, nil
}

// applyDefaults fills the fields the runtime has no default of its own for.
func (c *Config) applyDefaults() {
	if c.Server.Addr == "" {
		c.Server.Addr = ":8080"
	}
	if c.GRPC.Addr == "" {
		c.GRPC.Addr = ":9000"
	}
	if c.ServiceName == "" {
		c.ServiceName = "app"
	}
}
