// Code generated by craftgo. DO NOT EDIT.

package wiring

import (
	"context"
	"errors"

	"github.com/craftgodotdev/craftgo/pkg/server"

	"example.com/app/internal/routes"
	"example.com/app/svccontext"
)

// Register registers the design's HTTP routes on srv.
func Register(ctx context.Context, srv *server.Server, svcCtx *svccontext.ServiceContext) (func(context.Context) error, error) {
	routes.RegisterAll(srv, svcCtx)
	// The chain skips a nil middleware, so an unwired one fails here.
	if svcCtx.AuthRequired == nil {
		return nil, errors.New("wiring: the design declares `middleware AuthRequired` and TodoService.ListTodos runs it, but svcCtx.AuthRequired is nil - assign `svc.AuthRequired = middleware.NewAuthRequiredMiddleware(/* args */)` in main.go")
	}
	return func(context.Context) error { return nil }, nil
}
