// Scaffold generated by craftgo. Safe to edit; will not be overwritten.
//
// Package config is the project's runtime configuration loader. main.go
// reads `config/config.yaml` at boot, fills in framework defaults, and
// hands the resulting *Config to svccontext so every
// service/middleware/logic function reads the same source of truth.
//
// Layout convention:
//
//	config/
//	├── config.go             - this file (Go struct + loader)
//	├── config.yaml           - local dev values (gitignore in real
//	│                           projects; commit only the example)
//	└── example.config.yaml   - committed reference with every key
//	                            documented; copy → config.yaml on a
//	                            new checkout, then edit
//
// Add new fields by extending the struct, optional yaml tag + default
// in [applyDefaults]. Per-environment overrides belong in
// `config.yaml` itself (one file per env, mounted by the deployer).
package config

import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/craftgodotdev/craftgo/pkg/metrics"
	craftotel "github.com/craftgodotdev/craftgo/pkg/otel"
)

// Config is the in-memory shape of `config/config.yaml`. Each section
// maps to one runtime concern - server listener, distributed tracing,
// metrics - so feature owners can extend their own block without
// stepping on each other.
//
// OTel + Metrics reuse the canonical library types so the call sites
// in main.go can pass `cfg.OTel` / `cfg.Metrics` straight into the
// dispatch helpers without re-mapping fields.
type Config struct {
	Server  ServerConfig     `yaml:"server"`
	Logging LogConfig        `yaml:"logging"`
	OTel    craftotel.Config `yaml:"otel"`
	Metrics metrics.Config   `yaml:"metrics"`
	Docs    DocsConfig       `yaml:"docs"`
}

// LogConfig controls the process-wide logger. Only the minimum level is
// modelled here; format (JSON vs console) and output destination are
// wired in main.go, where you can swap log.New / log.NewConsole or
// install your own logger via srv.SetLogger.
type LogConfig struct {
	// Level is the minimum level emitted: "debug", "info" (default),
	// "warn", or "error". main.go feeds it to log.SetLevel, which retunes
	// the server and the generated logic layer together. An unrecognised
	// value leaves the info default in place.
	Level string `yaml:"level"`
}

// DocsConfig controls the in-process API-reference docs page. When enabled,
// main.go serves the generated OpenAPI document plus an HTML page that renders
// it with the chosen UI (assets loaded from a CDN).
type DocsConfig struct {
	// Enabled toggles the docs + spec routes. Default true.
	Enabled bool `yaml:"enabled"`

	// UI is the renderer: "redoc" (default), "swagger", or "scalar".
	UI string `yaml:"ui"`

	// Path is the HTML docs page route. Default "/docs".
	Path string `yaml:"path"`

	// SpecPath is the route serving the raw OpenAPI document. Default
	// "/openapi.yaml".
	SpecPath string `yaml:"specPath"`
}

// ServerConfig configures the public API listener that handles HTTP
// traffic. The admin / metrics scrape lives on a separate listener
// (see [MetricsConfig]) so ops can firewall the two independently.
//
// Transport-level deadlines (`http.Server.ReadTimeout`,
// `WriteTimeout`, `IdleTimeout`, `ReadHeaderTimeout`,
// `MaxHeaderBytes`) are NOT modelled here - those are server-wide
// stdlib knobs the user sets directly on the http.Server in main.go
// when the defaults are insufficient. This struct only carries
// per-handler defaults the framework can enforce uniformly.
type ServerConfig struct {
	// Addr is the bind address for the public HTTP server, e.g. ":8080"
	// or "127.0.0.1:8080" to limit to localhost during development.
	Addr string `yaml:"addr"`

	// HandlerTimeout is the global default for handler execution.
	// Applied as `srv.Use(server.Timeout(d))` so every route inherits
	// the deadline; per-method `@timeout(d)` decorators override
	// (innermost wrap wins). Zero = no global default.
	HandlerTimeout time.Duration `yaml:"handlerTimeout"`

	// MaxBodySize is the global default request-body cap in bytes.
	// Applied as `srv.Use(server.BodyLimit(n))` so every route
	// inherits the limit; per-method `@maxBodySize(n)` decorators
	// override. Zero = no global cap.
	MaxBodySize int64 `yaml:"maxBodySize"`

	// Compression toggles gzip / deflate response compression. Disabled
	// by default so deployments behind a compressing reverse proxy
	// (Nginx, Envoy, CloudFront) don't double-encode.
	Compression CompressionConfig `yaml:"compression"`
}

// CompressionConfig drives the response compression middleware. The
// middleware negotiates gzip / deflate against the client's
// Accept-Encoding; small bodies and pre-compressed media types
// (image/*, video/*, application/zip, ...) pass through untouched.
type CompressionConfig struct {
	// Enabled toggles the middleware. False = no wrap, no Vary header.
	Enabled bool `yaml:"enabled"`
	// MinSize is the byte threshold below which responses skip
	// compression. Zero falls back to the framework default (1024).
	MinSize int `yaml:"minSize"`
	// Level is the gzip / deflate level (1..9). Zero falls back to
	// the framework default (compress/gzip.DefaultCompression).
	Level int `yaml:"level"`
}

// OTel + Metrics block shapes live in `pkg/otel` and `pkg/metrics`
// respectively (look there for field-by-field docs). The aliases
// below let `config.yaml` and call sites read like local types
// without the project re-defining the schema.
//
// Aliases are kept exported so an IDE goto-definition lands on the
// library doc strings instead of an opaque indirection.
type (
	// OTelConfig drives the OpenTelemetry tracer setup. Disabled =
	// silent no-op (no spans, no propagation); enabled with exporter
	// "none" still produces in-process spans whose IDs flow into log
	// lines but go nowhere. See [craftotel.Config] for field detail.
	OTelConfig = craftotel.Config

	// MetricsConfig drives the OpenTelemetry meter + admin scrape
	// listener. otelhttp's HTTPMiddleware records the standard
	// `http.server.*` instruments against whatever meter provider
	// gets installed; this block only chooses where the metrics
	// flow OUT. See [metrics.Config] for field detail.
	MetricsConfig = metrics.Config
)

// Path returns the conventional config-file location. Override by
// passing a different path to [Load] directly.
func Path() string {
	return "config/config.yaml"
}

// Load reads cfgPath (when non-empty) and fills in framework defaults
// for any blank fields. The YAML file is the single source of truth;
// pass an empty cfgPath to boot purely on defaults.
func Load(cfgPath string) (*Config, error) {
	cfg := &Config{}
	if cfgPath != "" {
		data, err := os.ReadFile(cfgPath)
		if err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("read %s: %w", cfgPath, err)
		}
		if err == nil {
			if err := yaml.Unmarshal(data, cfg); err != nil {
				return nil, fmt.Errorf("parse %s: %w", cfgPath, err)
			}
		}
	}
	cfg.applyDefaults()
	return cfg, nil
}

// applyDefaults fills any blank field with the framework's recommended
// value. Mirrors the example.config.yaml that ships with `craftgo init`
// so a project that deletes config.yaml and runs purely on defaults
// behaves identically to one that copied the example.
func (c *Config) applyDefaults() {
	if c.Server.Addr == "" {
		c.Server.Addr = ":8080"
	}

	if c.Logging.Level == "" {
		c.Logging.Level = "info"
	}

	if c.OTel.Exporter == "" {
		c.OTel.Exporter = "none"
	}
	if c.OTel.ServiceName == "" {
		c.OTel.ServiceName = "raw"
	}

	if c.Metrics.Exporter == "" {
		c.Metrics.Exporter = "prometheus"
	}
	if c.Metrics.AdminAddr == "" {
		c.Metrics.AdminAddr = ":9090"
	}
	if c.Metrics.Path == "" {
		c.Metrics.Path = "/metrics"
	}

	if c.Docs.UI == "" {
		c.Docs.UI = "redoc"
	}
	if c.Docs.Path == "" {
		c.Docs.Path = "/docs"
	}
	if c.Docs.SpecPath == "" {
		c.Docs.SpecPath = "/openapi.yaml"
	}
}
