// Code generated by craftgo. DO NOT EDIT.

package upstream

import (
	"context"
	"fmt"

	craftevents "github.com/craftgodotdev/craftgo/pkg/events"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/upstream"
)

// Consumers is the handler set LedgerService must supply for the contracts
// it consumes. Implement it and hand it to [Subscriptions]; nothing here
// depends on the application that hosts the bus.
type Consumers interface {
	RecordSettlement(ctx context.Context, payload *types.PaymentSettledPayload) error
}

// Subscriptions binds h to bus, one subscription per contract LedgerService
// consumes. The payload is decoded with the bus codec and validated before
// a handler sees it; a payload that fails either never reaches the
// handler, and the error names the contract it arrived on.
func Subscriptions(bus *craftevents.Bus, h Consumers) []craftevents.Subscription {
	return []craftevents.Subscription{
		{
			Event:    "payments.settled.v1",
			Consumer: "RecordSettlement",
			Group:    "upstream-LedgerService-RecordSettlement",
			Handle: func(ctx context.Context, msg *craftevents.Message) error {
				var payload types.PaymentSettledPayload
				if err := bus.Decode(msg, &payload); err != nil {
					return err
				}
				if err := payload.Validate(); err != nil {
					return fmt.Errorf("validate %s: %w", "payments.settled.v1", err)
				}
				return h.RecordSettlement(ctx, &payload)
			},
		},
	}
}
