// Code generated by craftgo. DO NOT EDIT.

package rawmodes

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/raw_modes_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// @timeout applies to a passthrough route: the stub sees a context deadline.
//
// PtTimeout returns the GET PtTimeout handler.
func PtTimeout(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewPtTimeoutService(r.Context(), svcCtx)
		if err := l.PtTimeout(w, r); err != nil {
			server.WriteError(w, r, err)
			return
		}
	}
}
