// Code generated by craftgo. DO NOT EDIT.

package rawmodes

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/raw_modes_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RqDocsReq returns the http.HandlerFunc for the
// POST RqDocsReq raw-request endpoint. The handler hands the
// *http.Request to logic unread and encodes the returned response.
func RqDocsReq(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewRqDocsReqService(r.Context(), svcCtx)
		resp, err := l.RqDocsReq(r)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
