// Code generated by craftgo. DO NOT EDIT.

package rawmodes

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/raw_modes_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Raw request, no response: `(r) error`, 204 on success.
//
// RqNoResp returns the GET RqNoResp handler.
func RqNoResp(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewRqNoRespService(r.Context(), svcCtx)
		err := l.RqNoResp(r)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}
