// Code generated by craftgo. DO NOT EDIT.

package rawmodes

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/raw_modes_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RrLate returns the http.HandlerFunc for the
// GET RrLate raw-response endpoint. The handler binds and
// validates the request, then hands the http.ResponseWriter and
// *http.Request to logic, which writes the response directly.
func RrLate(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewRrLateService(r.Context(), svcCtx)
		if err := l.RrLate(w, r); err != nil {
			server.WriteError(w, r, err)
			return
		}
	}
}
