// Code generated by craftgo. DO NOT EDIT.

package rawmodes

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/raw_modes_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/rawmodes"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RrMultipart returns the http.HandlerFunc for the
// POST RrMultipart raw-response endpoint. The handler binds and
// validates the request, then hands the http.ResponseWriter and
// *http.Request to logic, which writes the response directly.
func RrMultipart(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(33554432); err != nil {
			http.Error(w, err.Error(), http.StatusRequestEntityTooLarge)
			return
		}
		// Remove the temp files the parser spilled to disk as soon as the
		// handler returns. net/http sweeps them again at end-of-response, but
		// the explicit cleanup releases disk before the response flush and
		// still runs on panic paths that bypass that sweep.
		defer func() { _ = r.MultipartForm.RemoveAll() }()
		var req types.RrUploadReq
		req.Note = r.FormValue("note")
		if _, header, err := r.FormFile("doc"); err == nil {
			req.Doc = header
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewRrMultipartService(r.Context(), svcCtx)
		if err := l.RrMultipart(w, r, &req); err != nil {
			server.WriteError(w, r, err)
			return
		}
	}
}
