// Code generated by craftgo. DO NOT EDIT.

package rawmodes

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/raw_modes_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/rawmodes"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Raw response over a bound + validated request; @status(201) and the Location header are docs-only.
//
// RrReq returns the POST RrReq handler.
func RrReq(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.RrReq
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewRrReqService(r.Context(), svcCtx)
		if err := l.RrReq(w, r, &req); err != nil {
			server.WriteError(w, r, err)
			return
		}
	}
}
