// Code generated by craftgo. DO NOT EDIT.

package orders

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/ecommerce/internal/service/order_service"
	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/orders"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// Bulk export - admin only, extra body-limit/timeout on top of parent chain.
//
// BulkExport returns the POST BulkExport handler.
func BulkExport(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.ListOrdersReq
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		_q := r.URL.Query()
		if _v := _q.Get("status"); _v != "" {
			_w := types.OrderStatus(_v)
			req.Status = &_w
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewBulkExportService(r.Context(), svcCtx)
		resp, err := l.BulkExport(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusCreated, resp)
	}
}
