// Code generated by craftgo. DO NOT EDIT.

package orders

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/ecommerce/internal/service/order_service"
	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/orders"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// Fetch one order.
//
// GetOrder returns the GET GetOrder handler.
func GetOrder(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetOrderReq
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewGetOrderService(r.Context(), svcCtx)
		resp, err := l.GetOrder(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusOK, resp)
	}
}
