// Code generated by craftgo. DO NOT EDIT.

package transport

import (
	"context"

	craftevents "github.com/craftgodotdev/craftgo/pkg/events"

	analyticsserviceevents "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/events/analytics_service"
	inventoryserviceevents "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/events/inventory_service"
	ledgerserviceevents "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/events/ledger_service"
	notificationserviceevents "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/events/notification_service"
	opsserviceevents "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/events/ops_service"

	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// SubscribeAll registers every consumer the design declares, the way
// RegisterAll wires every handler. Each service's subscriptions are built
// by its own event package from the handler set in this package, so the
// decode-validate-dispatch rule is spelled once, in the contract.
// Delivery runs until ctx is cancelled.
func SubscribeAll(ctx context.Context, bus *craftevents.Bus, svcCtx *svccontext.ServiceContext) error {
	var subs []craftevents.Subscription
	subs = append(subs, inventoryserviceevents.Subscriptions(bus, NewInventoryServiceConsumers(svcCtx))...)
	subs = append(subs, analyticsserviceevents.Subscriptions(bus, NewAnalyticsServiceConsumers(svcCtx))...)
	subs = append(subs, notificationserviceevents.Subscriptions(bus, NewNotificationServiceConsumers(svcCtx))...)
	subs = append(subs, opsserviceevents.Subscriptions(bus, NewOpsServiceConsumers(svcCtx))...)
	subs = append(subs, ledgerserviceevents.Subscriptions(bus, NewLedgerServiceConsumers(svcCtx))...)
	return bus.SubscribeAll(ctx, subs)
}
