// Code generated by craftgo. DO NOT EDIT.

package transport

import (
	"context"

	guardedservicelogic "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/guarded_service"
	events "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/events"

	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// GuardedServiceConsumers is the handler set GuardedService asks for.
//
// It satisfies the Consumers interface the service's event package
// declares, forwarding each payload to that consumer's logic. Consumers
// a @group moved into another logic package are reached through their
// own import, so one value serves the whole service.
type GuardedServiceConsumers struct {
	svcCtx *svccontext.ServiceContext
}

// NewGuardedServiceConsumers binds GuardedService's consumers to svcCtx.
func NewGuardedServiceConsumers(svcCtx *svccontext.ServiceContext) *GuardedServiceConsumers {
	return &GuardedServiceConsumers{svcCtx: svcCtx}
}

// GuardedStock hands a decoded events.ItemStocked to its logic.
func (h *GuardedServiceConsumers) GuardedStock(ctx context.Context, payload *events.ItemStocked) error {
	return guardedservicelogic.NewGuardedStockConsumer(ctx, h.svcCtx).GuardedStock(payload)
}

// BareStock hands a decoded events.StocktakeStarted to its logic.
func (h *GuardedServiceConsumers) BareStock(ctx context.Context, payload *events.StocktakeStarted) error {
	return guardedservicelogic.NewBareStockConsumer(ctx, h.svcCtx).BareStock(payload)
}

// InheritedStock hands a decoded events.WarehouseClosed to its logic.
func (h *GuardedServiceConsumers) InheritedStock(ctx context.Context, payload *events.WarehouseClosed) error {
	return guardedservicelogic.NewInheritedStockConsumer(ctx, h.svcCtx).InheritedStock(payload)
}
