// Code generated by craftgo. DO NOT EDIT.

package transport

import (
	"context"

	opsserviceopslogic "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/ops"
	events "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/events"

	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// OpsServiceConsumers is the handler set OpsService asks for.
//
// It satisfies the Consumers interface the service's event package
// declares, forwarding each payload to that consumer's logic. Consumers
// a @group moved into another logic package are reached through their
// own import, so one value serves the whole service.
type OpsServiceConsumers struct {
	svcCtx *svccontext.ServiceContext
}

// NewOpsServiceConsumers binds OpsService's consumers to svcCtx.
func NewOpsServiceConsumers(svcCtx *svccontext.ServiceContext) *OpsServiceConsumers {
	return &OpsServiceConsumers{svcCtx: svcCtx}
}

// RecordClosure hands a decoded events.WarehouseClosed to its logic.
func (h *OpsServiceConsumers) RecordClosure(ctx context.Context, payload *events.WarehouseClosed) error {
	return opsserviceopslogic.NewRecordClosureConsumer(ctx, h.svcCtx).RecordClosure(payload)
}
