// Code generated by craftgo. DO NOT EDIT.

package adminapi

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/admin/v3"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// PingV3 returns the http.HandlerFunc for the
// GET PingV3 endpoint.
func PingV3(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewPingV3Service(r.Context(), svcCtx)
		resp, err := l.PingV3()
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
