// Code generated by craftgo. DO NOT EDIT.

package grpc

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/rpc"

	pb "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/pb/grpc"
	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/greeter"
)

// SayHello answers one greeting; an empty name is refused.
// SayHello serves the unary RPC /grpcmatrix.Greeter/SayHello: it hands the
// call context to the logic and maps the error it returns onto a status,
// as the HTTP handler does with WriteError.
func (s *Server) SayHello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloReply, error) {
	if err := rpc.Validate(req); err != nil {
		return nil, err
	}
	l := service.NewSayHelloService(ctx, s.svcCtx)
	resp, err := l.SayHello(req)
	if err != nil {
		return nil, rpc.Error(ctx, err)
	}
	return resp, nil
}
