// Code generated by craftgo. DO NOT EDIT.

package regression

type Rg3Color string

const (
	Rg3ColorRed   Rg3Color = "RED"
	Rg3ColorGreen Rg3Color = "GREEN"
)

type Rg3Level int

const (
	Rg3LevelLow  Rg3Level = 1
	Rg3LevelHigh Rg3Level = 9
)

type Rg3Status int

const (
	Rg3StatusInactive Rg3Status = 0
	Rg3StatusActive   Rg3Status = 1
	Rg3StatusBanned   Rg3Status = 2
)

type Rg5Method string

const (
	Rg5MethodCard Rg5Method = "card"
	Rg5MethodBank Rg5Method = "bank"
)

type RgColor string

const (
	RgColorRed   RgColor = "red"
	RgColorGreen RgColor = "green"
	RgColorBlue  RgColor = "blue"
)

type RgPriority int

const (
	RgPriorityLow    RgPriority = 1
	RgPriorityMedium RgPriority = 5
	RgPriorityHigh   RgPriority = 10
)
