// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package adminservice

import (
	"context"
	"io"

	"github.com/dropship-dev/craftgo/example/svccontext"
	"github.com/dropship-dev/craftgo/pkg/log"
	"github.com/dropship-dev/craftgo/pkg/server"
)

// EchoStreamLogic carries the per-request state for the
// EchoStream raw-streaming endpoint of AdminService.
type EchoStreamLogic struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewEchoStreamLogic constructs a fresh logic instance bound to ctx.
func NewEchoStreamLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *EchoStreamLogic {
	return &EchoStreamLogic{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// EchoStream is the @raw @stream combo: logic gets a body
// io.Reader for the raw input AND a *server.RawStream it writes
// chunks into. The handler flushes after every Write so the
// client sees each chunk as soon as it's produced.
// EchoStream is the raw-streaming business-logic entry point. The
// `body` parameter is the raw request payload; `stream` is the
// auto-flushing response writer. Read from body, write chunks to
// stream as they're produced, and return when done.
//
// Honour l.ctx so an aborted client closes the stream cleanly.
func (l *EchoStreamLogic) EchoStream(body io.Reader, stream *server.RawStream) error {
	buf := make([]byte, 8)
	for {
		select {
		case <-l.ctx.Done():
			return l.ctx.Err()
		default:
		}
		n, err := body.Read(buf)
		if n > 0 {
			if _, werr := stream.Write(buf[:n]); werr != nil {
				return werr
			}
		}
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
	}
}
