// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package adminservice

import (
	"context"

	types "github.com/dropship-dev/craftgo/example/internal/types/design"

	"github.com/dropship-dev/craftgo/example/svccontext"
	"github.com/dropship-dev/craftgo/pkg/log"
)

// StatsLogic carries the per-request state for the
// Stats endpoint of AdminService.
type StatsLogic struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewStatsLogic constructs a fresh logic instance bound to ctx.
func NewStatsLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *StatsLogic {
	return &StatsLogic{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Stats returns aggregate book/order counts. Path resolves to
// `/api/v1/admin/stats`.
// Stats is the business-logic entry point. Replace the
// TODO with the real implementation.
func (l *StatsLogic) Stats() (*types.AdminStats, error) {
	l.svcCtx.Lock()
	defer l.svcCtx.Unlock()
	revenue := 0
	for _, o := range l.svcCtx.Orders {
		if o.Status != "cancelled" {
			revenue += o.TotalCents
		}
	}
	return &types.AdminStats{
		BookCount:  len(l.svcCtx.Books),
		OrderCount: len(l.svcCtx.Orders),
		Revenue:    revenue,
	}, nil
}
