// Code generated by craftgo. DO NOT EDIT.

package tasks

import (
	"github.com/craftgodotdev/craftgo/example/taskflow/internal/types/shared"
)

type AddCommentReq struct {
	ProjectID shared.ID `json:"-" path:"projectId"`
	ID        shared.ID `json:"-" path:"id"`
	Body      string    `json:"body"`
}

type BulkCreateReq struct {
	ProjectID shared.ID        `json:"-" path:"projectId"`
	Tasks     []CreateTaskItem `json:"tasks"`
}

type Comment struct {
	ID     shared.ID `json:"id"`
	TaskID shared.ID `json:"taskId"`
	Author shared.ID `json:"author"`
	Body   string    `json:"body"`
	shared.Timestamps
}

// One row of a bulk create.
type CreateTaskItem struct {
	Title    string    `json:"title"`
	Priority *Priority `json:"priority,omitempty"`
}

type CreateTaskReq struct {
	ProjectID   shared.ID      `json:"-" path:"projectId"`
	Title       string         `json:"title"`
	Description *string        `json:"description,omitempty"`
	Priority    *Priority      `json:"priority,omitempty"`
	Points      *shared.Points `json:"points,omitempty"`
	AssigneeIds []shared.ID    `json:"assigneeIds,omitempty"`
	Labels      []string       `json:"labels,omitempty"`
	DueAt       *string        `json:"dueAt,omitempty"`
}

type GetTaskReq struct {
	ProjectID shared.ID `json:"-" path:"projectId"`
	ID        shared.ID `json:"-" path:"id"`
}

type ListTasksReq struct {
	shared.PageParams
	ProjectID shared.ID   `json:"-" path:"projectId"`
	Status    *TaskStatus `json:"-" query:"status"`
	Priority  *Priority   `json:"-" query:"priority"`
	Assignee  *shared.ID  `json:"-" query:"assignee"`
}

type LogTimeReq struct {
	ProjectID shared.ID `json:"-" path:"projectId"`
	ID        shared.ID `json:"-" path:"id"`
	// Minutes worked, in 5-minute increments (max one working day).
	Minutes int `json:"minutes"`
}

type ReindexReq struct {
	ProjectID shared.ID `json:"-" path:"projectId"`
}

type SetTaskStatusReq struct {
	ProjectID shared.ID  `json:"-" path:"projectId"`
	ID        shared.ID  `json:"-" path:"id"`
	Status    TaskStatus `json:"status"`
}

type Task struct {
	ID          shared.ID      `json:"id"`
	ProjectID   shared.ID      `json:"projectId"`
	Title       string         `json:"title"`
	Description *string        `json:"description,omitempty"`
	Status      TaskStatus     `json:"status"`
	Priority    Priority       `json:"priority"`
	Points      *shared.Points `json:"points,omitempty"`
	ProgressPct int            `json:"progressPct"`
	AssigneeIds []shared.ID    `json:"assigneeIds"`
	Labels      []string       `json:"labels"`
	DueAt       *string        `json:"dueAt,omitempty"`
	// Server-only: the denormalised search text, populated by service code
	// and never accepted from or sent to a client.
	SearchText string `json:"-"`
	shared.Timestamps
}
