// Code generated by craftgo. DO NOT EDIT.

package catalogservice

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/catalog-service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Featured returns the http.HandlerFunc for the
// GET Featured endpoint.
func Featured(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewFeaturedService(r.Context(), svcCtx)
		resp, err := l.Featured()
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
