// Code generated by craftgo. DO NOT EDIT.

package accountservice

import (
	"encoding/json"
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/service/account-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/services"
	shared "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/shared"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// DeleteAccount returns the http.HandlerFunc for the
// DELETE DeleteAccount endpoint.
func DeleteAccount(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.DeleteAccountReq
		req.ID = shared.ID(r.PathValue("id"))
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewDeleteAccountService(r.Context(), svcCtx)
		resp, err := l.DeleteAccount(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
