// Code generated by craftgo. DO NOT EDIT.

package accountservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/service/account-service"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// Logout returns the http.HandlerFunc for the
// POST Logout endpoint.
func Logout(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewLogoutService(r.Context(), svcCtx)
		resp, err := l.Logout()
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
