// Code generated by craftgo. DO NOT EDIT.

package tasks

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/taskflow/internal/service/task_service"
	"github.com/craftgodotdev/craftgo/example/taskflow/internal/types/shared"
	types "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/tasks"
	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// Deprecated: use SetTaskStatus with status=done. Kept for older clients.
//
// CloseTask returns the POST CloseTask handler.
func CloseTask(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetTaskReq
		req.ProjectID = shared.ID(r.PathValue("projectId"))
		req.ID = shared.ID(r.PathValue("id"))
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewCloseTaskService(r.Context(), svcCtx)
		resp, err := l.CloseTask(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusCreated, resp)
	}
}
