// Code generated by craftgo. DO NOT EDIT.

package xrefs

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/x_refs_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Pins cross-package response generic. Component must be `XBagOfXOwner`, not dangling `xshared.XBag`.
//
// ListItems returns the GET ListItems handler.
func ListItems(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewListItemsService(r.Context(), svcCtx)
		resp, err := l.ListItems()
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusOK, resp)
	}
}
