// Code generated by craftgo. DO NOT EDIT.

package scalars

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/scalars_service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/scalars"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// EchoRefMeta returns the http.HandlerFunc for the
// POST EchoRefMeta endpoint.
func EchoRefMeta(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.RefMeta
		{
			__d := types.Count(7)
			req.RoleReq = &__d
		}
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewEchoRefMetaService(r.Context(), svcCtx)
		resp, err := l.EchoRefMeta(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
