// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package adminservice

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// LegacyPingService carries the per-request state for the
// LegacyPing endpoint of AdminService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type LegacyPingService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewLegacyPingService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewLegacyPingService(ctx context.Context, svcCtx *svccontext.ServiceContext) *LegacyPingService {
	return &LegacyPingService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// LegacyPing is the service entry point. Replace the
// TODO with the real implementation.
func (l *LegacyPingService) LegacyPing() error {
	// TODO: implement
	return nil
}
