// Code generated by craftgo. DO NOT EDIT.

package projectservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/example/internal/service/project-service"
	types "github.com/craftgodotdev/craftgo/example/internal/types/projects"
	"github.com/craftgodotdev/craftgo/example/svccontext"
)

// DeleteProject returns the http.HandlerFunc for the
// DELETE DeleteProject endpoint.
func DeleteProject(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetProjectReq
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewDeleteProjectService(r.Context(), svcCtx)
		resp, err := l.DeleteProject(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
