// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package customerservice

import (
	"context"

	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/customers"
	shared "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/shared"

	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// ListCustomersService carries the per-request state for the
// ListCustomers endpoint of CustomerService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type ListCustomersService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewListCustomersService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewListCustomersService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ListCustomersService {
	return &ListCustomersService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// ListCustomers is the service entry point. Replace the
// TODO with the real implementation.
func (l *ListCustomersService) ListCustomers(req *shared.Pagination) (*shared.Page[types.Customer], error) {
	// TODO: implement
	return nil, nil
}
