// Code generated by craftgo. DO NOT EDIT.

package userservice

import (
	"encoding/json"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/users/internal/service/user-service"
	"github.com/craftgodotdev/craftgo/tests/e2e/users/svccontext"
)

// DeleteUser clears the in-memory store. Path id is currently ignored.
// DeleteUser returns the http.HandlerFunc for the
// DELETE DeleteUser endpoint.
func DeleteUser(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewDeleteUserService(r.Context(), svcCtx)
		resp, err := l.DeleteUser()
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
