// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package notifications

import (
	"context"
	"fmt"

	orders "github.com/craftgodotdev/craftgo/example/brokers/internal/types/orders"

	"github.com/craftgodotdev/craftgo/example/brokers/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// SendDispatchNoteConsumer carries the per-message state for the SendDispatchNote
// consumer of NotificationService. The embedded log.Logger is bound to the
// delivery context; whether that context carries a trace depends on the
// transport - the in-process one starts a fresh context per message.
type SendDispatchNoteConsumer struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewSendDispatchNoteConsumer constructs a fresh consumer instance bound to ctx.
func NewSendDispatchNoteConsumer(ctx context.Context, svcCtx *svccontext.ServiceContext) *SendDispatchNoteConsumer {
	return &SendDispatchNoteConsumer{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// SendDispatchNote handles orders.Shipped. The payload arrives decoded and
// validated; returning an error tells the transport the message was not
// processed.
func (l *SendDispatchNoteConsumer) SendDispatchNote(payload *orders.OrderShipped) error {
	fmt.Printf("  [notifications/SendDispatch]  order=%s carrier=%s\n", payload.OrderID, payload.Carrier)
	return nil
}
