// Code generated by craftgo. DO NOT EDIT.

package bindingsservice

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/bindings-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/bindings"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// DeleteItem reuses GetItemReq (path-only DTO) and pins two
// errors: a 404 (RecordNotFound, bodyless) and a 403
// (AccessDenied, typed body). Idempotent — repeated deletes
// surface the same response.
// DeleteItem returns the http.HandlerFunc for the
// DELETE DeleteItem endpoint.
func DeleteItem(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetItemReq
		req.ID = types.UUID(r.PathValue("id"))
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewDeleteItemService(r.Context(), svcCtx)
		resp, err := l.DeleteItem(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
