// Code generated by craftgo. DO NOT EDIT.

package bindingsservice

import (
	"encoding/json"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/service/bindings-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/bindings"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// UploadAvatar exercises the path + form-file combination. The
// `id` field auto-binds to the path segment; the `file` field
// rides the multipart/form-data body.
// UploadAvatar returns the http.HandlerFunc for the
// POST UploadAvatar multipart endpoint. The handler parses
// `multipart/form-data` bodies, binds every form field declared on
// the request type, and populates `*multipart.FileHeader` fields
// for any DSL-typed `file` declarations.
func UploadAvatar(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			http.Error(w, err.Error(), http.StatusRequestEntityTooLarge)
			return
		}
		var req types.UploadReq
		req.ID = r.PathValue("id")
		if _, header, err := r.FormFile("file"); err == nil {
			req.File = header
		}
		if err := req.Validate(); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		l := service.NewUploadAvatarService(r.Context(), svcCtx)
		resp, err := l.UploadAvatar(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
