// Code generated by craftgo. DO NOT EDIT.

package combine

import (
	"encoding/json"
)

// ErrCodeFieldRulesFailed is the canonical machine-readable code for FieldRulesFailedErr.
const ErrCodeFieldRulesFailed = "FIELD_RULES_FAILED"

// FieldRulesFailedBody is the body of FieldRulesFailedErr.
type FieldRulesFailedBody struct {
	Attempts int     `json:"attempts"`
	Field    string  `json:"field"`
	Hint     *string `json:"hint,omitempty"`
	//
	// Deprecated: removed
	Legacy string `json:"legacy"`
}

// FieldRulesFailed is an error body with field constraints, an optional
// field and a @deprecated field.
//
// FieldRulesFailedErr is the UnprocessableEntity error FieldRulesFailed.
type FieldRulesFailedErr struct {
	FieldRulesFailedBody
}

// NewFieldRulesFailedErr constructs FieldRulesFailedErr.
func NewFieldRulesFailedErr(body FieldRulesFailedBody) *FieldRulesFailedErr {
	return &FieldRulesFailedErr{FieldRulesFailedBody: body}
}

// Error returns the UnprocessableEntity category's default message.
func (e *FieldRulesFailedErr) Error() string { return "Unprocessable entity" }

// ErrCode returns ErrCodeFieldRulesFailed.
func (e *FieldRulesFailedErr) ErrCode() string { return ErrCodeFieldRulesFailed }

// HTTPStatus returns the UnprocessableEntity status.
func (e *FieldRulesFailedErr) HTTPStatus() int { return 422 }

// MarshalJSON encodes the body alone.
func (e *FieldRulesFailedErr) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.FieldRulesFailedBody)
}
