// Code generated by craftgo. DO NOT EDIT.

package transport

import (
	"context"

	notificationservicelogic "github.com/craftgodotdev/craftgo/example/brokers/internal/service/notification_service"
	orders "github.com/craftgodotdev/craftgo/example/brokers/internal/types/orders"

	"github.com/craftgodotdev/craftgo/example/brokers/svccontext"
)

// NotificationServiceConsumers is the handler set NotificationService asks for.
//
// It satisfies the Consumers interface the service's event package
// declares, forwarding each payload to that consumer's logic. Consumers
// a @group moved into another logic package are reached through their
// own import, so one value serves the whole service.
type NotificationServiceConsumers struct {
	svcCtx *svccontext.ServiceContext
}

// NewNotificationServiceConsumers binds NotificationService's consumers to svcCtx.
func NewNotificationServiceConsumers(svcCtx *svccontext.ServiceContext) *NotificationServiceConsumers {
	return &NotificationServiceConsumers{svcCtx: svcCtx}
}

// SendReceipt hands a decoded orders.Placed to its logic.
func (h *NotificationServiceConsumers) SendReceipt(ctx context.Context, payload *orders.OrderPlaced) error {
	return notificationservicelogic.NewSendReceiptConsumer(ctx, h.svcCtx).SendReceipt(payload)
}

// SendDispatchNote hands a decoded orders.Shipped to its logic.
func (h *NotificationServiceConsumers) SendDispatchNote(ctx context.Context, payload *orders.OrderShipped) error {
	return notificationservicelogic.NewSendDispatchNoteConsumer(ctx, h.svcCtx).SendDispatchNote(payload)
}
