// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package catalog

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/catalog"
	"github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/shared"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// ListCategoriesService runs CatalogService.ListCategories for one request.
type ListCategoriesService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewListCategoriesService binds ListCategoriesService to ctx; its Logger carries ctx's trace ids.
func NewListCategoriesService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ListCategoriesService {
	return &ListCategoriesService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// List categories.
//
// ListCategories implements CatalogService.ListCategories.
func (l *ListCategoriesService) ListCategories(req *shared.Pagination) (*shared.Page[types.Category], error) {
	// TODO: implement
	return nil, nil
}
