// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package streamservice

import (
	"context"
	"net/http"

	"github.com/craftgodotdev/craftgo/example/raw/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// DownloadService carries the per-request state for the
// Download passthrough endpoint of StreamService. The embedded
// log.Logger is pre-bound to the request context so logging
// surfaces trace_id / span_id / request_id.
type DownloadService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewDownloadService constructs a fresh service instance bound to ctx.
func NewDownloadService(ctx context.Context, svcCtx *svccontext.ServiceContext) *DownloadService {
	return &DownloadService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Download is the passthrough service entry point. The
// framework hands you the raw http.ResponseWriter and *http.Request
// - read path parameters via r.PathValue, write headers/body to w
// directly, and return any error to surface it through the
// framework's error writer.
func (l *DownloadService) Download(w http.ResponseWriter, r *http.Request) error {
	// TODO: implement
	http.Error(w, "not implemented", http.StatusNotImplemented)
	return nil
}
