// Code generated by craftgo. DO NOT EDIT.

package orderservice

import (
	transport "github.com/craftgodotdev/craftgo/example/internal/transport/order-service"
	"github.com/craftgodotdev/craftgo/example/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/server"
)

// RegisterRoutes wires every OrderService endpoint onto srv. Patterns
// use the Go 1.22 method-prefixed form so VERB and path match together;
// service prefix and OpenAPI basePath are baked in. Methods declaring
// `@middlewares(...)` are wrapped via the corresponding fields on
// ServiceContext (embedded Middlewares struct), so no runtime name
// lookup is required - the values come pre-wired.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api/orders/{id}", transport.GetOrder(svcCtx))
	srv.Handle("GET /api/orders", transport.ListOrders(svcCtx))
	srv.Handle("POST /api/orders", transport.CreateOrder(svcCtx))
	srv.Handle("DELETE /api/orders/{id}", transport.DeleteOrder(svcCtx))
	srv.Handle("POST /api/orders/defaults", transport.DefaultsShowcase(svcCtx))
}
