// Code generated by craftgo. DO NOT EDIT.

package money

import (
	"fmt"
	"regexp"
	"unicode/utf8"
)

// The regexes of the @pattern and @format checks, compiled once.
var (
	_pattern0 = regexp.MustCompile("^[A-Za-z0-9-]+$")
)

// Validate returns the first constraint v violates, or nil.
func (v Amount) Validate() error {
	if int64(v) < 0 {
		return fmt.Errorf("below minimum 0")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v OrderID) Validate() error {
	if utf8.RuneCountInString(string(v)) < 1 {
		return fmt.Errorf("length less than 1")
	}
	if utf8.RuneCountInString(string(v)) > 64 {
		return fmt.Errorf("length greater than 64")
	}
	if !_pattern0.MatchString(string(v)) {
		return fmt.Errorf("does not match pattern")
	}
	return nil
}
