// Code generated by craftgo. DO NOT EDIT.

package attachments

import (
	"github.com/craftgodotdev/craftgo/pkg/server"

	transport "github.com/craftgodotdev/craftgo/example/taskflow/internal/transport/attachment_service"
	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// RegisterRoutes registers the AttachmentService routes on srv.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("POST /api/projects/v1/{projectId}/tasks/{taskId}/attachments", server.WithLimits(transport.UploadAttachment(svcCtx), server.Limits{MaxBodySize: 12 << 20}), svcCtx.RequestID, svcCtx.AccessLog, svcCtx.AuthRequired)
	srv.Handle("GET /api/projects/v1/{projectId}/tasks/{taskId}/attachments", transport.ListAttachments(svcCtx), svcCtx.RequestID, svcCtx.AccessLog, svcCtx.AuthRequired)
}
