// Code generated by craftgo. DO NOT EDIT.

package attachments

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/taskflow/internal/service/attachment-service"
	types "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/attachments"
	shared "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/shared"
	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// ListAttachments returns the http.HandlerFunc for the
// GET ListAttachments endpoint.
func ListAttachments(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.ListAttachmentsReq
		{
			__d := 20
			req.Limit = &__d
		}
		req.ProjectID = shared.ID(r.PathValue("projectId"))
		req.TaskID = shared.ID(r.PathValue("taskId"))
		_q := r.URL.Query()
		if _v := _q.Get("cursor"); _v != "" {
			req.Cursor = &_v
		}
		if !server.BindValuePtr(w, r, "limit", "int", _q.Get("limit"), &req.Limit, server.ParseSigned[int]) {
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewListAttachmentsService(r.Context(), svcCtx)
		resp, err := l.ListAttachments(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
