// Code generated by craftgo. DO NOT EDIT.

package nested

import (
	"net/http"
	"strconv"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/nested_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// GetRateResp returns the GET GetRateResp handler.
func GetRateResp(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewGetRateRespService(r.Context(), svcCtx)
		resp, err := l.GetRateResp()
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("X-Rate-Limit", strconv.Itoa(resp.Limit))
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
