// Code generated by craftgo. DO NOT EDIT.

package design

import (
	"github.com/craftgodotdev/craftgo/pkg/server"

	transport "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/transport/profile_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RegisterRoutes registers the ProfileService routes on srv.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api/v1/profiles/{id}", transport.GetProfile(svcCtx))
	srv.Handle("GET /api/v1/profiles", transport.ListProfiles(svcCtx))
	srv.Handle("GET /api/v1/admin/profiles", transport.AdminListProfiles(svcCtx), svcCtx.ProfileAuth)
	srv.Handle("POST /api/v1/profiles", transport.CreateProfile(svcCtx))
	srv.Handle("PATCH /api/v1/profiles/{id}", transport.PatchProfile(svcCtx))
}
