// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package greet

import (
	"context"
	"errors"
	"fmt"
	"io"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"google.golang.org/grpc"

	pb "github.com/craftgodotdev/craftgo/example/grpc/internal/pb/greet"
	"github.com/craftgodotdev/craftgo/example/grpc/svccontext"
)

// RecordHellosService runs Greeter.RecordHellos for one request.
type RecordHellosService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewRecordHellosService binds RecordHellosService to ctx; its Logger carries ctx's trace ids.
func NewRecordHellosService(ctx context.Context, svcCtx *svccontext.ServiceContext) *RecordHellosService {
	return &RecordHellosService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// RecordHellos counts the greetings the client streams in.
//
// RecordHellos reads requests with stream.Recv until io.EOF, then answers with stream.SendAndClose.
func (l *RecordHellosService) RecordHellos(stream grpc.ClientStreamingServer[pb.HelloRequest, pb.HelloReply]) error {
	n := 0
	for {
		_, err := stream.Recv()
		if errors.Is(err, io.EOF) {
			return stream.SendAndClose(&pb.HelloReply{Message: fmt.Sprintf("recorded %d greetings", n)})
		}
		if err != nil {
			return err
		}
		n++
	}
}
