// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package greet

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	pb "github.com/craftgodotdev/craftgo/example/grpc/internal/pb/greet"
	"github.com/craftgodotdev/craftgo/example/grpc/svccontext"
)

// SayHelloService runs Greeter.SayHello for one request.
type SayHelloService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewSayHelloService binds SayHelloService to ctx; its Logger carries ctx's trace ids.
func NewSayHelloService(ctx context.Context, svcCtx *svccontext.ServiceContext) *SayHelloService {
	return &SayHelloService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// SayHello answers one greeting.
//
// SayHello implements Greeter.SayHello.
func (l *SayHelloService) SayHello(req *pb.HelloRequest) (*pb.HelloReply, error) {
	if req.GetName() == "" {
		return nil, status.Error(codes.InvalidArgument, "name is required")
	}
	l.Info("greeting", log.String("name", req.GetName()))
	return &pb.HelloReply{Message: "hello " + req.GetName()}, nil
}
