// Code generated by craftgo. DO NOT EDIT.

package tasks

import (
	"context"

	craftevents "github.com/craftgodotdev/craftgo/pkg/events"

	types "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/tasks"
)

// Contract names for the events TaskService publishes. Publisher and
// consumer both address a contract by this value.
const (
	// TaskCreatedContract is the wire identity of TaskService.TaskCreated.
	TaskCreatedContract = "tasks.TaskCreated"
	// TaskStatusChangedContract is the wire identity of TaskService.TaskStatusChanged.
	TaskStatusChangedContract = "tasks.TaskStatusChanged"
)

// Publisher publishes the events TaskService declares.
type Publisher struct {
	bus  *craftevents.Bus
	opts []craftevents.PublishOption
}

// NewPublisher binds a Publisher to bus. opts are this publisher's
// defaults - a tenant header, a key derived the same way every time -
// applied to every message before the options of the call itself, so a
// per-call option of the same kind wins.
func NewPublisher(bus *craftevents.Bus, opts ...craftevents.PublishOption) *Publisher {
	return &Publisher{bus: bus, opts: opts}
}

// PublishTaskCreated publishes TaskService.TaskCreated as tasks.TaskCreated.
// Pass craftevents.WithKey(...) to order this message against others
// about the same entity; see the craftevents.PublishOption docs for the
// rest.
func (p *Publisher) PublishTaskCreated(ctx context.Context, payload *types.TaskCreated, opts ...craftevents.PublishOption) error {
	return p.bus.Publish(ctx, TaskCreatedContract, payload, craftevents.JoinOptions(p.opts, opts)...)
}

// PublishTaskStatusChanged publishes TaskService.TaskStatusChanged as tasks.TaskStatusChanged.
// Pass craftevents.WithKey(...) to order this message against others
// about the same entity; see the craftevents.PublishOption docs for the
// rest.
func (p *Publisher) PublishTaskStatusChanged(ctx context.Context, payload *types.TaskStatusChanged, opts ...craftevents.PublishOption) error {
	return p.bus.Publish(ctx, TaskStatusChangedContract, payload, craftevents.JoinOptions(p.opts, opts)...)
}

// Batch appends TaskService's events to a batch the caller publishes in
// one call. Obtain it from `svcCtx.Events.Batch()`; a batch may mix the
// contracts of several services, which is what an outbox drains.
type Batch struct {
	envs *[]craftevents.Envelope
	opts []craftevents.PublishOption
}

// TaskCreated adds TaskService.TaskCreated to the batch.
func (b Batch) TaskCreated(payload *types.TaskCreated, opts ...craftevents.PublishOption) Batch {
	env := craftevents.Envelope{Event: TaskCreatedContract, Payload: payload}
	env.Apply(craftevents.JoinOptions(b.opts, opts)...)
	*b.envs = append(*b.envs, env)
	return b
}

// TaskStatusChanged adds TaskService.TaskStatusChanged to the batch.
func (b Batch) TaskStatusChanged(payload *types.TaskStatusChanged, opts ...craftevents.PublishOption) Batch {
	env := craftevents.Envelope{Event: TaskStatusChangedContract, Payload: payload}
	env.Apply(craftevents.JoinOptions(b.opts, opts)...)
	*b.envs = append(*b.envs, env)
	return b
}

// NewBatch binds a Batch to the caller's envelope slice. opts are the
// defaults every entry starts from, the same ones [NewPublisher] takes.
func NewBatch(envs *[]craftevents.Envelope, opts ...craftevents.PublishOption) Batch {
	return Batch{envs: envs, opts: opts}
}
