// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package middleware

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"
)

// AuthRequired enforces a Bearer token on every request flowing
// through it. The canonical no-arg middleware: behaviour is fixed,
// configuration (token lifetime, issuer, audience) lives in
// svccontext / config, not in the DSL contract.
//
// NewAuthRequiredMiddleware returns the AuthRequired middleware, which ServiceContext's AuthRequired field holds.
func NewAuthRequiredMiddleware() server.Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// TODO: implement
			next.ServeHTTP(w, r)
		})
	}
}
