// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package middleware

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"
)

// BasicAuth is an alternative auth strategy used by the
// `@ignoreMiddleware + @middlewares(...)` reset-and-replace pattern
// in `services/ignore_pattern.craftgo`. Body of the middleware is
// scaffolded; behaviour (Authorization header parse, credential
// lookup, ...) lives in the generated impl file.
//
// NewBasicAuthMiddleware returns the BasicAuth middleware, which ServiceContext's BasicAuth field holds.
func NewBasicAuthMiddleware() server.Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// TODO: implement
			next.ServeHTTP(w, r)
		})
	}
}
