// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package middleware

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"
)

// RateLimit applies a token-bucket per remote IP. The concrete refill
// rate, burst size, and storage backend are choices the user makes
// inside the generated impl file - the DSL only reserves the slot.
//
// NewRateLimitMiddleware returns the RateLimit middleware, which ServiceContext's RateLimit field holds.
func NewRateLimitMiddleware() server.Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// TODO: implement
			next.ServeHTTP(w, r)
		})
	}
}
