// Code generated by craftgo. DO NOT EDIT.

package hidden

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/hidden_notes"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/hidden"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Peek returns the GET Peek handler.
func Peek(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.Stash
		_q := r.URL.Query()
		if !server.RequirePresent(w, r, _q.Has("tier"), "tier", "query") {
			return
		}
		req.Tier = types.Tier(_q.Get("tier"))
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewPeekService(r.Context(), svcCtx)
		resp, err := l.Peek(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusOK, resp)
	}
}
