// Code generated by craftgo. DO NOT EDIT.

package orderservice

import (
	"encoding/json"
	"github.com/dropship-dev/craftgo/pkg/server"
	"net/http"

	logic "github.com/dropship-dev/craftgo/example/internal/logic/order-service"
	types "github.com/dropship-dev/craftgo/example/internal/types/orders"
	"github.com/dropship-dev/craftgo/example/svccontext"
)

// GetOrderHandler returns the http.HandlerFunc for the
// GET GetOrder endpoint.
func GetOrderHandler(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetOrderReq
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := logic.NewGetOrderLogic(r.Context(), svcCtx)
		resp, err := l.GetOrder(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
