// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package nested

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/nested"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// EchoOrgService runs NestedService.EchoOrg for one request.
type EchoOrgService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewEchoOrgService binds EchoOrgService to ctx; its Logger carries ctx's trace ids.
func NewEchoOrgService(ctx context.Context, svcCtx *svccontext.ServiceContext) *EchoOrgService {
	return &EchoOrgService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Optional slice of nested.
//
// EchoOrg implements NestedService.EchoOrg.
func (l *EchoOrgService) EchoOrg(req *types.Org) (*types.Org, error) {
	// TODO: implement
	return nil, nil
}
