// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package nested

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/nested"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// EchoTeamService runs NestedService.EchoTeam for one request.
type EchoTeamService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewEchoTeamService binds EchoTeamService to ctx; its Logger carries ctx's trace ids.
func NewEchoTeamService(ctx context.Context, svcCtx *svccontext.ServiceContext) *EchoTeamService {
	return &EchoTeamService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Slice of nested with array-level bounds.
//
// EchoTeam implements NestedService.EchoTeam.
func (l *EchoTeamService) EchoTeam(req *types.Team) (*types.Team, error) {
	// TODO: implement
	return nil, nil
}
