// Code generated by craftgo. DO NOT EDIT.

package userservice

import (
	"encoding/json"
	"github.com/dropship-dev/craftgo/pkg/server"
	"net/http"

	logic "github.com/dropship-dev/craftgo/example/internal/logic/user-service"
	types "github.com/dropship-dev/craftgo/example/internal/types/users"
	"github.com/dropship-dev/craftgo/example/svccontext"
)

// RestoreUser is the inverse of SuspendUser. The same chain +
// scope rules apply. Note the request type is reused from
// service.craftgo's GetUserReq — extend blocks share the
// package's full type table.
// RestoreUserHandler returns the http.HandlerFunc for the
// POST RestoreUser endpoint.
func RestoreUserHandler(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.GetUserReq
		req.ID = r.PathValue("id")
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := logic.NewRestoreUserLogic(r.Context(), svcCtx)
		resp, err := l.RestoreUser(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
