// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package orderservice

import (
	"context"

	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/orders"
	shared "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/shared"

	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// CancelOrderService carries the per-request state for the
// CancelOrder endpoint of OrderService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type CancelOrderService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewCancelOrderService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewCancelOrderService(ctx context.Context, svcCtx *svccontext.ServiceContext) *CancelOrderService {
	return &CancelOrderService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// CancelOrder is the service entry point. Replace the
// TODO with the real implementation.
func (l *CancelOrderService) CancelOrder(req *types.GetOrderReq) (*shared.OkResp, error) {
	// TODO: implement
	return nil, nil
}
