// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package orderservice

import (
	"context"

	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/orders"
	shared "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/shared"

	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// FilterOrdersService carries the per-request state for the
// FilterOrders endpoint of OrderService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type FilterOrdersService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewFilterOrdersService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewFilterOrdersService(ctx context.Context, svcCtx *svccontext.ServiceContext) *FilterOrdersService {
	return &FilterOrdersService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// FilterOrders is the service entry point. Replace the
// TODO with the real implementation.
func (l *FilterOrdersService) FilterOrders(req *types.FilterOrdersReq) (*shared.Page[types.Order], error) {
	// TODO: implement
	return nil, nil
}
