// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package orderservice

import (
	"context"

	types "github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/orders"

	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// ForceShipService carries the per-request state for the
// ForceShip endpoint of OrderService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type ForceShipService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewForceShipService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewForceShipService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ForceShipService {
	return &ForceShipService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// ForceShip is the service entry point. Replace the
// TODO with the real implementation.
func (l *ForceShipService) ForceShip(req *types.GetOrderReq) (*types.Order, error) {
	// TODO: implement
	return nil, nil
}
