// Code generated by craftgo. DO NOT EDIT.

package adminapi

import (
	"github.com/craftgodotdev/craftgo/pkg/server"

	transportAdminV1 "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/transport/admin/v1"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RegisterRoutes registers the AdminApi routes of group admin/v1 on srv.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api/adminapi/v1/ping", transportAdminV1.PingV1(svcCtx))
	srv.Handle("GET /api/adminapi/inherit/ping", transportAdminV1.PingInherit(svcCtx))
}
