// Code generated by craftgo. DO NOT EDIT.

package server

import (
	"fmt"
	"unicode/utf8"
)

// Validate returns the first constraint v violates, or nil.
func (v *Credentials) Validate() error {
	if err := v.Session.Validate(); err != nil {
		return fmt.Errorf("session: %w", err)
	}
	if v.Channel != nil {
		if err := v.Channel.Validate(); err != nil {
			return fmt.Errorf("channel: %w", err)
		}
	}
	if utf8.RuneCountInString(v.User) < 1 {
		return fmt.Errorf("user: length less than 1")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v SessionID) Validate() error {
	if utf8.RuneCountInString(string(v)) < 1 {
		return fmt.Errorf("length less than 1")
	}
	return nil
}

// Validate returns the first constraint v violates, or nil.
func (v Channel) Validate() error {
	switch v {
	case ChannelWeb, ChannelMobile:
	default:
		return fmt.Errorf("must be one of [Web Mobile]")
	}
	return nil
}
