// Code generated by craftgo. DO NOT EDIT.

package notifications

import (
	"context"

	craftevents "github.com/craftgodotdev/craftgo/pkg/events"

	orders "github.com/craftgodotdev/craftgo/example/brokers/internal/types/orders"
)

// Consumers is the handler set NotificationService must supply for the contracts
// it consumes. Implement it and hand it to [Subscriptions]; nothing here
// depends on the application that hosts the bus.
type Consumers interface {
	SendReceipt(ctx context.Context, payload *orders.OrderPlaced) error

	SendDispatchNote(ctx context.Context, payload *orders.OrderShipped) error
}

// Subscriptions binds h to bus, one subscription per contract NotificationService
// consumes. The payload is decoded with the bus codec and validated before
// a handler sees it; one that fails either never reaches the handler and
// comes back as a [craftevents.PayloadError] naming the contract.
func Subscriptions(bus *craftevents.Bus, h Consumers) []craftevents.Subscription {
	return []craftevents.Subscription{
		{
			Event:    "orders.Placed",
			Consumer: "SendReceipt",
			Group:    "notifications-NotificationService-SendReceipt",
			Handle: func(ctx context.Context, msg *craftevents.Message) error {
				var payload orders.OrderPlaced
				if err := bus.Decode(msg, &payload); err != nil {
					return err
				}
				if err := payload.Validate(); err != nil {
					return &craftevents.PayloadError{Event: "orders.Placed", Err: err}
				}
				return h.SendReceipt(ctx, &payload)
			},
		},
		{
			Event:    "orders.Shipped",
			Consumer: "SendDispatchNote",
			Group:    "notifications-NotificationService-SendDispatchNote",
			Handle: func(ctx context.Context, msg *craftevents.Message) error {
				var payload orders.OrderShipped
				if err := bus.Decode(msg, &payload); err != nil {
					return err
				}
				if err := payload.Validate(); err != nil {
					return &craftevents.PayloadError{Event: "orders.Shipped", Err: err}
				}
				return h.SendDispatchNote(ctx, &payload)
			},
		},
	}
}
