// Code generated by craftgo. DO NOT EDIT.

package runtime

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/orders_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Latest returns the GET Latest handler.
func Latest(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewLatestService(r.Context(), svcCtx)
		resp, err := l.Latest()
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusOK, resp)
	}
}
