// Code generated by craftgo. DO NOT EDIT.

package ordersservice

import (
	"encoding/json"
	"net/http"

	service "github.com/dropship-dev/craftgo/tests/e2e/multi-service/internal/service/orders-service"
	"github.com/dropship-dev/craftgo/tests/e2e/multi-service/svccontext"
)

// Latest returns the most recently placed order.
// Latest returns the http.HandlerFunc for the
// GET Latest endpoint.
func Latest(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewLatestService(r.Context(), svcCtx)
		resp, err := l.Latest()
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
