// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package xrefs

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/xshared"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// GetThirdService runs XRefsService.GetThird for one request.
type GetThirdService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewGetThirdService binds GetThirdService to ctx; its Logger carries ctx's trace ids.
func NewGetThirdService(ctx context.Context, svcCtx *svccontext.ServiceContext) *GetThirdService {
	return &GetThirdService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Pins a QUALIFIED request whose field reaches a THIRD package (xshared.XThirdReq.sev is shared.Severity). The xrefs handler casts shared.Severity(...), so the import collector must resolve the qualified request and pull in `shared` - else `undefined: shared`. Also pins an error (XMixinErr) whose body embeds a cross-package mixin, so the error emitter's import walk must collect xshared.
//
// GetThird implements XRefsService.GetThird.
func (l *GetThirdService) GetThird(req *xshared.XThirdReq) (*xshared.XOwner, error) {
	// TODO: implement
	return nil, nil
}
