// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package xrefs

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/xrefs"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/xshared"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// PostDefaultService runs XRefsService.PostDefault for one request.
type PostDefaultService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewPostDefaultService binds PostDefaultService to ctx; its Logger carries ctx's trace ids.
func NewPostDefaultService(ctx context.Context, svcCtx *svccontext.ServiceContext) *PostDefaultService {
	return &PostDefaultService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Pins cross-package enum `@default` pre-fill in transport. Body decode must seed `req.Color = &__d` with `__d := xshared.XColorRed` before JSON.Decode runs; without resolver the default literal silently drops because the local pkg.Enums miss.
//
// PostDefault implements XRefsService.PostDefault.
func (l *PostDefaultService) PostDefault(req *types.XEnumDefault) (*xshared.XOwner, error) {
	// TODO: implement
	return nil, nil
}
