// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package xrefs

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/xrefs"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/xshared"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// WrapLocalService runs XRefsService.WrapLocal for one request.
type WrapLocalService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewWrapLocalService binds WrapLocalService to ctx; its Logger carries ctx's trace ids.
func NewWrapLocalService(ctx context.Context, svcCtx *svccontext.ServiceContext) *WrapLocalService {
	return &WrapLocalService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Pins a QUALIFIED GENERIC request with a LOCAL type-arg (xshared.XWrapInBag<XLocalItem>). The handler renders `var req xshared.XWrapInBag[types.XLocalItem]`, so it must keep the canonical `types` import for the local arg even though the outer type is cross-package - otherwise `undefined: types`.
//
// WrapLocal implements XRefsService.WrapLocal.
func (l *WrapLocalService) WrapLocal(req *xshared.XWrapInBag[types.XLocalItem]) (*xshared.XOwner, error) {
	// TODO: implement
	return nil, nil
}
