// Code generated by craftgo. DO NOT EDIT.

package greet

import (
	pb "github.com/craftgodotdev/craftgo/example/grpc/internal/pb/greet"
	"github.com/craftgodotdev/craftgo/example/grpc/svccontext"
)

// Server implements pb.GreeterServer (greet.Greeter).
type Server struct {
	pb.UnimplementedGreeterServer
	svcCtx *svccontext.ServiceContext
}

// NewServer returns the implementation wiring.RegisterGRPC registers.
func NewServer(svcCtx *svccontext.ServiceContext) *Server {
	return &Server{svcCtx: svcCtx}
}
