// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package booksservice

import (
	"context"

	types "github.com/dropship-dev/craftgo/example/internal/types/design"

	"github.com/dropship-dev/craftgo/example/svccontext"
)

// GetBookLogic carries the per-request state for the
// GetBook endpoint of BooksService.
type GetBookLogic struct {
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewGetBookLogic constructs a fresh logic instance bound to ctx.
func NewGetBookLogic(ctx context.Context, svcCtx *svccontext.ServiceContext) *GetBookLogic {
	return &GetBookLogic{ctx: ctx, svcCtx: svcCtx}
}

// GetBook returns a single book by id.
// GetBook is the business-logic entry point. Replace the
// TODO with the real implementation.
func (l *GetBookLogic) GetBook(req *types.GetBookReq) (*types.Book, error) {
	l.svcCtx.Lock()
	defer l.svcCtx.Unlock()
	b, ok := l.svcCtx.Books[req.ID]
	if !ok {
		return nil, types.NewBookNotFoundErr()
	}
	return &types.Book{
		ID: b.ID, Title: b.Title, Author: b.Author, Isbn: b.ISBN,
		PriceCents: b.PriceCents, Stock: b.Stock,
	}, nil
}
