// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package shared

import (
	"context"

	types "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/tasks"

	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// SetTaskStatusService carries the per-request state for the
// SetTaskStatus endpoint of TaskService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type SetTaskStatusService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewSetTaskStatusService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewSetTaskStatusService(ctx context.Context, svcCtx *svccontext.ServiceContext) *SetTaskStatusService {
	return &SetTaskStatusService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// SetTaskStatus is the service entry point. Replace the
// TODO with the real implementation.
func (l *SetTaskStatusService) SetTaskStatus(req *types.SetTaskStatusReq) (*types.Task, error) {
	return l.svcCtx.Store.SetTaskStatus(req.ProjectID, req.ID, req.Status)
}
