// Code generated by craftgo. DO NOT EDIT.

package catalog

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/example/ecommerce/internal/service/catalog_service"
	"github.com/craftgodotdev/craftgo/example/ecommerce/internal/types/shared"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
)

// List categories.
//
// ListCategories returns the GET ListCategories handler.
func ListCategories(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req shared.Pagination
		_q := r.URL.Query()
		if _v := _q.Get("cursor"); _v != "" {
			req.Cursor = &_v
		}
		if !server.RequirePresent(w, r, _q.Has("limit"), "limit", "query") {
			return
		}
		if !server.BindValue(w, r, "limit", "int", _q.Get("limit"), &req.Limit, server.ParseSigned[int]) {
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewListCategoriesService(r.Context(), svcCtx)
		resp, err := l.ListCategories(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		server.WriteResponse(w, r, http.StatusOK, resp)
	}
}
