// Code generated by craftgo. DO NOT EDIT.

package regressionbatch5

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/regression-batch5"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/regression"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// EchoComposite returns the http.HandlerFunc for the
// POST EchoComposite endpoint.
func EchoComposite(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.Rg5Composite
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewEchoCompositeService(r.Context(), svcCtx)
		resp, err := l.EchoComposite(&req)
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
