// Code generated by craftgo. DO NOT EDIT.

package bindings

import (
	"fmt"
	"net/mail"
	"net/url"
	"regexp"
)

// Validate checks every field-level constraint declared on AddItemReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *AddItemReq) Validate() error {
	if l := len(v.Name); l < 1 || l > 200 {
		return fmt.Errorf("name: length out of range [1, 200]")
	}
	if v.Price < 0 {
		return fmt.Errorf("price: below minimum 0")
	}
	if v.Price > 1000000 {
		return fmt.Errorf("price: above maximum 1000000")
	}
	if v.Notes != nil && len(*v.Notes) > 2000 {
		return fmt.Errorf("notes: length greater than 2000")
	}
	return nil
}

// Validate checks every field-level constraint declared on BodyExplicitReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *BodyExplicitReq) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on CookieReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *CookieReq) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on FormFileReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *FormFileReq) Validate() error {
	if l := len(v.ID); l < 1 || l > 64 {
		return fmt.Errorf("id: length out of range [1, 64]")
	}
	if v.File == nil {
		return fmt.Errorf("file: required")
	}
	if v.File != nil && v.File.Size > 5242880 {
		return fmt.Errorf("file: file size exceeds 5242880 bytes")
	}
	if v.File != nil {
		switch v.File.Header.Get("Content-Type") {
		case "image/png", "image/jpeg":
		default:
			return fmt.Errorf("file: disallowed content type")
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on GetItemReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *GetItemReq) Validate() error {
	if !regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`).MatchString(v.ID) {
		return fmt.Errorf("id: not a valid UUID")
	}
	return nil
}

// Validate checks every field-level constraint declared on HeaderOptionalReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *HeaderOptionalReq) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on HeaderReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *HeaderReq) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on Item.
// Returns the first violation; nil when the value satisfies the contract.
func (v *Item) Validate() error {
	if !regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`).MatchString(v.ID) {
		return fmt.Errorf("id: not a valid UUID")
	}
	if l := len(v.Name); l < 1 || l > 200 {
		return fmt.Errorf("name: length out of range [1, 200]")
	}
	if v.Price < 0 {
		return fmt.Errorf("price: below minimum 0")
	}
	return nil
}

// Validate checks every field-level constraint declared on ItemList.
// Returns the first violation; nil when the value satisfies the contract.
func (v *ItemList) Validate() error {
	for i0 := range v.Items {
		if err := v.Items[i0].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on PathEnumReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *PathEnumReq) Validate() error {
	if v.C == "" {
		return fmt.Errorf("c: required")
	}
	switch v.C {
	case ColorRed, ColorGreen, ColorBlue:
	default:
		return fmt.Errorf("c: invalid Color value")
	}
	return nil
}

// Validate checks every field-level constraint declared on PathExplicitNameReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *PathExplicitNameReq) Validate() error {
	if l := len(v.UserID); l < 1 || l > 64 {
		return fmt.Errorf("userId: length out of range [1, 64]")
	}
	return nil
}

// Validate checks every field-level constraint declared on PathScalarReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *PathScalarReq) Validate() error {
	if !regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`).MatchString(v.ID) {
		return fmt.Errorf("id: not a valid UUID")
	}
	return nil
}

// Validate checks every field-level constraint declared on PathStringReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *PathStringReq) Validate() error {
	if l := len(v.ID); l < 1 || l > 64 {
		return fmt.Errorf("id: length out of range [1, 64]")
	}
	return nil
}

// Validate checks every field-level constraint declared on QueryArrayIntReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *QueryArrayIntReq) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on QueryArrayStringReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *QueryArrayStringReq) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on QueryBoolReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *QueryBoolReq) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on QueryEnumReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *QueryEnumReq) Validate() error {
	if v.C != nil {
		switch *v.C {
		case ColorRed, ColorGreen, ColorBlue:
		default:
			return fmt.Errorf("c: invalid Color value")
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on QueryIntRequiredReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *QueryIntRequiredReq) Validate() error {
	if v.Page < 1 {
		return fmt.Errorf("page: below minimum 1")
	}
	return nil
}

// Validate checks every field-level constraint declared on QueryRequiredReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *QueryRequiredReq) Validate() error {
	if v.Limit < 1 {
		return fmt.Errorf("limit: below minimum 1")
	}
	if v.Limit > 100 {
		return fmt.Errorf("limit: above maximum 100")
	}
	return nil
}

// Validate checks every field-level constraint declared on QueryStringReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *QueryStringReq) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on SearchReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *SearchReq) Validate() error {
	if v.Limit < 1 {
		return fmt.Errorf("limit: below minimum 1")
	}
	if v.Limit > 100 {
		return fmt.Errorf("limit: above maximum 100")
	}
	if v.Sort != nil {
		switch *v.Sort {
		case ColorRed, ColorGreen, ColorBlue:
		default:
			return fmt.Errorf("sort: invalid Color value")
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on UploadReq.
// Returns the first violation; nil when the value satisfies the contract.
func (v *UploadReq) Validate() error {
	if l := len(v.ID); l < 1 || l > 64 {
		return fmt.Errorf("id: length out of range [1, 64]")
	}
	if v.File == nil {
		return fmt.Errorf("file: required")
	}
	if v.File != nil && v.File.Size > 5242880 {
		return fmt.Errorf("file: file size exceeds 5242880 bytes")
	}
	if v.File != nil {
		switch v.File.Header.Get("Content-Type") {
		case "image/png", "image/jpeg":
		default:
			return fmt.Errorf("file: disallowed content type")
		}
	}
	return nil
}

// Validate checks every field-level constraint declared on UserAvatar.
// Returns the first violation; nil when the value satisfies the contract.
func (v *UserAvatar) Validate() error {
	if _u, _err := url.Parse(v.URL); _err != nil || (_u.Scheme != "http" && _u.Scheme != "https") {
		return fmt.Errorf("url: not a valid URL")
	}
	if len(v.URL) > 2048 {
		return fmt.Errorf("url: length greater than 2048")
	}
	if l := len(v.Key); l < 1 || l > 256 {
		return fmt.Errorf("key: length out of range [1, 256]")
	}
	return nil
}

// Validate checks every field-level constraint declared on AccessDeniedBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *AccessDeniedBody) Validate() error {
	if len(v.Reason) < 1 {
		return fmt.Errorf("reason: length less than 1")
	}
	return nil
}

// Validate checks every field-level constraint declared on AuthRequiredBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *AuthRequiredBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on DuplicateKeyBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *DuplicateKeyBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on EmailTakenBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *EmailTakenBody) Validate() error {
	if _, _err := mail.ParseAddress(v.Email); _err != nil {
		return fmt.Errorf("email: not a valid email")
	}
	return nil
}

// Validate checks every field-level constraint declared on InvalidInputBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *InvalidInputBody) Validate() error {
	return nil
}

// Validate checks every field-level constraint declared on RateLimitExceededBody.
// Returns the first violation; nil when the value satisfies the contract.
func (v *RateLimitExceededBody) Validate() error {
	if v.RetryAfter < 1 {
		return fmt.Errorf("retryAfter: below minimum 1")
	}
	return nil
}
