// Code generated by craftgo. DO NOT EDIT.

package numbersservice

import (
	"encoding/json"
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/service/numbers-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/numbers"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// AddBoundary returns the http.HandlerFunc for the
// POST AddBoundary endpoint.
func AddBoundary(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.BoundaryReq
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewAddBoundaryService(r.Context(), svcCtx)
		resp, err := l.AddBoundary(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
	}
}
