// Code generated by craftgo. DO NOT EDIT.

package numbersservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/service/numbers-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/numbers"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// AddUnsigned returns the http.HandlerFunc for the
// POST AddUnsigned endpoint.
func AddUnsigned(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.UnsignedReq
		if err := server.JSON().Decode(r.Body, &req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewAddUnsignedService(r.Context(), svcCtx)
		resp, err := l.AddUnsigned(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
