// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package eventsubs

import (
	"context"

	events "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/events"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// TrackStocktakeConsumer carries the per-message state for the TrackStocktake
// consumer of NotificationService. The embedded log.Logger is bound to the
// delivery context; whether that context carries a trace depends on the
// transport - the in-process one starts a fresh context per message.
type TrackStocktakeConsumer struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewTrackStocktakeConsumer constructs a fresh consumer instance bound to ctx.
func NewTrackStocktakeConsumer(ctx context.Context, svcCtx *svccontext.ServiceContext) *TrackStocktakeConsumer {
	return &TrackStocktakeConsumer{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// TrackStocktake handles events.StocktakeStarted, recording the payload so the
// fixture's round-trip test can assert on what reached logic.
func (l *TrackStocktakeConsumer) TrackStocktake(payload *events.StocktakeStarted) error {
	l.svcCtx.Record("TrackStocktake", payload)
	return nil
}
