// Code generated by craftgo. DO NOT EDIT.

package orders

type GeoSource string

const (
	GeoSourceGps  GeoSource = "gps"
	GeoSourceCell GeoSource = "cell"
	GeoSourceWiFi GeoSource = "wifi"
	GeoSourceIP   GeoSource = "ip"
)

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusShipped   OrderStatus = "shipped"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusCancelled OrderStatus = "cancelled"
)

type PaymentMethod string

const (
	PaymentMethodCard    PaymentMethod = "card"
	PaymentMethodBank    PaymentMethod = "bank"
	PaymentMethodWallet  PaymentMethod = "wallet"
	PaymentMethodInvoice PaymentMethod = "invoice"
)
