// Code generated by craftgo. DO NOT EDIT.

package orderservice

import (
	transport "github.com/craftgodotdev/craftgo/example/ecommerce/internal/transport/order-service"
	"github.com/craftgodotdev/craftgo/example/ecommerce/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/server"
)

// RegisterRoutes wires every OrderService endpoint onto srv. Patterns
// use the Go 1.22 method-prefixed form so VERB and path match together;
// service prefix and OpenAPI basePath are baked in. Methods declaring
// `@middlewares(...)` are wrapped via the corresponding fields on
// ServiceContext (embedded Middlewares struct), so no runtime name
// lookup is required - the values come pre-wired.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api/orders/list-orders", transport.ListOrders(svcCtx), svcCtx.RequestID, svcCtx.RateLimit, svcCtx.CORS, svcCtx.AuthRequired)
	srv.Handle("GET /api/orders/{id}", transport.GetOrder(svcCtx), svcCtx.RequestID, svcCtx.RateLimit, svcCtx.CORS, svcCtx.AuthRequired)
	srv.Handle("POST /api/orders", transport.CreateOrder(svcCtx), svcCtx.RequestID, svcCtx.RateLimit, svcCtx.CORS, svcCtx.AuthRequired)
	srv.Handle("GET /api/orders/by-status/{status}", transport.FilterOrders(svcCtx), svcCtx.RequestID, svcCtx.RateLimit, svcCtx.CORS, svcCtx.AuthRequired)
	srv.Handle("POST /api/orders/defaults", transport.Defaults(svcCtx), svcCtx.RequestID, svcCtx.RateLimit, svcCtx.CORS, svcCtx.AuthRequired)
	srv.Handle("POST /api/orders/{id}/cancel", transport.CancelOrder(svcCtx), svcCtx.RequestID, svcCtx.RateLimit, svcCtx.CORS, svcCtx.AuthRequired, svcCtx.BodyLimit, svcCtx.Timeout)
	srv.Handle("POST /api/orders/{id}/ship", transport.ForceShip(svcCtx), svcCtx.RequestID, svcCtx.RateLimit, svcCtx.CORS, svcCtx.AuthRequired, svcCtx.BodyLimit, svcCtx.Timeout)
	srv.Handle("GET /api/orders/health", transport.PublicHealth(svcCtx))
	srv.Handle("GET /api/orders/{id}/track", transport.TrackPublic(svcCtx), svcCtx.CORS, svcCtx.RequestID)
	srv.Handle("POST /api/orders/export", transport.BulkExport(svcCtx), svcCtx.RequestID, svcCtx.RateLimit, svcCtx.CORS, svcCtx.AuthRequired, svcCtx.BodyLimit, svcCtx.Timeout)
	srv.Handle("POST /api/orders/{id}/replay", transport.Replay(svcCtx), svcCtx.RequestID, svcCtx.RateLimit, svcCtx.CORS, svcCtx.AuthRequired)
}
