// Code generated by craftgo. DO NOT EDIT.

package userservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	"net/http"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/user-service"
	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/services"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ListUsers returns the http.HandlerFunc for the
// GET ListUsers endpoint.
func ListUsers(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.ListUsersReq
		{
			__d := 20
			req.Limit = &__d
		}
		_q := r.URL.Query()
		if !server.BindValuePtr(w, r, "limit", "int", _q.Get("limit"), &req.Limit, server.ParseSigned[int]) {
			return
		}
		if _v := _q.Get("cursor"); _v != "" {
			req.Cursor = &_v
		}
		if !server.BindValuePtr(w, r, "total", "int", _q.Get("total"), &req.Total, server.ParseSigned[int]) {
			return
		}
		if _v := _q.Get("query"); _v != "" {
			req.Query = &_v
		}
		if err := req.Validate(); err != nil {
			server.WriteValidationError(w, r, err)
			return
		}
		l := service.NewListUsersService(r.Context(), svcCtx)
		resp, err := l.ListUsers(&req)
		if err != nil {
			writeError(w, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = server.JSON().Encode(w, resp)
	}
}
