// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package collections

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/collections"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// MapKeyValueService runs Collections.MapKeyValue for one request.
type MapKeyValueService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewMapKeyValueService binds MapKeyValueService to ctx; its Logger carries ctx's trace ids.
func NewMapKeyValueService(ctx context.Context, svcCtx *svccontext.ServiceContext) *MapKeyValueService {
	return &MapKeyValueService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// MapKeyValue is the scalar-on-both-sides map case.
//
// MapKeyValue implements Collections.MapKeyValue.
func (l *MapKeyValueService) MapKeyValue(req *types.Map_KeyAndValue) (*types.Map_KeyAndValue, error) {
	// TODO: implement
	return nil, nil
}
