// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package combine

import (
	"context"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/combine"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// TagPairsService carries the per-request state for the
// TagPairs endpoint of CombineService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type TagPairsService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewTagPairsService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewTagPairsService(ctx context.Context, svcCtx *svccontext.ServiceContext) *TagPairsService {
	return &TagPairsService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// TagPairs is the service entry point. Replace the
// TODO with the real implementation.
func (l *TagPairsService) TagPairs(req *types.PairsDoc) (*types.PairsTagged, error) {
	// TODO: implement
	return nil, nil
}
