// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package combine

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/combine"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// UploadSourceService runs CombineService.UploadSource for one request.
type UploadSourceService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewUploadSourceService binds UploadSourceService to ctx; its Logger carries ctx's trace ids.
func NewUploadSourceService(ctx context.Context, svcCtx *svccontext.ServiceContext) *UploadSourceService {
	return &UploadSourceService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Upload a file or a link, exactly one. The multipart body carries the request type's own groups; an empty url part counts as absent.
//
// UploadSource implements CombineService.UploadSource.
func (l *UploadSourceService) UploadSource(req *types.PairsSource) (*types.PairsDoc, error) {
	// TODO: implement
	return nil, nil
}
