// Code generated by craftgo. DO NOT EDIT.

package analytics

import (
	"context"
	"errors"
	"fmt"

	craftevents "github.com/craftgodotdev/craftgo/pkg/events"

	ordersevents "github.com/craftgodotdev/craftgo/example/brokers/internal/events/orders"
	orders "github.com/craftgodotdev/craftgo/example/brokers/internal/types/orders"
)

// AnalyticsServiceHandler is the application side of AnalyticsService.
// One method per `consume` the design declares; the payload is decoded
// and validated before a method runs.
type AnalyticsServiceHandler interface {
	CountOrder(ctx context.Context, payload *orders.OrderPlaced) error
}

// AnalyticsServiceGroups names the broker identity each consume joins.
// A field left empty falls back to Default. The names are the
// application's to choose - a group is where a consumer resumes, and two
// deployables of one design need not agree on it.
type AnalyticsServiceGroups struct {
	Default    craftevents.Group
	CountOrder craftevents.Group
}

func (g AnalyticsServiceGroups) group(own craftevents.Group) craftevents.Group {
	if own != "" {
		return own
	}
	return g.Default
}

// RegisterAnalyticsServiceHandler registers one subscription per consume,
// each behind chain. Nothing is delivered until [craftevents.Bus.Start].
func RegisterAnalyticsServiceHandler(bus *craftevents.Bus, h AnalyticsServiceHandler, chain craftevents.Chain, groups AnalyticsServiceGroups) error {
	if groups.Default == "" && groups.CountOrder == "" {
		return errors.New("events: every consume of AnalyticsService needs a group - set AnalyticsServiceGroups.Default, or one field per consume")
	}
	if err := bus.Register(ordersevents.Placed.Subscription(bus, "CountOrder", groups.group(groups.CountOrder), chain, h.CountOrder)); err != nil {
		return fmt.Errorf("AnalyticsService.CountOrder: %w", err)
	}
	return nil
}
