// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package bindings

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/bindings"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// GetSessionCookieService runs BindingsService.GetSessionCookie for one request.
type GetSessionCookieService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewGetSessionCookieService binds GetSessionCookieService to ctx; its Logger carries ctx's trace ids.
func NewGetSessionCookieService(ctx context.Context, svcCtx *svccontext.ServiceContext) *GetSessionCookieService {
	return &GetSessionCookieService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// GetSessionCookie implements BindingsService.GetSessionCookie.
func (l *GetSessionCookieService) GetSessionCookie(req *types.SessionCookieReq) (*types.DoneResp, error) {
	// TODO: implement
	return nil, nil
}
