// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package bindings

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/bindings"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// ListPageService runs BindingsService.ListPage for one request.
type ListPageService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewListPageService binds ListPageService to ctx; its Logger carries ctx's trace ids.
func NewListPageService(ctx context.Context, svcCtx *svccontext.ServiceContext) *ListPageService {
	return &ListPageService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// List one page of items. `pageSize` rides the query string; a value below its bound is reported as pageSize.
//
// ListPage implements BindingsService.ListPage.
func (l *ListPageService) ListPage(req *types.PageReq) (*types.ItemList, error) {
	// TODO: implement
	return nil, nil
}
