// Code generated by craftgo. DO NOT EDIT.

package securedservice

import (
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/server"

	service "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/service/secured-service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// Quarantine exercises the array-shortcut form: `@security([A, B])`
// is the bracket-wrapped sugar that any variadic decorator accepts.
// It parses identical to `@security(A, B)`, so the generated
// OpenAPI security[] entry must look exactly like Wipe's
// AdminBearer+MFA AND-combination once the inherited service-level
// `@security(AdminBearer)` is layered in.
// Quarantine returns the http.HandlerFunc for the
// POST Quarantine endpoint.
func Quarantine(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewQuarantineService(r.Context(), svcCtx)
		resp, err := l.Quarantine()
		if err != nil {
			server.WriteError(w, r, err)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
		_ = server.JSON().Encode(w, resp)
	}
}
