// Code generated by craftgo. DO NOT EDIT.

package svccontext

import "github.com/craftgodotdev/craftgo/pkg/server"

// AuthRequiredMiddleware is the AuthRequired middleware.
type AuthRequiredMiddleware = server.Middleware

// BodyLimitMiddleware is the BodyLimit middleware.
type BodyLimitMiddleware = server.Middleware

// CORSMiddleware is the CORS middleware.
type CORSMiddleware = server.Middleware

// RateLimitMiddleware is the RateLimit middleware.
type RateLimitMiddleware = server.Middleware

// RequestIDMiddleware is the RequestID middleware.
type RequestIDMiddleware = server.Middleware

// TimeoutMiddleware is the Timeout middleware.
type TimeoutMiddleware = server.Middleware

// Middlewares holds one field per middleware the design declares.
type Middlewares struct {
	AuthRequired AuthRequiredMiddleware
	BodyLimit    BodyLimitMiddleware
	CORS         CORSMiddleware
	RateLimit    RateLimitMiddleware
	RequestID    RequestIDMiddleware
	Timeout      TimeoutMiddleware
}
