// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package numbersservice

import (
	"context"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/numbers"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// AddExactService carries the per-request state for the
// AddExact endpoint of NumbersService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type AddExactService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewAddExactService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewAddExactService(ctx context.Context, svcCtx *svccontext.ServiceContext) *AddExactService {
	return &AddExactService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// AddExact is the service entry point. Replace the
// TODO with the real implementation.
func (l *AddExactService) AddExact(req *types.ExactReq) (*types.ExactReq, error) {
	// TODO: implement
	return nil, nil
}
