// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package numbersservice

import (
	"context"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/numbers"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// AddOptionalService carries the per-request state for the
// AddOptional endpoint of NumbersService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type AddOptionalService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewAddOptionalService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewAddOptionalService(ctx context.Context, svcCtx *svccontext.ServiceContext) *AddOptionalService {
	return &AddOptionalService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// AddOptional is the service entry point. Replace the
// TODO with the real implementation.
func (l *AddOptionalService) AddOptional(req *types.OptionalReq) (*types.OptionalReq, error) {
	// TODO: implement
	return nil, nil
}
