// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package attachments

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/example/taskflow/internal/types/attachments"
	"github.com/craftgodotdev/craftgo/example/taskflow/svccontext"
)

// UploadAttachmentService runs AttachmentService.UploadAttachment for one request.
type UploadAttachmentService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewUploadAttachmentService binds UploadAttachmentService to ctx; its Logger carries ctx's trace ids.
func NewUploadAttachmentService(ctx context.Context, svcCtx *svccontext.ServiceContext) *UploadAttachmentService {
	return &UploadAttachmentService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Upload a file attachment to a task (image, PDF or text; ≤10MB).
//
// UploadAttachment implements AttachmentService.UploadAttachment.
func (l *UploadAttachmentService) UploadAttachment(req *types.UploadAttachmentReq) (*types.Attachment, error) {
	a := types.Attachment{
		Filename: req.File.Filename,
		Size:     int(req.File.Size),
		MimeType: req.File.Header.Get("Content-Type"),
		Caption:  req.Caption,
	}
	return l.svcCtx.Store.AddAttachment(req.ProjectID, req.TaskID, a)
}
