// Code generated by craftgo. DO NOT EDIT.

package headerechoservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	transport "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/transport/header-echo-service"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// RegisterRoutes wires every HeaderEchoService endpoint onto srv. Patterns
// use the Go 1.22 method-prefixed form so VERB and path match together;
// service prefix and OpenAPI basePath are baked in. Methods declaring
// `@middlewares(...)` are wrapped via the corresponding fields on
// ServiceContext (embedded Middlewares struct), so no runtime name
// lookup is required - the values come pre-wired.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api/header-echo", transport.ListItems(svcCtx))
}
