// Code generated by craftgo. DO NOT EDIT.

package rawmodes

import (
	"time"

	"github.com/craftgodotdev/craftgo/pkg/server"

	transport "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/transport/raw_modes_service"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RegisterRoutes registers the RawModesService routes on srv.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api/raw/pt", transport.PtPlain(svcCtx), svcCtx.Timing)
	srv.Handle("GET /api/raw/pt/items/{id}", transport.PtBlocks(svcCtx), svcCtx.Timing)
	srv.Handle("GET /api/raw/pt/timeout", server.WithLimits(transport.PtTimeout(svcCtx), server.Limits{Timeout: 1 * time.Second}), svcCtx.Timing)
	srv.Handle("GET /api/raw/rr", transport.RrNoReq(svcCtx), svcCtx.Timing)
	srv.Handle("POST /api/raw/rr/items/{id}", transport.RrReq(svcCtx), svcCtx.Timing)
	srv.Handle("POST /api/raw/rr/upload", transport.RrMultipart(svcCtx), svcCtx.Timing)
	srv.Handle("GET /api/raw/rr/xpkg/{id}", transport.RrXpkg(svcCtx), svcCtx.Timing)
	srv.Handle("GET /api/raw/rr/late", transport.RrLate(svcCtx), svcCtx.Timing)
	srv.Handle("GET /api/raw/rr/nomw", transport.RrNoMw(svcCtx))
	srv.Handle("GET /api/raw/rq/items/{id}", transport.RqNoResp(svcCtx), svcCtx.Timing)
	srv.Handle("POST /api/raw/rq", transport.RqResp(svcCtx), svcCtx.Timing)
	srv.Handle("GET /api/raw/rq/page", transport.RqPage(svcCtx), svcCtx.Timing)
	srv.Handle("POST /api/raw/rq/docs", transport.RqDocsReq(svcCtx), svcCtx.Timing)
	srv.Handle("POST /api/raw/rq/limits", server.WithLimits(transport.RqLimits(svcCtx), server.Limits{Timeout: 2 * time.Second, MaxBodySize: 1 << 10}), svcCtx.Timing)
}
