// Code generated by craftgo. DO NOT EDIT.

package streamservice

import (
	"net/http"

	service "github.com/craftgodotdev/craftgo/example/raw/internal/service/stream-service"
	"github.com/craftgodotdev/craftgo/example/raw/svccontext"
)

// Download returns the http.HandlerFunc for the
// GET Download passthrough endpoint. The framework stays
// out of the way: logic receives the raw http.ResponseWriter and
// *http.Request and writes the response directly.
func Download(svcCtx *svccontext.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := service.NewDownloadService(r.Context(), svcCtx)
		if err := l.Download(w, r); err != nil {
			writeError(w, err)
			return
		}
	}
}
