// Code generated by craftgo. DO NOT EDIT.

package accountservice

import (
	"github.com/craftgodotdev/craftgo/pkg/server"
	transport "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/transport/account-service"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// RegisterRoutes wires every AccountService endpoint onto srv. Patterns
// use the Go 1.22 method-prefixed form so VERB and path match together;
// service prefix and OpenAPI basePath are baked in. Methods declaring
// `@middlewares(...)` are wrapped via the corresponding fields on
// ServiceContext (embedded Middlewares struct), so no runtime name
// lookup is required - the values come pre-wired.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("POST /api/account/signup", svcCtx.RateLimit(transport.Signup(svcCtx)))
	srv.Handle("POST /api/account/login", svcCtx.RateLimit(transport.Login(svcCtx)))
	srv.Handle("GET /api/account/me", svcCtx.RateLimit(svcCtx.AuthRequired(transport.Me(svcCtx))))
	srv.Handle("POST /api/account/logout", svcCtx.RateLimit(svcCtx.AuthRequired(svcCtx.Audit(transport.Logout(svcCtx)))))
	srv.Handle("DELETE /api/account/admin/{id}", svcCtx.RateLimit(svcCtx.BasicAuth(svcCtx.Audit(transport.DeleteAccount(svcCtx)))))
	srv.Handle("POST /api/account/admin/reset", svcCtx.Audit(transport.Reset(svcCtx)))
}
