// Code generated by craftgo. DO NOT EDIT.

package emptylists

import (
	"github.com/craftgodotdev/craftgo/pkg/server"

	transport "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/transport/empty_lists"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// RegisterRoutes registers the EmptyLists routes on srv.
func RegisterRoutes(srv *server.Server, svcCtx *svccontext.ServiceContext) {
	srv.Handle("GET /api/empty-lists/shapes", transport.GetShapes(svcCtx))
	srv.Handle("GET /api/empty-lists/clash", transport.GetClash(svcCtx))
	srv.Handle("GET /api/empty-lists/cycle", transport.GetCycle(svcCtx))
	srv.Handle("GET /api/empty-lists/nothing", transport.GetNothing(svcCtx))
	srv.Handle("GET /api/empty-lists/shared", transport.GetShared(svcCtx))
}
