// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package nestedservice

import (
	"context"

	types "github.com/craftgodotdev/craftgo/tests/e2e/cornercase/internal/types/nested"

	"github.com/craftgodotdev/craftgo/pkg/log"
	"github.com/craftgodotdev/craftgo/tests/e2e/cornercase/svccontext"
)

// EchoCubeService carries the per-request state for the
// EchoCube endpoint of NestedService. The embedded log.Logger is
// pre-bound to the request context (trace_id / span_id / request_id),
// so handlers can call l.Info(...) / l.Error(...) directly.
type EchoCubeService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewEchoCubeService constructs a fresh service instance bound to ctx.
// The Logger is pulled from log.Default() (set by Server.SetLogger)
// and seeded with WithContext(ctx) so OTel trace IDs ride every line.
func NewEchoCubeService(ctx context.Context, svcCtx *svccontext.ServiceContext) *EchoCubeService {
	return &EchoCubeService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// EchoCube is the service entry point. Replace the
// TODO with the real implementation.
func (l *EchoCubeService) EchoCube(req *types.Cube) (*types.Cube, error) {
	// TODO: implement
	return nil, nil
}
