// Code generated by craftgo. DO NOT EDIT.

package upstream

import (
	"fmt"
	"unicode/utf8"
)

// Validate returns the first constraint v violates, or nil.
func (v *PaymentSettledPayload) Validate() error {
	if utf8.RuneCountInString(v.InvoiceID) < 1 {
		return fmt.Errorf("invoiceId: length less than 1")
	}
	if v.Amount < 0 {
		return fmt.Errorf("amount: below minimum 0")
	}
	return nil
}
