// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package xdelegate

import (
	"context"

	"github.com/craftgodotdev/craftgo/pkg/log"

	types "github.com/craftgodotdev/craftgo/tests/e2e/matrix/internal/types/xdelegate"
	"github.com/craftgodotdev/craftgo/tests/e2e/matrix/svccontext"
)

// StoreService runs XDelegateService.Store for one request.
type StoreService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewStoreService binds StoreService to ctx; its Logger carries ctx's trace ids.
func NewStoreService(ctx context.Context, svcCtx *svccontext.ServiceContext) *StoreService {
	return &StoreService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Round-trips the delegating types so the handler path compiles too.
//
// Store implements XDelegateService.Store.
func (l *StoreService) Store(req *types.XDelegatedScalars) (*types.XDelegatedShapes, error) {
	// TODO: implement
	return nil, nil
}
