// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package stream

import (
	"bytes"
	"context"
	"net/http"
	"time"

	types "github.com/craftgodotdev/craftgo/example/raw/internal/types/stream"

	"github.com/craftgodotdev/craftgo/example/raw/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// DownloadService carries the per-request state for the Download endpoint of
// StreamService. The embedded log.Logger is pre-bound to the request
// context so logging surfaces trace_id / span_id / request_id.
type DownloadService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewDownloadService constructs a fresh service instance bound to ctx.
func NewDownloadService(ctx context.Context, svcCtx *svccontext.ServiceContext) *DownloadService {
	return &DownloadService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// demoFiles stands in for object storage. Keys are file names that satisfy
// DownloadReq's @pattern, so a lookup miss is a plain 404, never a path
// traversal - the framework validated req before this method ran.
var demoFiles = map[string][]byte{
	"hello.txt":   []byte("hello, raw world\n"),
	"notes.md":    []byte("# notes\n\n- raw response\n- typed request\n"),
	"payload.bin": bytes.Repeat([]byte{0xAB}, 4096),
}

var demoModTime = time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)

// Download is a raw-response entry point: the framework bound and
// validated req, logic owns the wire. http.ServeContent handles Range,
// If-Modified-Since and HEAD, which is why the *http.Request is passed in.
func (l *DownloadService) Download(w http.ResponseWriter, r *http.Request, req *types.DownloadReq) error {
	body, ok := demoFiles[req.File]
	if !ok {
		http.NotFound(w, r)
		return nil
	}
	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Disposition", `attachment; filename="`+req.File+`"`)
	http.ServeContent(w, r, req.File, demoModTime, bytes.NewReader(body))
	return nil
}
