// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package stream

import (
	"bytes"
	"compress/gzip"
	"context"
	"io"
	"net/http"
	"time"

	types "github.com/craftgodotdev/craftgo/example/raw/internal/types/stream"

	"github.com/craftgodotdev/craftgo/pkg/server"

	"github.com/craftgodotdev/craftgo/example/raw/svccontext"
	"github.com/craftgodotdev/craftgo/pkg/log"
)

// SnapshotService carries the per-request state for the Snapshot endpoint of
// StreamService. The embedded log.Logger is pre-bound to the request
// context so logging surfaces trace_id / span_id / request_id.
type SnapshotService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewSnapshotService constructs a fresh service instance bound to ctx.
func NewSnapshotService(ctx context.Context, svcCtx *svccontext.ServiceContext) *SnapshotService {
	return &SnapshotService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// snapshotCache stands in for a Redis entry that was gzip-compressed when it
// was written: the read path never encodes JSON, it hands the stored bytes
// to the client as they are whenever the client accepts gzip.
var snapshotCache = map[string][]byte{}

func init() {
	for _, region := range []string{"global", "eu", "us"} {
		snapshotCache[region] = gzipJSON(types.Snapshot{
			Region:      region,
			GeneratedAt: time.Date(2026, 9, 5, 0, 0, 0, 0, time.UTC).Format(time.RFC3339),
			Items:       []string{"alpha", "beta", "gamma"},
		})
	}
}

func gzipJSON(v any) []byte {
	var buf bytes.Buffer
	zw := gzip.NewWriter(&buf)
	_ = server.JSON().Encode(zw, v)
	_ = zw.Close()
	return buf.Bytes()
}

func gunzip(b []byte) ([]byte, error) {
	zr, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
		return nil, err
	}
	return io.ReadAll(zr)
}

// Snapshot is a raw-response entry point over a bound + validated request.
// The response block documents types.Snapshot for clients; the bytes on the
// wire come straight from the cache, verbatim when the client accepts gzip
// and decoded otherwise - WritePrecompressed negotiates per request.
func (l *SnapshotService) Snapshot(w http.ResponseWriter, r *http.Request, req *types.SnapshotReq) error {
	region := "global"
	if req.Region != nil {
		region = *req.Region
	}
	blob, ok := snapshotCache[region]
	if !ok {
		http.NotFound(w, r)
		return nil
	}
	return server.WritePrecompressed(w, r, http.StatusOK, "application/json; charset=utf-8", "gzip", blob, gunzip)
}
