// Scaffold generated by craftgo. Safe to edit; will not be overwritten.

package stream

import (
	"context"
	"fmt"
	"net/http"

	"github.com/craftgodotdev/craftgo/pkg/log"

	"github.com/craftgodotdev/craftgo/example/raw/svccontext"
)

// TailLogsService runs StreamService.TailLogs for one request.
type TailLogsService struct {
	log.Logger
	ctx    context.Context
	svcCtx *svccontext.ServiceContext
}

// NewTailLogsService binds TailLogsService to ctx; its Logger carries ctx's trace ids.
func NewTailLogsService(ctx context.Context, svcCtx *svccontext.ServiceContext) *TailLogsService {
	return &TailLogsService{
		Logger: log.Default().WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// TailLogs is a bare passthrough: with no request block the path value is
// read straight off the request.
func (l *TailLogsService) TailLogs(w http.ResponseWriter, r *http.Request) error {
	service := r.PathValue("service")
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	for i := 1; i <= 3; i++ {
		if _, err := fmt.Fprintf(w, "%s: log line %d\n", service, i); err != nil {
			return nil
		}
	}
	return nil
}
